site_name: My Documentation
site_url: https://olegsirik.github.io/PoliTech/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true






