site_name: My Documentation
site_url: https://olegsirik.github.io/PoliTech/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

# Явно указываем все страницы в навигации
nav:
  - Главная: index.md
  - Установка: README.md
  - Руководства:
      - Начало работы: authN/README.md
      - Продвинутые настройки: guides/advanced.md
  - Справочник:
      - API: reference/api.md
      - FAQ: reference/faq.md

# Где лежат файлы (по умолчанию docs)
docs_dir: docs




