site_name: My Documentation
site_url: https://olegsirik.github.io/PoliTech/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

# Явно указываем все страницы в навигации
nav:
  - Главная: index.md
  - Установка: README.md
  - Руководства:
      - Руководство пользователя: user-docs/README.md
      - Руководство администратора: doc_admin/tenant.md
      - Руководство разработчика:
        - Аутентификация: authN/README.md
        - Авторизация: authZ/README.md
        - Шаблонизатор: development/Text-Template.md
        - Калькулятор : development/Calculator.md
  - Справочник:
      - API: api/api-overview.md
      
