-- V21: Move contract attributes to tree-shaped mt_attribute_def (tenant + document_id);
--      drop mt_entity_def and mt_contract_section.

CREATE TABLE mt_attribute_def_new (
    id BIGINT NOT NULL,
    parent_id BIGINT,
    tenant_id BIGINT NOT NULL,
    document_id VARCHAR(30) NOT NULL,
    var_code VARCHAR(50) NOT NULL,
    var_name VARCHAR(300) NOT NULL,
    var_path VARCHAR(500) NOT NULL,
    var_ord BIGINT NOT NULL DEFAULT 0,
    var_type VARCHAR(30) NOT NULL,
    var_cardinality VARCHAR(10) NOT NULL DEFAULT 'SINGLE',
    var_data_type VARCHAR(20) NOT NULL,
    var_value VARCHAR(500),
    var_cdm VARCHAR(500),
    var_list VARCHAR(100),
    code VARCHAR(50),
    name VARCHAR(250),
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT mt_attribute_def_new_pkey PRIMARY KEY (id),
    CONSTRAINT uk_attribute_def_new UNIQUE (tenant_id, document_id, var_code),
    CONSTRAINT mt_attribute_def_new_parent_fk FOREIGN KEY (parent_id) REFERENCES mt_attribute_def_new(id)
);





-- Вставка данных
INSERT INTO mt_attribute_def_new (
    id, parent_id, tenant_id, document_id, var_code, var_name, var_path, var_ord, 
    var_type, var_cardinality, var_data_type, var_value, var_cdm, var_list, code, name, is_system
) VALUES
(362, 359, 1, 'INSURANCE_CONTRACT', '159_ext_id', 'Страхователь.внешний id', 'policyHolder.person.ext_id', 31, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.ext_id', NULL, 'ext_id', 'Внешний id', false),
(363, 359, 1, 'INSURANCE_CONTRACT', '170_firstName', 'Страхователь.имя', 'policyHolder.person.firstName', 2, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.firstName', NULL, 'firstName', 'Имя', false),
(364, 359, 1, 'INSURANCE_CONTRACT', '160_birthPlace', 'Страхователь.место рождения', 'policyHolder.person.birthPlace', 13, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.birthPlace', NULL, 'birthPlace', 'Место рождения', false),
(243, 348, 1, 'INSURANCE_CONTRACT', 'io_doc_countryCode', 'Io.документ.страна выдачи документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].countryCode', 71, 'IN', 'SINGLE', 'STRING', 'RU', 'insuredObjects.identifiers.countryCode', 'country2', 'countryCode', 'Страна выдачи документа', false),
(270, 351, 1, 'INSURANCE_CONTRACT', 'io_device_countryCode', 'Застрахованное ус-во. код страны', 'insuredObjects[0].device.countryCode', 118, 'IN', 'SINGLE', 'STRING', 'RU', 'insuredObjects.device.countryCode', 'country2', 'device_countryCode', 'Код страны', false),
(269, 351, 1, 'INSURANCE_CONTRACT', 'io_device_devicePrice', 'Застрахованное ус-во. цена', 'insuredObjects[0].device.devicePrice', 119, 'IN', 'SINGLE', 'NUMBER', '10000', 'insuredObjects.device.devicePrice', NULL, 'device_devicePrice', 'Цена', false),
(357, 3, 1, 'INSURANCE_CONTRACT', '343_organization', 'Юр.лицо', 'organization', 12, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'organization', NULL, 'organization', 'Юр.лицо', false),
(358, 3, 1, 'INSURANCE_CONTRACT', '344_identifiers', 'Документ', 'identifiers[?(@.isPrimary)]', 13, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'identifiers', NULL, 'identifiers', 'Документ', false),
(359, 3, 1, 'INSURANCE_CONTRACT', '341_person', 'Физ.лицо', 'person', 10, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'person', NULL, 'person', 'Физ.лицо', false),
(199, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_fiasId', 'Ph.адрес.код фиас', 'policyHolder.addresses[?(@.isPrimary)].fiasId', 95, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.fiasId', NULL, 'fiasId', 'Код фиас', false),
(365, 359, 1, 'INSURANCE_CONTRACT', '161_fullNameEn', 'Страхователь.полное фио англ', 'policyHolder.person.fullNameEn', 12, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.fullNameEn', NULL, 'fullNameEn', 'Полное фио англ', false),
(366, 359, 1, 'INSURANCE_CONTRACT', '162_fullName', 'Страхователь.полное фио', 'policyHolder.person.fullName', 9, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.fullName', NULL, 'fullName', 'Полное фио', false),
(367, 359, 1, 'INSURANCE_CONTRACT', '164_age_issue', 'Страхователь.возраст на дату выпуска договора', 'null', 142, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_issue', 'Возраст на дату выпуска договора', false),
(368, 359, 1, 'INSURANCE_CONTRACT', '166_birthDate', 'Страхователь.дата рождения', 'policyHolder.person.birthDate', 7, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.birthDate', NULL, 'birthDate', 'Дата рождения', false),
(369, 359, 1, 'INSURANCE_CONTRACT', '169_gender', 'Страхователь.пол', 'policyHolder.person.gender', 18, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.gender', 'gender', 'gender', 'Пол', false),
(370, 359, 1, 'INSURANCE_CONTRACT', '171_isPublicOfficial', 'Страхователь.признак пдл', 'policyHolder.person.isPublicOfficial', 26, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.isPublicOfficial', 'bool', 'isPublicOfficial', 'Признак пдл', false),
(254, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_flat', 'Io.адрес.квартира', 'insuredObjects[0].addresses[?(@.isPrimary)].flat', 88, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.flat', NULL, 'flat', 'Квартира', false),
(255, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_building', 'Io.адрес.строение', 'insuredObjects[0].addresses[?(@.isPrimary)].building', 85, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.building', NULL, 'building', 'Строение', false),
(177, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_ext_id', 'Страхователь.внешний id (юрик)', 'policyHolder.organization.ext_id', 47, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.ext_id', NULL, 'ext_id', 'Внешний id (юрик)', false),
(239, 347, 1, 'INSURANCE_CONTRACT', 'io_email', 'Застрахованный.email', 'insuredObjects[0].contacts.email', 51, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.contacts.email', NULL, 'email', 'Email', false),
(263, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_addressStrEn', 'Io.адрес.адресная строка англ', 'insuredObjects[0].addresses[?(@.isPrimary)].addressStrEn', 100, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.addressStrEn', NULL, 'addressStrEn', 'Адресная строка англ', false),
(371, 359, 1, 'INSURANCE_CONTRACT', '158_isResident', 'Страхователь.резидент рф', 'policyHolder.person.isResident', 28, 'IN', 'SINGLE', 'STRING', 'true', 'policyHolder.person.isResident', 'bool', 'isResident', 'Резидент рф', false),
(372, 359, 1, 'INSURANCE_CONTRACT', '165_familyState', 'Страхователь.семейное положение', 'policyHolder.person.familyState', 20, 'IN', 'SINGLE', 'STRING', 'SINGLE', 'policyHolder.person.familyState', 'familyState', 'familyState', 'Семейное положение', false),
(373, 359, 1, 'INSURANCE_CONTRACT', '157_age_end', 'Страхователь.возраст на дату окончания договора', 'null', 141, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_end', 'Возраст на дату окончания договора', false),
(245, 348, 1, 'INSURANCE_CONTRACT', 'io_doc_serial', 'Io.документ.серия документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].serial', 58, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.serial', NULL, 'serial', 'Серия документа', false),
(159, 341, 1, 'INSURANCE_CONTRACT', 'ph_ext_id', 'Страхователь.внешний id', 'policyHolder.person.ext_id', 31, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.ext_id', NULL, 'ext_id', 'Внешний id', false),
(234, 346, 1, 'INSURANCE_CONTRACT', 'io_isResident', 'Застрахованный.резидент рф', 'insuredObjects[0].person.isResident', 27, 'IN', 'SINGLE', 'STRING', 'true', 'insuredObjects.person.isResident', 'bool', 'isResident', 'Резидент рф', false),
(200, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_street', 'Ph.адрес.улица', 'policyHolder.addresses[?(@.isPrimary)].street', 81, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.street', NULL, 'street', 'Улица', false),
(220, 1, 1, 'INSURANCE_CONTRACT', 'pl_productCode', 'Код продукта', 'productCode', 1, 'IN', 'SINGLE', 'STRING', NULL, 'productCode', NULL, 'productCode', 'Код продукта', false),
(231, 346, 1, 'INSURANCE_CONTRACT', 'io_middleName', 'Застрахованный.отчество', 'insuredObjects[0].person.middleName', 6, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.middleName', NULL, 'middleName', 'Отчество', false),
(232, 346, 1, 'INSURANCE_CONTRACT', 'io_birthDate', 'Застрахованный.дата рождения', 'insuredObjects[0].person.birthDate', 8, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.birthDate', NULL, 'birthDate', 'Дата рождения', false),
(250, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_fiasId', 'Io.адрес.код фиас', 'insuredObjects[0].addresses[?(@.isPrimary)].fiasId', 96, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.fiasId', NULL, 'fiasId', 'Код фиас', false),
(251, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_kladrId', 'Io.адрес.код кладр', 'insuredObjects[0].addresses[?(@.isPrimary)].kladrId', 94, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.kladrId', NULL, 'kladrId', 'Код кладр', false),
(252, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_zipCode', 'Io.адрес.индекс', 'insuredObjects[0].addresses[?(@.isPrimary)].zipCode', 91, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.zipCode', NULL, 'zipCode', 'Индекс', false),
(253, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_room', 'Io.адрес.комната', 'insuredObjects[0].addresses[?(@.isPrimary)].room', 90, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.room', NULL, 'room', 'Комната', false),
(206, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_countryCode', 'Ph.адрес.код страны', 'policyHolder.addresses[?(@.isPrimary)].countryCode', 76, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.addresses.countryCode', 'country2', 'countryCode', 'Код страны', false),
(170, 341, 1, 'INSURANCE_CONTRACT', 'ph_firstName', 'Страхователь.имя', 'policyHolder.person.firstName', 2, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.firstName', NULL, 'firstName', 'Имя', false),
(374, 359, 1, 'INSURANCE_CONTRACT', '163_citizenship', 'Страхователь.гражданство', 'policyHolder.person.citizenship', 16, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.person.citizenship', 'country2', 'citizenship', 'Гражданство', false),
(375, 359, 1, 'INSURANCE_CONTRACT', '167_middleName', 'Страхователь.отчество', 'policyHolder.person.middleName', 5, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.middleName', NULL, 'middleName', 'Отчество', false),
(376, 359, 1, 'INSURANCE_CONTRACT', '168_lastName', 'Страхователь.фамилия', 'policyHolder.person.lastName', 3, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.lastName', NULL, 'lastName', 'Фамилия', false),
(377, 360, 1, 'INSURANCE_CONTRACT', '172_phone', 'Страхователь.телефон', 'policyHolder.contacts.phone', 49, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.contacts.phone', NULL, 'phone', 'Телефон', false),
(378, 360, 1, 'INSURANCE_CONTRACT', '173_email', 'Страхователь.email', 'policyHolder.contacts.email', 52, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.contacts.email', NULL, 'email', 'Email', false),
(379, 357, 1, 'INSURANCE_CONTRACT', '177_ext_id', 'Страхователь.внешний id (юрик)', 'policyHolder.organization.ext_id', 47, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.ext_id', NULL, 'ext_id', 'Внешний id (юрик)', false),
(380, 357, 1, 'INSURANCE_CONTRACT', '187_fullName', 'Страхователь.полное наименование юр.лица', 'policyHolder.organization.fullName', 37, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.fullName', NULL, 'fullName', 'Полное наименование юр.лица', false),
(381, 357, 1, 'INSURANCE_CONTRACT', '184_legalForm', 'Страхователь.организационно-правовая форма', 'policyHolder.organization.legalForm', 40, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.legalForm', NULL, 'legalForm', 'Организационно-правовая форма', false),
(382, 357, 1, 'INSURANCE_CONTRACT', '182_ogrn', 'Страхователь.огрн', 'policyHolder.organization.ogrn', 42, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.ogrn', NULL, 'ogrn', 'Огрн', false),
(383, 357, 1, 'INSURANCE_CONTRACT', '180_isResident', 'Страхователь.резидент рф юр.лица', 'policyHolder.organization.isResident', 45, 'IN', 'SINGLE', 'STRING', 'true', 'policyHolder.organization.isResident', 'bool', 'isResident', 'Резидент рф юр.лица', false),
(384, 357, 1, 'INSURANCE_CONTRACT', '183_kpp', 'Страхователь.кпп', 'policyHolder.organization.kpp', 41, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.kpp', NULL, 'kpp', 'Кпп', false),
(385, 357, 1, 'INSURANCE_CONTRACT', '175_inn', 'Страхователь.инн юр.лица', 'policyHolder.organization.inn', 36, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.inn', NULL, 'inn', 'Инн юр.лица', false),
(386, 357, 1, 'INSURANCE_CONTRACT', '176_nciCode', 'Страхователь.нси код', 'policyHolder.organization.nciCode', 48, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.nciCode', NULL, 'nciCode', 'Нси код', false),
(387, 357, 1, 'INSURANCE_CONTRACT', '181_okpo', 'Страхователь.окпо', 'policyHolder.organization.okpo', 43, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.okpo', NULL, 'okpo', 'Окпо', false),
(388, 357, 1, 'INSURANCE_CONTRACT', '185_shortName', 'Страхователь.краткое наименование юр.лица', 'policyHolder.organization.shortName', 39, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.shortName', NULL, 'shortName', 'Краткое наименование юр.лица', false),
(389, 357, 1, 'INSURANCE_CONTRACT', '186_fullNameEn', 'Страхователь.полное наименование  юр.лица англ', 'policyHolder.organization.fullNameEn', 38, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.fullNameEn', NULL, 'fullNameEn', 'Полное наименование  юр.лица англ', false),
(390, 357, 1, 'INSURANCE_CONTRACT', '179_group', 'Страхователь.gруппа страхователя юл', 'policyHolder.organization.group', 46, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.group', NULL, 'group', 'Gруппа страхователя юл', false),
(391, 357, 1, 'INSURANCE_CONTRACT', '178_country', 'Страхователь.код страны регистрации', 'policyHolder.organization.country', 35, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.country', 'country2', 'country', 'Код страны регистрации', false),
(392, 357, 1, 'INSURANCE_CONTRACT', '174_bic', 'Страхователь.бик', 'policyHolder.organization.bic', 44, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.bic', NULL, 'bic', 'Бик', false),
(393, 358, 1, 'INSURANCE_CONTRACT', '188_dateIssue', 'Ph.документ.дата выдачи', 'policyHolder.identifiers[?(@.isPrimary)].dateIssue', 61, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.dateIssue', NULL, 'dateIssue', 'Дата выдачи', false),
(394, 358, 1, 'INSURANCE_CONTRACT', '189_divisionCode', 'Ph.документ.код подразделения', 'policyHolder.identifiers[?(@.isPrimary)].divisionCode', 67, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.divisionCode', NULL, 'divisionCode', 'Код подразделения', false),
(395, 358, 1, 'INSURANCE_CONTRACT', '190_validUntil', 'Ph.документ.действительно до', 'policyHolder.identifiers[?(@.isPrimary)].validUntil', 64, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.validUntil', NULL, 'validUntil', 'Действительно до', false),
(396, 358, 1, 'INSURANCE_CONTRACT', '191_whom', 'Ph.документ.кем выдан', 'policyHolder.identifiers[?(@.isPrimary)].whom', 65, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.whom', NULL, 'whom', 'Кем выдан', false),
(397, 358, 1, 'INSURANCE_CONTRACT', '192_ext_id', 'Ph.документ.внешний id', 'policyHolder.identifiers[?(@.isPrimary)].ext_id', 70, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.ext_id', NULL, 'ext_id', 'Внешний id', false),
(398, 358, 1, 'INSURANCE_CONTRACT', '193_countryCode', 'Ph.документ.страна выдачи документа', 'policyHolder.identifiers[?(@.isPrimary)].countryCode', 72, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.identifiers.countryCode', 'country2', 'countryCode', 'Страна выдачи документа', false),
(399, 358, 1, 'INSURANCE_CONTRACT', '196_number', 'Ph.документ.номер документа', 'policyHolder.identifiers[?(@.isPrimary)].number', 60, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.number', NULL, 'number', 'Номер документа', false),
(400, 358, 1, 'INSURANCE_CONTRACT', '194_typeCode', 'Ph.документ.код типа документа', 'policyHolder.identifiers[?(@.isPrimary)].typeCode', 55, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.typeCode', 'identifierType', 'typeCode', 'Код типа документа', false),
(188, 344, 1, 'INSURANCE_CONTRACT', 'ph_doc_dateIssue', 'Ph.документ.дата выдачи', 'policyHolder.identifiers[?(@.isPrimary)].dateIssue', 61, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.dateIssue', NULL, 'dateIssue', 'Дата выдачи', false),
(401, 358, 1, 'INSURANCE_CONTRACT', '195_serial', 'Ph.документ.серия документа', 'policyHolder.identifiers[?(@.isPrimary)].serial', 57, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.serial', NULL, 'serial', 'Серия документа', false),
(189, 344, 1, 'INSURANCE_CONTRACT', 'ph_doc_divisionCode', 'Ph.документ.код подразделения', 'policyHolder.identifiers[?(@.isPrimary)].divisionCode', 67, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.divisionCode', NULL, 'divisionCode', 'Код подразделения', false),
(190, 344, 1, 'INSURANCE_CONTRACT', 'ph_doc_validUntil', 'Ph.документ.действительно до', 'policyHolder.identifiers[?(@.isPrimary)].validUntil', 64, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.validUntil', NULL, 'validUntil', 'Действительно до', false),
(191, 344, 1, 'INSURANCE_CONTRACT', 'ph_doc_whom', 'Ph.документ.кем выдан', 'policyHolder.identifiers[?(@.isPrimary)].whom', 65, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.whom', NULL, 'whom', 'Кем выдан', false),
(284, 352, 1, 'INSURANCE_CONTRACT', 'io_buildingArea', 'Имущество.площадь здания', 'insuredObjects[0].property.buildingArea', 127, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.buildingArea', NULL, 'buildingArea', 'Площадь здания', false),
(285, 352, 1, 'INSURANCE_CONTRACT', 'io_repairYear', 'Имущество.год ремонта', 'insuredObjects[0].property.repairYear', 126, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.repairYear', NULL, 'repairYear', 'Год ремонта', false),
(187, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_fullName', 'Страхователь.полное наименование юр.лица', 'policyHolder.organization.fullName', 37, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.fullName', NULL, 'fullName', 'Полное наименование юр.лица', false),
(286, 352, 1, 'INSURANCE_CONTRACT', 'io_constructionYear', 'Имущество.год постройки', 'insuredObjects[0].property.constructionYear', 125, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.constructionYear', NULL, 'constructionYear', 'Год постройки', false),
(277, 352, 1, 'INSURANCE_CONTRACT', 'io_ceilingMaterial', 'Имущество.материал перекрытий', 'insuredObjects[0].property.ceilingMaterial', 123, 'IN', 'SINGLE', 'STRING', 'Смешанные', 'insuredObjects.property.ceilingMaterial', NULL, 'ceilingMaterial', 'Материал перекрытий', false),
(278, 352, 1, 'INSURANCE_CONTRACT', 'io_isNewBuilding', 'Имущество.новостройка', 'insuredObjects[0].property.isNewBuilding', 133, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.isNewBuilding', NULL, 'isNewBuilding', 'Новостройка', false),
(288, 352, 1, 'INSURANCE_CONTRACT', 'io_wallsMaterialOther', 'Имущество.материал стен другой', 'insuredObjects[0].property.wallsMaterialOther', 122, 'IN', 'SINGLE', 'STRING', 'Каменные, кирпичные', 'insuredObjects.property.wallsMaterialOther', NULL, 'wallsMaterialOther', 'Материал стен другой', false),
(402, 361, 1, 'INSURANCE_CONTRACT', '199_fiasId', 'Ph.адрес.код фиас', 'policyHolder.addresses[?(@.isPrimary)].fiasId', 95, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.fiasId', NULL, 'fiasId', 'Код фиас', false),
(403, 361, 1, 'INSURANCE_CONTRACT', '200_street', 'Ph.адрес.улица', 'policyHolder.addresses[?(@.isPrimary)].street', 81, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.street', NULL, 'street', 'Улица', false),
(404, 361, 1, 'INSURANCE_CONTRACT', '206_countryCode', 'Ph.адрес.код страны', 'policyHolder.addresses[?(@.isPrimary)].countryCode', 76, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.addresses.countryCode', 'country2', 'countryCode', 'Код страны', false),
(405, 361, 1, 'INSURANCE_CONTRACT', '197_region', 'Ph.адрес.регион', 'policyHolder.addresses[?(@.isPrimary)].region', 77, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.region', NULL, 'region', 'Регион', false),
(406, 361, 1, 'INSURANCE_CONTRACT', '201_house', 'Ph.адрес.дом', 'policyHolder.addresses[?(@.isPrimary)].house', 83, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.house', NULL, 'house', 'Дом', false),
(407, 361, 1, 'INSURANCE_CONTRACT', '207_kladrId', 'Ph.адрес.код кладр', 'policyHolder.addresses[?(@.isPrimary)].kladrId', 93, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.kladrId', NULL, 'kladrId', 'Код кладр', false),
(408, 361, 1, 'INSURANCE_CONTRACT', '208_zipCode', 'Ph.адрес.индекс', 'policyHolder.addresses[?(@.isPrimary)].zipCode', 92, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.zipCode', NULL, 'zipCode', 'Индекс', false),
(409, 361, 1, 'INSURANCE_CONTRACT', '209_room', 'Ph.адрес.комната', 'policyHolder.addresses[?(@.isPrimary)].room', 89, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.room', NULL, 'room', 'Комната', false),
(410, 361, 1, 'INSURANCE_CONTRACT', '210_building', 'Ph.адрес.строение', 'policyHolder.addresses[?(@.isPrimary)].building', 86, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.building', NULL, 'building', 'Строение', false),
(411, 361, 1, 'INSURANCE_CONTRACT', '198_typeCode', 'Ph.адрес.тип адреса', 'policyHolder.addresses[?(@.isPrimary)].typeCode', 74, 'IN', 'SINGLE', 'STRING', 'REGISTRATION', 'policyHolder.addresses.typeCode', 'addressType', 'typeCode', 'Тип адреса', false),
(412, 361, 1, 'INSURANCE_CONTRACT', '204_ext_id', 'Ph.адрес.внешний id', 'policyHolder.addresses[?(@.isPrimary)].ext_id', 101, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.ext_id', NULL, 'ext_id', 'Внешний id', false),
(413, 361, 1, 'INSURANCE_CONTRACT', '205_addressStr', 'Ph.адрес.адресная строка', 'policyHolder.addresses[?(@.isPrimary)].addressStr', 98, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.addressStr', NULL, 'addressStr', 'Адресная строка', false),
(287, 352, 1, 'INSURANCE_CONTRACT', 'io_ceilingMaterialOther', 'Имущество.материал перекрытий другой', 'insuredObjects[0].property.ceilingMaterialOther', 124, 'IN', 'SINGLE', 'STRING', 'Смешанные', 'insuredObjects.property.ceilingMaterialOther', NULL, 'ceilingMaterialOther', 'Материал перекрытий другой', false),
(267, 351, 1, 'INSURANCE_CONTRACT', 'io_device_typeCode', 'Застрахованное ус-во. код типа', 'insuredObjects[0].device.deviceTypeCode', 106, 'IN', 'SINGLE', 'STRING', 'PHONE', 'insuredObjects.device.deviceTypeCode', 'deviceType', 'device_typeCode', 'Код типа', false),
(258, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_region', 'Io.адрес.регион', 'insuredObjects[0].addresses[?(@.isPrimary)].region', 78, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.region', NULL, 'region', 'Регион', false),
(293, 352, 1, 'INSURANCE_CONTRACT', 'io_commissioningDate', 'Имущество.дата ввода в эксплуатацию', 'insuredObjects[0].property.commissioningDate', 135, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.commissioningDate', NULL, 'commissioningDate', 'Дата ввода в эксплуатацию', false),
(273, 351, 1, 'INSURANCE_CONTRACT', 'io_device_osVersion', 'Застрахованное ус-во. версия ос', 'insuredObjects[0].device.osVersion', 116, 'IN', 'SINGLE', 'STRING', '10', 'insuredObjects.device.osVersion', NULL, 'device_osVersion', 'Версия ос', false),
(240, 347, 1, 'INSURANCE_CONTRACT', 'io_phone', 'Застрахованный.телефон', 'insuredObjects[0].contacts.phone', 50, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.contacts.phone', NULL, 'phone', 'Телефон', false),
(281, 352, 1, 'INSURANCE_CONTRACT', 'io_wearCoefficient', 'Имущество.коэффициент износа', 'insuredObjects[0].property.wearCoefficient', 130, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.wearCoefficient', NULL, 'wearCoefficient', 'Коэффициент износа', false),
(238, 346, 1, 'INSURANCE_CONTRACT', 'io_age_end', 'Возраст застрахованного на дату окончания полиса', 'null', 140, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_end', 'Возраст застрахованного на дату окончания полиса', false),
(249, 348, 1, 'INSURANCE_CONTRACT', 'io_doc_dateIssue', 'Io.документ.дата выдачи', 'insuredObjects[0].identifiers[?(@.isPrimary)].dateIssue', 62, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.dateIssue', NULL, 'dateIssue', 'Дата выдачи', false),
(260, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_ext_id', 'Io.адрес.внешний id', 'insuredObjects[0].addresses[?(@.isPrimary)].ext_id', 102, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.ext_id', NULL, 'ext_id', 'Внешний id', false),
(414, 361, 1, 'INSURANCE_CONTRACT', '211_city', 'Ph.адрес.город', 'policyHolder.addresses[?(@.isPrimary)].city', 79, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.city', NULL, 'city', 'Город', false),
(415, 361, 1, 'INSURANCE_CONTRACT', '202_flat', 'Ph.адрес.квартира', 'policyHolder.addresses[?(@.isPrimary)].flat', 87, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.flat', NULL, 'flat', 'Квартира', false),
(416, 361, 1, 'INSURANCE_CONTRACT', '203_addressStrEn', 'Ph.адрес.адресная строка англ', 'policyHolder.addresses[?(@.isPrimary)].addressStrEn', 99, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.addressStrEn', NULL, 'addressStrEn', 'Адресная строка англ', false),
(417, 349, 1, 'INSURANCE_CONTRACT', '393_dateIssue', 'Ph.документ.дата выдачи', 'policyHolder.identifiers[?(@.isPrimary)].dateIssue', 61, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.dateIssue', NULL, 'dateIssue', 'Дата выдачи', false),
(418, 349, 1, 'INSURANCE_CONTRACT', '394_divisionCode', 'Ph.документ.код подразделения', 'policyHolder.identifiers[?(@.isPrimary)].divisionCode', 67, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.divisionCode', NULL, 'divisionCode', 'Код подразделения', false),
(419, 349, 1, 'INSURANCE_CONTRACT', '395_validUntil', 'Ph.документ.действительно до', 'policyHolder.identifiers[?(@.isPrimary)].validUntil', 64, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.validUntil', NULL, 'validUntil', 'Действительно до', false),
(420, 349, 1, 'INSURANCE_CONTRACT', '396_whom', 'Ph.документ.кем выдан', 'policyHolder.identifiers[?(@.isPrimary)].whom', 65, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.whom', NULL, 'whom', 'Кем выдан', false),
(421, 349, 1, 'INSURANCE_CONTRACT', '397_ext_id', 'Ph.документ.внешний id', 'policyHolder.identifiers[?(@.isPrimary)].ext_id', 70, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.ext_id', NULL, 'ext_id', 'Внешний id', false),
(422, 349, 1, 'INSURANCE_CONTRACT', '398_countryCode', 'Ph.документ.страна выдачи документа', 'policyHolder.identifiers[?(@.isPrimary)].countryCode', 72, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.identifiers.countryCode', 'country2', 'countryCode', 'Страна выдачи документа', false),
(423, 349, 1, 'INSURANCE_CONTRACT', '399_number', 'Ph.документ.номер документа', 'policyHolder.identifiers[?(@.isPrimary)].number', 60, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.number', NULL, 'number', 'Номер документа', false),
(424, 349, 1, 'INSURANCE_CONTRACT', '400_typeCode', 'Ph.документ.код типа документа', 'policyHolder.identifiers[?(@.isPrimary)].typeCode', 55, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.typeCode', 'identifierType', 'typeCode', 'Код типа документа', false),
(425, 349, 1, 'INSURANCE_CONTRACT', '401_serial', 'Ph.документ.серия документа', 'policyHolder.identifiers[?(@.isPrimary)].serial', 57, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.serial', NULL, 'serial', 'Серия документа', false),
(2, 356, 1, 'INSURANCE_CONTRACT', 'сommission', 'Агентская комиссия', 'сommission', 10, 'IN', 'SINGLE', 'OBJECT', NULL, 'сommission', NULL, 'сommission', 'Агентская комиссия', false),
(289, 352, 1, 'INSURANCE_CONTRACT', 'io_wallsMaterial', 'Имущество.материал стен', 'insuredObjects[0].property.wallsMaterial', 121, 'IN', 'SINGLE', 'STRING', 'Каменные, кирпичные', 'insuredObjects.property.wallsMaterial', NULL, 'wallsMaterial', 'Материал стен', false),
(264, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_addressStr', 'Io.адрес.адресная строка', 'insuredObjects[0].addresses[?(@.isPrimary)].addressStr', 97, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.addressStr', NULL, 'addressStr', 'Адресная строка', false),
(282, 352, 1, 'INSURANCE_CONTRACT', 'io_buildingValue', 'Имущество.стоимость здания', 'insuredObjects[0].property.buildingValue', 129, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.buildingValue', NULL, 'buildingValue', 'Стоимость здания', false),
(192, 344, 1, 'INSURANCE_CONTRACT', 'ph_doc_ext_id', 'Ph.документ.внешний id', 'policyHolder.identifiers[?(@.isPrimary)].ext_id', 70, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.ext_id', NULL, 'ext_id', 'Внешний id', false),
(233, 346, 1, 'INSURANCE_CONTRACT', 'io_fullName', 'Застрахованный.полное фио', 'insuredObjects[0].person.fullName', 10, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.fullName', NULL, 'fullName', 'Полное фио', false),
(274, 351, 1, 'INSURANCE_CONTRACT', 'io_device_imei', 'Застрахованное ус-во. imei', 'insuredObjects[0].device.imei', 115, 'IN', 'SINGLE', 'STRING', '1234567890', 'insuredObjects.device.imei', NULL, 'device_imei', 'Imei', false),
(236, 346, 1, 'INSURANCE_CONTRACT', 'io_fullNameEn', 'Застрахованный.полное фио англ', 'insuredObjects[0].person.fullNameEn', 11, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.fullNameEn', NULL, 'fullNameEn', 'Полное фио англ', false),
(184, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_legalForm', 'Страхователь.организационно-правовая форма', 'policyHolder.organization.legalForm', 40, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.legalForm', NULL, 'legalForm', 'Организационно-правовая форма', false),
(256, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_house', 'Io.адрес.дом', 'insuredObjects[0].addresses[?(@.isPrimary)].house', 84, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.house', NULL, 'house', 'Дом', false),
(257, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_street', 'Io.адрес.улица', 'insuredObjects[0].addresses[?(@.isPrimary)].street', 82, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.street', NULL, 'street', 'Улица', false),
(182, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_ogrn', 'Страхователь.огрн', 'policyHolder.organization.ogrn', 42, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.ogrn', NULL, 'ogrn', 'Огрн', false),
(262, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_city', 'Io.адрес.город', 'insuredObjects[0].addresses[?(@.isPrimary)].city', 80, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.city', NULL, 'city', 'Город', false),
(244, 348, 1, 'INSURANCE_CONTRACT', 'io_doc_number', 'Io.документ.номер документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].number', 59, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.number', NULL, 'number', 'Номер документа', false),
(235, 346, 1, 'INSURANCE_CONTRACT', 'io_ext_id', 'Застрахованный.внешний id', 'insuredObjects[0].person.ext_id', 33, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.ext_id', NULL, 'ext_id', 'Внешний id', false),
(214, 1, 1, 'INSURANCE_CONTRACT', 'pl_policyNumber', 'Номер договора', 'policyNumber', 5, 'IN', 'SINGLE', 'STRING', NULL, 'policyNumber', NULL, 'policyNumber', 'Номер договора', false),
(360, 3, 1, 'INSURANCE_CONTRACT', '342_contacts', 'Контакты', 'contacts', 11, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'contacts', NULL, 'contacts', 'Контакты', false),
(361, 3, 1, 'INSURANCE_CONTRACT', '345_addresses', 'Адрес', 'addresses[?(@.isPrimary)]', 14, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'addresses', NULL, 'addresses', 'Адрес', false),
(1, NULL, 1, 'INSURANCE_CONTRACT', 'policy', 'Договор страхования', '*', 1, 'OBJECT', 'SINGLE', 'OBJECT', NULL, '*', NULL, 'policy', 'Договор страхования', false),
(343, 4, 1, 'INSURANCE_CONTRACT', 'ph_organization', 'Юр.лицо', 'organization', 12, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'organization', NULL, 'organization', 'Юр.лицо', false),
(3, 1, 1, 'INSURANCE_CONTRACT', 'insurer', 'Страховщик', 'insurer', 200, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insurer', NULL, 'insurer', 'Страховщик', false),
(350, 5, 1, 'INSURANCE_CONTRACT', '24_addresses', 'Адрес', 'addresses[?(@.isPrimary)]', 24, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'addresses', NULL, 'addresses', 'Адрес', false),
(344, 4, 1, 'INSURANCE_CONTRACT', 'ph_identifiers', 'Документ', 'identifiers[?(@.isPrimary)]', 13, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'identifiers', NULL, 'identifiers', 'Документ', false),
(352, 5, 1, 'INSURANCE_CONTRACT', '26_property', 'Недвижимость', 'property', 26, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'property', NULL, 'property', 'Недвижимость', false),
(4, 1, 1, 'INSURANCE_CONTRACT', 'policyHolder', 'Страхователь', 'policyHolder', 300, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'policyHolder', NULL, 'policyHolder', 'Страхователь', false),
(5, 1, 1, 'INSURANCE_CONTRACT', 'insuredObject', 'Объект страхования', 'insuredObject[0]', 400, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObject', NULL, 'insuredObject', 'Объект страхования', false),
(279, 352, 1, 'INSURANCE_CONTRACT', 'io_propertyLocation', 'Имущество.расположение имущества', 'insuredObjects[0].property.propertyLocation', 132, 'IN', 'SINGLE', 'STRING', 'В многоквартирном доме', 'insuredObjects.property.propertyLocation', NULL, 'propertyLocation', 'Расположение имущества', false),
(272, 351, 1, 'INSURANCE_CONTRACT', 'io_device_tradeMark', 'Застрахованное ус-во. торговая марка', 'insuredObjects[0].device.tradeMark', 108, 'IN', 'SINGLE', 'STRING', 'Samsung', 'insuredObjects.device.tradeMark', NULL, 'device_tradeMark', 'Торговая марка', false),
(271, 353, 1, 'INSURANCE_CONTRACT', 'io_legs', 'Количество перелетов', 'insuredObjects[0].travelSegments[*].count()', 56, 'IN', 'SINGLE', 'NUMBER', NULL, 'insuredObjects.travelSegments[*].count()', NULL, 'legs', 'Количество перелетов', false),
(225, 346, 1, 'INSURANCE_CONTRACT', 'io_citizenship', 'Застрахованный.гражданство', 'insuredObjects[0].person.citizenship', 15, 'IN', 'SINGLE', 'STRING', 'RU', 'insuredObjects.person.citizenship', 'country2', 'citizenship', 'Гражданство', false),
(346, 5, 1, 'INSURANCE_CONTRACT', '20_person', 'Физ.лицо', 'person', 20, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'person', NULL, 'person', 'Физ.лицо', false),
(193, 344, 1, 'INSURANCE_CONTRACT', 'ph_doc_countryCode', 'Ph.документ.страна выдачи документа', 'policyHolder.identifiers[?(@.isPrimary)].countryCode', 72, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.identifiers.countryCode', 'country2', 'countryCode', 'Страна выдачи документа', false),
(213, 1, 1, 'INSURANCE_CONTRACT', 'pl_startDate', 'Дата начала действия договора', 'startDate', 23, 'IN', 'SINGLE', 'STRING', NULL, 'startDate', NULL, 'startDate', 'Дата начала действия договора', false),
(215, 1, 1, 'INSURANCE_CONTRACT', 'pl_endDate', 'Дата окончания договора', 'endDate', 29, 'IN', 'SINGLE', 'STRING', NULL, 'endDate', NULL, 'endDate', 'Дата окончания договора', false),
(216, 1, 1, 'INSURANCE_CONTRACT', 'gross_up_factor', 'Gross_up_factor 1/(1-kv)', 'null', 138, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'gross_up_factor', 'Gross_up_factor 1/(1-kv)', false),
(217, 1, 1, 'INSURANCE_CONTRACT', 'pl_TermDays', 'Срок полиса в днях', 'null', 144, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'TermDays', 'Срок полиса в днях', false),
(218, 1, 1, 'INSURANCE_CONTRACT', 'pl_TermMonths', 'Срок полиса в месяцах', 'null', 143, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'TermMonths', 'Срок полиса в месяцах', false),
(197, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_region', 'Ph.адрес.регион', 'policyHolder.addresses[?(@.isPrimary)].region', 77, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.region', NULL, 'region', 'Регион', false),
(160, 341, 1, 'INSURANCE_CONTRACT', 'ph_birthPlace', 'Страхователь.место рождения', 'policyHolder.person.birthPlace', 13, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.birthPlace', NULL, 'birthPlace', 'Место рождения', false),
(161, 341, 1, 'INSURANCE_CONTRACT', 'ph_fullNameEn', 'Страхователь.полное фио англ', 'policyHolder.person.fullNameEn', 12, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.fullNameEn', NULL, 'fullNameEn', 'Полное фио англ', false),
(354, 5, 1, 'INSURANCE_CONTRACT', '28_riskFactors', 'Доп. риски', 'riskFactors', 28, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'riskFactors', NULL, 'riskFactors', 'Доп. риски', false),
(201, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_house', 'Ph.адрес.дом', 'policyHolder.addresses[?(@.isPrimary)].house', 83, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.house', NULL, 'house', 'Дом', false),
(222, 5, 1, 'INSURANCE_CONTRACT', 'io_sumInsured', 'Страховая сумма объекта страхования', 'insuredObjects[0].sumInsured', 19, 'IN', 'SINGLE', 'NUMBER', '100000', 'insuredObjects.sumInsured', NULL, 'sumInsured', 'Страховая сумма объекта страхования', false),
(223, 5, 1, 'INSURANCE_CONTRACT', 'io_packageCode', 'Код пакета', 'insuredObjects[0].packageCode', 24, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.packageCode', NULL, 'packageCode', 'Код пакета', false),
(226, 346, 1, 'INSURANCE_CONTRACT', 'io_gender', 'Застрахованный.пол', 'insuredObjects[0].person.gender', 17, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.gender', 'gender', 'gender', 'Пол', false),
(227, 346, 1, 'INSURANCE_CONTRACT', 'io_familyState', 'Застрахованный.семейное положение', 'insuredObjects[0].person.familyState', 21, 'IN', 'SINGLE', 'STRING', 'SINGLE', 'insuredObjects.person.familyState', 'familyState', 'familyState', 'Семейное положение', false),
(228, 346, 1, 'INSURANCE_CONTRACT', 'io_isPublicOfficial', 'Застрахованный.признак пдл', 'insuredObjects[0].person.isPublicOfficial', 25, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.isPublicOfficial', 'bool', 'isPublicOfficial', 'Признак пдл', false),
(229, 346, 1, 'INSURANCE_CONTRACT', 'io_firstName', 'Застрахованный.имя', 'insuredObjects[0].person.firstName', 1, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.firstName', NULL, 'firstName', 'Имя', false),
(162, 341, 1, 'INSURANCE_CONTRACT', 'ph_fullName', 'Страхователь.полное фио', 'policyHolder.person.fullName', 9, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.fullName', NULL, 'fullName', 'Полное фио', false),
(353, 5, 1, 'INSURANCE_CONTRACT', '27_travelSegments', 'Сегмент авиаперевозки', 'travelSegments', 27, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'travelSegments', NULL, 'travelSegments', 'Сегмент авиаперевозки', false),
(294, 352, 1, 'INSURANCE_CONTRACT', 'io_propertyValue', 'Имущество.стоимость имущества', 'insuredObjects[0].property.propertyValue', 134, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.propertyValue', NULL, 'propertyValue', 'Стоимость имущества', false),
(196, 344, 1, 'INSURANCE_CONTRACT', 'ph_doc_number', 'Ph.документ.номер документа', 'policyHolder.identifiers[?(@.isPrimary)].number', 60, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.number', NULL, 'number', 'Номер документа', false),
(275, 351, 1, 'INSURANCE_CONTRACT', 'io_device_model', 'Застрахованное ус-во. модель', 'insuredObjects[0].device.model', 110, 'IN', 'SINGLE', 'STRING', 'Galaxy S21', 'insuredObjects.device.model', NULL, 'device_model', 'Модель', false),
(351, 5, 1, 'INSURANCE_CONTRACT', '25_device', 'Электронное устройство', 'device', 25, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'device', NULL, 'device', 'Электронное устройство', false),
(164, 341, 1, 'INSURANCE_CONTRACT', 'ph_age_issue', 'Страхователь.возраст на дату выпуска договора', 'null', 142, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_issue', 'Возраст на дату выпуска договора', false),
(166, 341, 1, 'INSURANCE_CONTRACT', 'ph_birthDate', 'Страхователь.дата рождения', 'policyHolder.person.birthDate', 7, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.birthDate', NULL, 'birthDate', 'Дата рождения', false),
(230, 346, 1, 'INSURANCE_CONTRACT', 'io_lastName', 'Застрахованный.фамилия', 'insuredObjects[0].person.lastName', 4, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.lastName', NULL, 'lastName', 'Фамилия', false),
(237, 346, 1, 'INSURANCE_CONTRACT', 'io_age_issue', 'Возраст застрахованного на дату выпуска полиса', 'null', 139, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_issue', 'Возраст застрахованного на дату выпуска полиса', false),
(298, 353, 1, 'INSURANCE_CONTRACT', 'io_departureTime', 'Время вылета', 'insuredObjects[0].travelSegments[*].departureTime', 109, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].departureTime', NULL, 'departureTime', 'Время вылета', false),
(299, 353, 1, 'INSURANCE_CONTRACT', 'io_departureDate', 'Дата вылета', 'insuredObjects[0].travelSegments[*].departureDate', 107, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].departureDate', NULL, 'departureDate', 'Дата вылета', false),
(219, 1, 1, 'INSURANCE_CONTRACT', 'pl_issueDate', 'Дата выпуска договора', 'issueDate', 10, 'IN', 'SINGLE', 'STRING', NULL, 'issueDate', NULL, 'issueDate', 'Дата выпуска договора', false),
(212, 1, 1, 'INSURANCE_CONTRACT', 'pl_premium', 'Премия по договору', 'premium', 32, 'IN', 'SINGLE', 'STRING', NULL, 'premium', NULL, 'premium', 'Премия по договору', false),
(300, 353, 1, 'INSURANCE_CONTRACT', 'io_ticketNr', 'Номер билета', 'insuredObjects[0].travelSegments[*].ticketNr', 105, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].ticketNr', NULL, 'ticketNr', 'Номер билета', false),
(301, 354, 1, 'INSURANCE_CONTRACT', 'rf_sport5', 'Доп.риск спорт #5', 'insuredObjects[0].riskFactors.sport5', 149, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport5', NULL, 'sport5', 'Доп.риск спорт #5', false),
(302, 354, 1, 'INSURANCE_CONTRACT', 'rf_sport1', 'Доп.риск спорт #1', 'insuredObjects[0].riskFactors.sport1', 145, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport1', NULL, 'sport1', 'Доп.риск спорт #1', false),
(303, 354, 1, 'INSURANCE_CONTRACT', 'rf_sport3', 'Доп.риск спорт #3', 'insuredObjects[0].riskFactors.sport3', 147, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport3', NULL, 'sport3', 'Доп.риск спорт #3', false),
(194, 344, 1, 'INSURANCE_CONTRACT', 'ph_doc_typeCode', 'Ph.документ.код типа документа', 'policyHolder.identifiers[?(@.isPrimary)].typeCode', 55, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.typeCode', 'identifierType', 'typeCode', 'Код типа документа', false),
(169, 341, 1, 'INSURANCE_CONTRACT', 'ph_gender', 'Страхователь.пол', 'policyHolder.person.gender', 18, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.gender', 'gender', 'gender', 'Пол', false),
(171, 341, 1, 'INSURANCE_CONTRACT', 'ph_isPublicOfficial', 'Страхователь.признак пдл', 'policyHolder.person.isPublicOfficial', 26, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.isPublicOfficial', 'bool', 'isPublicOfficial', 'Признак пдл', false),
(158, 341, 1, 'INSURANCE_CONTRACT', 'ph_isResident', 'Страхователь.резидент рф', 'policyHolder.person.isResident', 28, 'IN', 'SINGLE', 'STRING', 'true', 'policyHolder.person.isResident', 'bool', 'isResident', 'Резидент рф', false),
(165, 341, 1, 'INSURANCE_CONTRACT', 'ph_familyState', 'Страхователь.семейное положение', 'policyHolder.person.familyState', 20, 'IN', 'SINGLE', 'STRING', 'SINGLE', 'policyHolder.person.familyState', 'familyState', 'familyState', 'Семейное положение', false),
(283, 352, 1, 'INSURANCE_CONTRACT', 'io_landArea', 'Имущество.площадь участка', 'insuredObjects[0].property.landArea', 128, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.landArea', NULL, 'landArea', 'Площадь участка', false),
(207, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_kladrId', 'Ph.адрес.код кладр', 'policyHolder.addresses[?(@.isPrimary)].kladrId', 93, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.kladrId', NULL, 'kladrId', 'Код кладр', false),
(208, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_zipCode', 'Ph.адрес.индекс', 'policyHolder.addresses[?(@.isPrimary)].zipCode', 92, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.zipCode', NULL, 'zipCode', 'Индекс', false),
(209, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_room', 'Ph.адрес.комната', 'policyHolder.addresses[?(@.isPrimary)].room', 89, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.room', NULL, 'room', 'Комната', false),
(210, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_building', 'Ph.адрес.строение', 'policyHolder.addresses[?(@.isPrimary)].building', 86, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.building', NULL, 'building', 'Строение', false),
(221, 356, 1, 'INSURANCE_CONTRACT', 'pl_commRate', 'Процент кв по договору', 'appliedCommissionRate', 137, 'IN', 'SINGLE', 'NUMBER', NULL, 'appliedCommissionRate', NULL, 'commRate', 'Процент кв по договору', false),
(295, 353, 1, 'INSURANCE_CONTRACT', 'io_arrivalCity', 'Город прилета', 'insuredObjects[0].travelSegments[*].arrivalCity', 113, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].arrivalCity', NULL, 'arrivalCity', 'Город прилета', false),
(296, 353, 1, 'INSURANCE_CONTRACT', 'io_departureCity', 'Город вылета', 'insuredObjects[0].travelSegments[*].departureCity', 111, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].departureCity', NULL, 'departureCity', 'Город вылета', false),
(297, 353, 1, 'INSURANCE_CONTRACT', 'io_ticketPrice', 'Стоимость билета', 'insuredObjects[0].travelSegments[*].ticketPrice.sum()', 53, 'IN', 'SINGLE', 'NUMBER', NULL, 'insuredObjects.travelSegments[*].ticketPrice.sum()', NULL, 'ticketPrice', 'Стоимость билета', false),
(157, 341, 1, 'INSURANCE_CONTRACT', 'ph_age_end', 'Страхователь.возраст на дату окончания договора', 'null', 141, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_end', 'Возраст на дату окончания договора', false),
(198, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_typeCode', 'Ph.адрес.тип адреса', 'policyHolder.addresses[?(@.isPrimary)].typeCode', 74, 'IN', 'SINGLE', 'STRING', 'REGISTRATION', 'policyHolder.addresses.typeCode', 'addressType', 'typeCode', 'Тип адреса', false),
(265, 351, 1, 'INSURANCE_CONTRACT', 'io_device_licenseKey', 'Застрахованное ус-во. ключ лицензии', 'insuredObjects[0].device.licenseKey', 114, 'IN', 'SINGLE', 'STRING', '1234567890', 'insuredObjects.device.licenseKey', NULL, 'device_licenseKey', 'Ключ лицензии', false),
(266, 351, 1, 'INSURANCE_CONTRACT', 'io_device_osName', 'Застрахованное ус-во. название ос', 'insuredObjects[0].device.osName', 117, 'IN', 'SINGLE', 'STRING', 'Android', 'insuredObjects.device.osName', NULL, 'device_osName', 'Название ос', false),
(268, 351, 1, 'INSURANCE_CONTRACT', 'io_device_name', 'Застрахованное ус-во. название', 'insuredObjects[0].device.deviceName', 103, 'IN', 'SINGLE', 'STRING', 'Телефон', 'insuredObjects.device.deviceName', NULL, 'device_name', 'Название', false),
(180, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_isResident', 'Страхователь.резидент рф юр.лица', 'policyHolder.organization.isResident', 45, 'IN', 'SINGLE', 'STRING', 'true', 'policyHolder.organization.isResident', 'bool', 'isResident', 'Резидент рф юр.лица', false),
(183, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_kpp', 'Страхователь.кпп', 'policyHolder.organization.kpp', 41, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.kpp', NULL, 'kpp', 'Кпп', false),
(348, 5, 1, 'INSURANCE_CONTRACT', '22_organization', 'Юр.лицо', 'organization', 22, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'organization', NULL, 'organization', 'Юр.лицо', false),
(349, 5, 1, 'INSURANCE_CONTRACT', '23_identifiers', 'Документ', 'identifiers[?(@.isPrimary)]', 23, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'identifiers', NULL, 'identifiers', 'Документ', false),
(204, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_ext_id', 'Ph.адрес.внешний id', 'policyHolder.addresses[?(@.isPrimary)].ext_id', 101, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.ext_id', NULL, 'ext_id', 'Внешний id', false),
(205, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_addressStr', 'Ph.адрес.адресная строка', 'policyHolder.addresses[?(@.isPrimary)].addressStr', 98, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.addressStr', NULL, 'addressStr', 'Адресная строка', false),
(211, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_city', 'Ph.адрес.город', 'policyHolder.addresses[?(@.isPrimary)].city', 79, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.city', NULL, 'city', 'Город', false),
(175, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_inn', 'Страхователь.инн юр.лица', 'policyHolder.organization.inn', 36, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.inn', NULL, 'inn', 'Инн юр.лица', false),
(176, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_nciCode', 'Страхователь.нси код', 'policyHolder.organization.nciCode', 48, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.nciCode', NULL, 'nciCode', 'Нси код', false),
(181, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_okpo', 'Страхователь.окпо', 'policyHolder.organization.okpo', 43, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.okpo', NULL, 'okpo', 'Окпо', false),
(241, 348, 1, 'INSURANCE_CONTRACT', 'io_doc_validUntil', 'Io.документ.действительно до', 'insuredObjects[0].identifiers[?(@.isPrimary)].validUntil', 63, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.validUntil', NULL, 'validUntil', 'Действительно до', false),
(242, 348, 1, 'INSURANCE_CONTRACT', 'io_doc_whom', 'Io.документ.кем выдан', 'insuredObjects[0].identifiers[?(@.isPrimary)].whom', 66, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.whom', NULL, 'whom', 'Кем выдан', false),
(280, 352, 1, 'INSURANCE_CONTRACT', 'io_numberOfFloors', 'Имущество.количество этажей', 'insuredObjects[0].property.numberOfFloors', 131, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.numberOfFloors', NULL, 'numberOfFloors', 'Количество этажей', false),
(259, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_countryCode', 'Io.адрес.код страны', 'insuredObjects[0].addresses[?(@.isPrimary)].countryCode', 75, 'IN', 'SINGLE', 'STRING', 'RU', 'insuredObjects.addresses.countryCode', 'country2', 'countryCode', 'Код страны', false),
(195, 344, 1, 'INSURANCE_CONTRACT', 'ph_doc_serial', 'Ph.документ.серия документа', 'policyHolder.identifiers[?(@.isPrimary)].serial', 57, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.serial', NULL, 'serial', 'Серия документа', false),
(304, 354, 1, 'INSURANCE_CONTRACT', 'rf_sport2', 'Доп.риск спорт #2', 'insuredObjects[0].riskFactors.sport2', 146, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport2', NULL, 'sport2', 'Доп.риск спорт #2', false),
(305, 354, 1, 'INSURANCE_CONTRACT', 'rf_sport4', 'Доп.риск спорт #4', 'insuredObjects[0].riskFactors.sport4', 148, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport4', NULL, 'sport4', 'Доп.риск спорт #4', false),
(306, 354, 1, 'INSURANCE_CONTRACT', 'rf_profSport', 'Профессиональный спорт', 'insuredObjects[0].riskFactors.profSport', 150, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.profSport', NULL, 'profSport', 'Профессиональный спорт', false),
(163, 341, 1, 'INSURANCE_CONTRACT', 'ph_citizenship', 'Страхователь.гражданство', 'policyHolder.person.citizenship', 16, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.person.citizenship', 'country2', 'citizenship', 'Гражданство', false),
(347, 5, 1, 'INSURANCE_CONTRACT', '21_contacts', 'Контакты', 'contacts', 21, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'contacts', NULL, 'contacts', 'Контакты', false),
(185, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_shortName', 'Страхователь.краткое наименование юр.лица', 'policyHolder.organization.shortName', 39, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.shortName', NULL, 'shortName', 'Краткое наименование юр.лица', false),
(186, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_fullNameEn', 'Страхователь.полное наименование  юр.лица англ', 'policyHolder.organization.fullNameEn', 38, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.fullNameEn', NULL, 'fullNameEn', 'Полное наименование  юр.лица англ', false),
(202, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_flat', 'Ph.адрес.квартира', 'policyHolder.addresses[?(@.isPrimary)].flat', 87, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.flat', NULL, 'flat', 'Квартира', false),
(203, 345, 1, 'INSURANCE_CONTRACT', 'ph_addr_addressStrEn', 'Ph.адрес.адресная строка англ', 'policyHolder.addresses[?(@.isPrimary)].addressStrEn', 99, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.addressStrEn', NULL, 'addressStrEn', 'Адресная строка англ', false),
(290, 352, 1, 'INSURANCE_CONTRACT', 'io_floor', 'Имущество.этаж', 'insuredObjects[0].property.floor', 136, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.floor', NULL, 'floor', 'Этаж', false),
(291, 352, 1, 'INSURANCE_CONTRACT', 'io_cadastrNr', 'Имущество.кадастровый номер', 'insuredObjects[0].property.cadastrNr', 120, 'IN', 'SINGLE', 'STRING', '77:07:0018002:2590', 'insuredObjects.property.cadastrNr', NULL, 'cadastrNr', 'Кадастровый номер', false),
(292, 352, 1, 'INSURANCE_CONTRACT', 'io_propertyTypeCode', 'Имущество.тип имущества код', 'insuredObjects[0].property.propertyType.code', 104, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.propertyType.code', NULL, 'propertyTypeCode', 'Тип имущества код', false),
(246, 348, 1, 'INSURANCE_CONTRACT', 'io_doc_ext_id', 'Io.документ.внешний id', 'insuredObjects[0].identifiers[?(@.isPrimary)].ext_id', 69, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.ext_id', NULL, 'ext_id', 'Внешний id', false),
(248, 348, 1, 'INSURANCE_CONTRACT', 'io_doc_divisionCode', 'Io.документ.код подразделения', 'insuredObjects[0].identifiers[?(@.isPrimary)].divisionCode', 68, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.divisionCode', NULL, 'divisionCode', 'Код подразделения', false),
(341, 4, 1, 'INSURANCE_CONTRACT', 'ph_person', 'Физ.лицо', 'person', 10, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'person', NULL, 'person', 'Физ.лицо', false),
(356, 1, 1, 'INSURANCE_CONTRACT', 'pl_commission', 'Комиссия по договору', 'commission', 500, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'commission', NULL, 'commission', 'Комиссия по договору', false),
(342, 4, 1, 'INSURANCE_CONTRACT', 'ph_contacts', 'Контакты', 'contacts', 11, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'contacts', NULL, 'contacts', 'Контакты', false),
(345, 4, 1, 'INSURANCE_CONTRACT', 'ph_addresses', 'Адрес', 'addresses[?(@.isPrimary)]', 14, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'addresses', NULL, 'addresses', 'Адрес', false),
(167, 341, 1, 'INSURANCE_CONTRACT', 'ph_middleName', 'Страхователь.отчество', 'policyHolder.person.middleName', 5, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.middleName', NULL, 'middleName', 'Отчество', false),
(168, 341, 1, 'INSURANCE_CONTRACT', 'ph_lastName', 'Страхователь.фамилия', 'policyHolder.person.lastName', 3, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.lastName', NULL, 'lastName', 'Фамилия', false),
(247, 348, 1, 'INSURANCE_CONTRACT', 'io_doc_typeCode', 'Io.документ.код типа документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].typeCode', 54, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.typeCode', 'identifierType', 'typeCode', 'Код типа документа', false),
(261, 350, 1, 'INSURANCE_CONTRACT', 'io_addr_typeCode', 'Io.адрес.тип адреса', 'insuredObjects[0].addresses[?(@.isPrimary)].typeCode', 73, 'IN', 'SINGLE', 'STRING', 'REGISTRATION', 'insuredObjects.addresses.typeCode', 'addressType', 'typeCode', 'Тип адреса', false),
(179, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_group', 'Страхователь.gруппа страхователя юл', 'policyHolder.organization.group', 46, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.group', NULL, 'group', 'Gруппа страхователя юл', false),
(178, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_country', 'Страхователь.код страны регистрации', 'policyHolder.organization.country', 35, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.country', 'country2', 'country', 'Код страны регистрации', false),
(276, 351, 1, 'INSURANCE_CONTRACT', 'io_device_serialNr', 'Застрахованное ус-во. серийный номер', 'insuredObjects[0].device.serialNr', 112, 'IN', 'SINGLE', 'STRING', '1234567890', 'insuredObjects.device.serialNr', NULL, 'device_serialNr', 'Серийный номер', false),
(172, 342, 1, 'INSURANCE_CONTRACT', 'ph_phone', 'Страхователь.телефон', 'policyHolder.contacts.phone', 49, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.contacts.phone', NULL, 'phone', 'Телефон', false),
(173, 342, 1, 'INSURANCE_CONTRACT', 'ph_email', 'Страхователь.email', 'policyHolder.contacts.email', 52, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.contacts.email', NULL, 'email', 'Email', false),
(174, 343, 1, 'INSURANCE_CONTRACT', 'ph_org_bic', 'Страхователь.бик', 'policyHolder.organization.bic', 44, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.bic', NULL, 'bic', 'Бик', false),
(224, 346, 1, 'INSURANCE_CONTRACT', 'io_birthPlace', 'Застрахованный.место рождения', 'insuredObjects[0].person.birthPlace', 14, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.birthPlace', NULL, 'birthPlace', 'Место рождения', false);


DROP TABLE IF EXISTS mt_attribute_def CASCADE;
DROP TABLE IF EXISTS mt_entity_def CASCADE;
DROP TABLE IF EXISTS mt_contract_section CASCADE;

ALTER TABLE mt_attribute_def_new RENAME TO mt_attribute_def;
ALTER TABLE mt_attribute_def RENAME CONSTRAINT mt_attribute_def_new_pkey TO mt_attribute_def_pkey_id;
ALTER TABLE mt_attribute_def RENAME CONSTRAINT uk_attribute_def_new TO uk_attribute_def2;
ALTER TABLE mt_attribute_def RENAME CONSTRAINT mt_attribute_def_new_parent_fk TO mt_attribute_def_parent_fk2;


CREATE SEQUENCE IF NOT EXISTS mt_attribute_def_seq;
SELECT setval('mt_attribute_def_seq', (SELECT COALESCE(MAX(id), 1) FROM mt_attribute_def));

