CREATE TABLE IF NOT EXISTS pt_metadata(
    var_Code varchar(50) not null primary key,
    var_Name varchar(300) not null,
    var_Path varchar(100),
    var_Type varchar(20) not null,
    var_Value varchar(500),
    var_Cdm varchar(100) not null,
    nr varchar(100) not null,
    var_data_type varchar(10)
);

CREATE TABLE IF NOT EXISTS pt_refdata(
    ref_code varchar(50),
    md_Code varchar(50) not null,
    md_Name varchar(100) not null,
    primary key (ref_code, md_Code)
);


insert into pt_metadata (var_code, var_name, var_path, var_type, var_value, var_cdm, nr, var_data_type) values

('io_addr_addressStr', 'Адрес.адресная строка', 'insuredObjects[0].addresses[isPrimary].addressesStr', 'IN', '', 'insuredObject.addresses.addressStr', '133', 'STRING'),
('io_addr_addressStrEn', 'Адрес.адресная строка англ', 'insuredObjects[0].addresses[isPrimary].addressesStrEn', 'IN', '', 'insuredObject.addresses.addressStrEn', '134', 'STRING'),
('io_addr_building', 'Адрес.строение', 'insuredObjects[0].addresses[isPrimary].building', 'IN', '', 'insuredObject.addresses.building', '127', 'STRING'),
('io_addr_city', 'Адрес.город', 'insuredObjects[0].addresses[isPrimary].city', 'IN', '', 'insuredObject.addresses.city', '124', 'STRING'),
('io_addr_countryCode', 'Адрес.код страны', 'insuredObjects[0].addresses[isPrimary].countryCode', 'IN', 'RU', 'insuredObject.addresses.countryCode', '122', 'STRING'),
('io_addr_ext_id', 'Адрес.внешний ID', 'insuredObjects[0].addresses[isPrimary].ext_id', 'IN', '', 'insuredObject.addresses.ext_id', '136', 'STRING'),
('io_addr_fiasId', 'Адрес.код ФИАС', 'insuredObjects[0].addresses[isPrimary].fiasId', 'IN', '', 'insuredObject.addresses.fiasId', '132', 'STRING'),
('io_addr_flat', 'Адрес.квартира', 'insuredObjects[0].addresses[isPrimary].flat', 'IN', '', 'insuredObject.addresses.flat', '128', 'STRING'),
('io_addr_house', 'Адрес.дом', 'insuredObjects[0].addresses[isPrimary].house', 'IN', '', 'insuredObject.addresses.house', '126', 'STRING'),
('io_addr_kladrId', 'Адрес.код КЛАДР', 'insuredObjects[0].addresses[isPrimary].kladrId', 'IN', '', 'insuredObject.addresses.kladrId', '131', 'STRING'),
('io_addr_region', 'Адрес.регион', 'insuredObjects[0].addresses[isPrimary].region', 'IN', '', 'insuredObject.addresses.region', '123', 'STRING'),
('io_addr_room', 'Адрес.комната', 'insuredObjects[0].addresses[isPrimary].room', 'IN', '', 'insuredObject.addresses.room', '129', 'STRING'),
('io_addr_street', 'Адрес.улица', 'insuredObjects[0].addresses[isPrimary].street', 'IN', '', 'insuredObject.addresses.street', '125', 'STRING'),
('io_addr_typeCode', 'Адрес.тип адреса', 'insuredObjects[0].addresses[isPrimary].typeCode', 'IN', 'REGISTRATION', 'insuredObject.addresses.typeCode', '121', 'STRING'),
('io_addr_zipCode', 'Адрес.индекс', 'insuredObjects[0].addresses[isPrimary].zipCode', 'IN', '', 'insuredObject.addresses.zipCode', '130', 'STRING'),
('io_email', 'Застрахованный.email', 'insuredObjects[0].contacts[isPrimary].email', 'IN', '', 'insuredObject.contacts..email', '91', 'STRING'),
('io_phone', 'Застрахованный.телефон', 'insuredObjects[0].contacts[isPrimary].phone', 'IN', '', 'insuredObject.contacts.phone', '81', 'STRING'),
('io_device_countryCode', 'Застрахованное ус-во. код страны', 'insuredObjects[0].device.countryCode', 'IN', 'RU', 'insuredObject.device.countryCode', '1009', 'STRING'),
('io_device_name', 'Застрахованное ус-во. название', 'insuredObjects[0].device.deviceName', 'IN', 'Телефон', 'insuredObject.device.deviceName', '1001', 'STRING'),
('io_device_devicePrice', 'Застрахованное ус-во. цена', 'insuredObjects[0].device.devicePrice', 'IN', '10000', 'insuredObject.device.devicePrice', '1010', 'STRING'),
('io_device_typeCode', 'Застрахованное ус-во. код типа', 'insuredObjects[0].device.deviceTypeCode', 'IN', 'PHONE', 'insuredObject.device.deviceTypeCode', '1002', 'STRING'),
('io_device_imei', 'Застрахованное ус-во. IMEI', 'insuredObjects[0].device.imei', 'IN', '1234567890', 'insuredObject.device.imei', '1007', 'STRING'),
('io_device_licenseKey', 'Застрахованное ус-во. ключ лицензии', 'insuredObjects[0].device.licenseKey', 'IN', '1234567890', 'insuredObject.device.licenseKey', '1006', 'STRING'),
('io_device_model', 'Застрахованное ус-во. модель', 'insuredObjects[0].device.model', 'IN', 'Galaxy S21', 'insuredObject.device.model', '1004', 'STRING'),
('io_device_osName', 'Застрахованное ус-во. название ОС', 'insuredObjects[0].device.osName', 'IN', 'Android', 'insuredObject.device.osName', '1008', 'STRING'),
('io_device_osVersion', 'Застрахованное ус-во. версия ОС', 'insuredObjects[0].device.osVersion', 'IN', '10', 'insuredObject.device.osVersion', '1008', 'STRING'),
('io_device_serialNr', 'Застрахованное ус-во. серийный номер', 'insuredObjects[0].device.serialNr', 'IN', '1234567890', 'insuredObject.device.serialNr', '1005', 'STRING'),
('io_device_tradeMark', 'Застрахованное ус-во. торговая марка', 'insuredObjects[0].device.tradeMark', 'IN', 'Samsung', 'insuredObject.device.tradeMark', '1003', 'STRING'),
('io_doc_countryCode', 'Документ.страна выдачи документа', 'insuredObjects[0].identifiers[isPrimary].countryCode', 'IN', 'RU', 'insuredObject.identifiers.countryCode', '110', 'STRING'),
('io_doc_dateIssue', 'Документ.дата выдачи', 'insuredObjects[0].identifiers[isPrimary].dateIssue', 'IN', '', 'insuredObject.identifiers.dateIssue', '104', 'STRING'),
('io_doc_divisionCode', 'Документ.код подразделения', 'insuredObjects[0].identifiers[isPrimary].divisionCode', 'IN', '', 'insuredObject.identifiers.divisionCode', '107', 'STRING'),
('io_doc_ext_id', 'Документ.внешний ID', 'insuredObjects[0].identifiers[isPrimary].ext_id', 'IN', '', 'insuredObject.identifiers.ext_id', '109', 'STRING'),
('io_doc_number', 'Документ.номер документа', 'insuredObjects[0].identifiers[isPrimary].number', 'IN', '', 'insuredObject.identifiers.number', '103', 'STRING'),
('io_doc_serial', 'Документ.серия документа', 'insuredObjects[0].identifiers[isPrimary].serial', 'IN', '', 'insuredObject.identifiers.serial', '102', 'STRING'),
('io_doc_typeCode', 'Документ.код типа документа', 'insuredObjects[0].identifiers[isPrimary].typeCode', 'IN', '', 'insuredObject.identifiers.typeCode', '101', 'STRING'),
('io_doc_validUntil', 'Документ.действительно до', 'insuredObjects[0].identifiers[isPrimary].validUntil', 'IN', '', 'insuredObject.identifiers.validUntil', '105', 'STRING'),
('io_doc_whom', 'Документ.кем выдан', 'insuredObjects[0].identifiers[isPrimary].whom', 'IN', '', 'insuredObject.identifiers.whom', '106', 'STRING'),
('io_packageCode', 'Код пакета', 'insuredObjects[0].packageCode', 'IN', '0', 'insuredObject.packageCode', '11', 'STRING'),
('io_age_end', 'Возраст застрахованного на дату окончания полиса', '', 'MAGIC', '', 'insuredObject.person.age_end', '1102', 'NUMBER'),
('io_age_issue', 'Возраст застрахованного на дату выпуска полиса', '', 'MAGIC', '', 'insuredObject.person.age_issue', '1101', 'NUMBER'),
('io_birthDate', 'Застрахованный.дата рождения', 'insuredObjects[0].person.birthDate', 'IN', '', 'insuredObject.person.birthDate', '4', 'STRING'),
('io_birthPlace', 'Застрахованный.место рождения', 'insuredObjects[0].person.birthPlace', 'IN', '', 'insuredObject.person.birthPlace', '7', 'STRING'),
('io_citizenship', 'Застрахованный.гражданство', 'insuredObjects[0].person.citizenship', 'IN', 'RU', 'insuredObject.person.citizenship', '8', 'STRING'),
('io_ext_id', 'Застрахованный.внешний ID', 'insuredObjects[0].person.ext_id', 'IN', '', 'insuredObject.person.ext_id', '14', 'STRING'),
('io_familyState', 'Застрахованный.семейное положение', 'insuredObjects[0].person.familyState', 'IN', 'SINGLE', 'insuredObject.person.familyState', '10', 'STRING'),
('io_firstName', 'Застрахованный.имя', 'insuredObjects[0].person.firstName', 'IN', '', 'insuredObject.person.firstName', '1', 'STRING'),
('io_fullName', 'Застрахованный.полное ФИО', 'insuredObjects[0].person.fullName', 'IN', '', 'insuredObject.person.fullName', '5', 'STRING'),
('io_fullNameEn', 'Застрахованный.полное ФИО англ', 'insuredObjects[0].person.fullNameEn', 'IN', '', 'insuredObject.person.fullNameEn', '6', 'STRING'),
('io_gender', 'Застрахованный.пол', 'insuredObjects[0].person.gender', 'IN', '', 'insuredObject.person.gender', '9', 'STRING'),
('io_isPublicOfficial', 'Застрахованный.признак ПДЛ', 'insuredObjects[0].person.isPublicOfficial', 'IN', '', 'insuredObject.person.isPublicOfficial', '11', 'STRING'),
('io_lastName', 'Застрахованный.фамилия', 'insuredObjects[0].person.lastName', 'IN', '', 'insuredObject.person.lastName', '2', 'STRING'),
('io_middleName', 'Застрахованный.отчество', 'insuredObjects[0].person.middleName', 'IN', '', 'insuredObject.person.middleName', '3', 'STRING'),
('io_sumInsured', 'Страховая сумма объекта страхования', 'insuredObjects[0].sumInsured', 'IN', '100000', 'insuredObject.sumInsured', '10', 'NUMBER'),
('io_arrivalCity', 'город прилета', 'insuredObjects[0].travelSegments[*].arrivalCity', 'IN', '', 'insuredObject.travelSegments.arrivalCity', '1005', 'STRING'),
('io_departureCity', 'город вылета', 'insuredObjects[0].travelSegments[*].departureCity', 'IN', '', 'insuredObject.travelSegments.departureCity', '1004', 'STRING'),
('io_departureDate', 'дата вылета', 'insuredObjects[0].travelSegments[*].departureDate', 'IN', '', 'insuredObject.travelSegments.departureDate', '1002', 'STRING'),
('io_departureTime', 'время вылета', 'insuredObjects[0].travelSegments[*].departureTime', 'IN', '', 'insuredObject.travelSegments.departureTime', '1003', 'STRING'),
('io_legs', 'количество перелетов', 'insuredObjects[0].travelSegments[*].count()', 'IN', '', 'insuredObject.travelSegments.legs', '101', 'NUMBER'),
('io_ticketNr', 'номер билета', 'insuredObjects[0].travelSegments[*].ticketNr', 'IN', '', 'insuredObject.travelSegments.ticketNr', '1001', 'STRING'),
('io_ticketPrice', 'стоимость билета', 'insuredObjects[0].travelSegments[*].ticketPrice.sum()', 'IN', '', 'insuredObject.travelSegments.ticketPrice', '101', 'NUMBER'),
('io_isResident', 'Застрахованный.резидент РФ', 'insuredObjects[0].person.isResident', 'IN', 'true', 'insuredObjects[0].person.isResident', '12', 'STRING'),
('pl_TermDays', 'Срок полиса в днях', '', 'MAGIC', '', 'policy.magic.termDays', '1202', 'NUMBER'),
('pl_TermMonths', 'Срок полиса в месяцах', '', 'MAGIC', '', 'policy.magic.termMonths', '1201', 'NUMBER'),
('pl_endDate', 'дата окончания договора', 'endDate', 'IN', '', 'policy.policy.endDate', '12', 'STRING'),
('pl_issueDate', 'дата выпуска договора', 'issueDate', 'IN', '', 'policy.policy.issueDate', '15', 'STRING'),
('pl_policyNumber', 'номер договора', 'policyNumber', 'IN', '', 'policy.policy.policyNumber', '13', 'STRING'),
('pl_premium', 'премия по договору', 'premium', 'IN', '', 'policy.policy.premium', '14', 'STRING'),
('pl_productCode', 'Код продукта', 'productCode', 'IN', '', 'policy.policy.productCode', '10', 'STRING'),
('pl_startDate', 'дата начала действия договора', 'startDate', 'IN', '', 'policy.policy.startDate', '11', 'STRING'),
('ph_addr_addressStr', 'Адрес.адресная строка', 'policyHolder.address.addressStr', 'IN', '', 'policyHolder.addresses.addressStr', '133', 'STRING'),
('ph_addr_addressStrEn', 'Адрес.адресная строка англ', 'policyHolder.address.addressStrEn', 'IN', '', 'policyHolder.addresses.addressStrEn', '134', 'STRING'),
('ph_addr_building', 'Адрес.строение', 'policyHolder.address.building', 'IN', '', 'policyHolder.addresses.building', '127', 'STRING'),
('ph_addr_city', 'Адрес.город', 'policyHolder.address.city', 'IN', '', 'policyHolder.addresses.city', '124', 'STRING'),
('ph_addr_countryCode', 'Адрес.код страны', 'policyHolder.address.countryCode', 'IN', 'RU', 'policyHolder.addresses.countryCode', '122', 'STRING'),
('ph_addr_ext_id', 'Адрес.внешний ID', 'policyHolder.address.ext_id', 'IN', '', 'policyHolder.addresses.ext_id', '136', 'STRING'),
('ph_addr_fiasId', 'Адрес.код ФИАС', 'policyHolder.address.fiasId', 'IN', '', 'policyHolder.addresses.fiasId', '132', 'STRING'),
('ph_addr_flat', 'Адрес.квартира', 'policyHolder.address.flat', 'IN', '', 'policyHolder.addresses.flat', '128', 'STRING'),
('ph_addr_house', 'Адрес.дом', 'policyHolder.address.house', 'IN', '', 'policyHolder.addresses.house', '126', 'STRING'),
('ph_addr_kladrId', 'Адрес.код КЛАДР', 'policyHolder.address.kladrId', 'IN', '', 'policyHolder.addresses.kladrId', '131', 'STRING'),
('ph_addr_region', 'Адрес.регион', 'policyHolder.address.region', 'IN', '', 'policyHolder.addresses.region', '123', 'STRING'),
('ph_addr_room', 'Адрес.комната', 'policyHolder.address.room', 'IN', '', 'policyHolder.addresses.room', '129', 'STRING'),
('ph_addr_street', 'Адрес.улица', 'policyHolder.address.street', 'IN', '', 'policyHolder.addresses.street', '125', 'STRING'),
('ph_addr_typeCode', 'Адрес.тип адреса', 'policyHolder.address.typeCode', 'IN', 'REGISTRATION', 'policyHolder.addresses.typeCode', '121', 'STRING'),
('ph_addr_zipCode', 'Адрес.индекс', 'policyHolder.address.zipCode', 'IN', '', 'policyHolder.addresses.zipCode', '130', 'STRING'),
('ph_email', 'Страхователь.email', 'policyHolder.email', 'IN', '', 'policyHolder.contacts..email', '91', 'STRING'),
('ph_phone', 'Страхователь.телефон', 'policyHolder.phone.phoneNumber', 'IN', '', 'policyHolder.contacts.phone', '81', 'STRING'),
('ph_doc_countryCode', 'Документ.страна выдачи документа', 'policyHolder.passport.countryCode', 'IN', 'RU', 'policyHolder.identifiers.countryCode', '110', 'STRING'),
('ph_doc_dateIssue', 'Документ.дата выдачи', 'policyHolder.passport.dateIssue', 'IN', '', 'policyHolder.identifiers.dateIssue', '104', 'STRING'),
('ph_doc_divisionCode', 'Документ.код подразделения', 'policyHolder.passport.divisionCode', 'IN', '', 'policyHolder.identifiers.divisionCode', '107', 'STRING'),
('ph_doc_ext_id', 'Документ.внешний ID', 'policyHolder.passport.ext_id', 'IN', '', 'policyHolder.identifiers.ext_id', '109', 'STRING'),
('ph_doc_number', 'Документ.номер документа', 'policyHolder.passport.number', 'IN', '', 'policyHolder.identifiers.number', '103', 'STRING'),
('ph_doc_serial', 'Документ.серия документа', 'policyHolder.passport.serial', 'IN', '', 'policyHolder.identifiers.serial', '102', 'STRING'),
('ph_doc_typeCode', 'Документ.код типа документа', 'policyHolder.passport.typeCode', 'IN', '', 'policyHolder.identifiers.typeCode', '101', 'STRING'),
('ph_doc_validUntil', 'Документ.действительно до', 'policyHolder.passport.validUntil', 'IN', '', 'policyHolder.identifiers.validUntil', '105', 'STRING'),
('ph_doc_whom', 'Документ.кем выдан', 'policyHolder.passport.whom', 'IN', '', 'policyHolder.identifiers.whom', '106', 'STRING'),
('ph_org_bic', 'Страхователь.БИК', 'policyHolder.organization.bic', 'IN', '', 'policyHolder.organization.bic', '60', 'STRING'),
('ph_country', 'Страхователь.код страны регистрации', 'policyHolder.organization.country', 'IN', '', 'policyHolder.organization.country', '51', 'STRING'),
('ph_org_ext_id', 'Страхователь.внешний ID', 'policyHolder.organization.ext_id', 'IN', '', 'policyHolder.organization.ext_id', '64', 'STRING'),
('ph_org_fullName', 'Страхователь.полное наименование юр.лица', 'policyHolder.organization.fullName', 'IN', '', 'policyHolder.organization.fullName', '53', 'STRING'),
('ph_org_fullNameEn', 'Страхователь.полное наименование  юр.лица англ', 'policyHolder.organization.fullNameEn', 'IN', '', 'policyHolder.organization.fullNameEn', '54', 'STRING'),
('ph_org_group', 'Страхователь.Gруппа страхователя ЮЛ', 'policyHolder.organization.group', 'IN', '', 'policyHolder.organization.group', '62', 'STRING'),
('ph_org_inn', 'Страхователь.ИНН юр.лица', 'policyHolder.organization.inn', 'IN', '', 'policyHolder.organization.inn', '52', 'STRING'),
('ph_org_isResident', 'Страхователь.резидент РФ юр.лица', 'policyHolder.organization.isResident', 'IN', 'true', 'policyHolder.organization.isResident', '61', 'STRING'),
('ph_org_kpp', 'Страхователь.КПП', 'policyHolder.organization.kpp', 'IN', '', 'policyHolder.organization.kpp', '57', 'STRING'),
('ph_org_legalForm', 'Страхователь.организационно-правовая форма', 'policyHolder.organization.legalForm', 'IN', '', 'policyHolder.organization.legalForm', '56', 'STRING'),
('ph_org_nciCode', 'Страхователь.НСИ код', 'policyHolder.organization.nciCode', 'IN', '', 'policyHolder.organization.nciCode', '65', 'STRING'),
('ph_org_ogrn', 'Страхователь.ОГРН', 'policyHolder.organization.ogrn', 'IN', '', 'policyHolder.organization.ogrn', '58', 'STRING'),
('ph_org_okpo', 'Страхователь.ОКПО', 'policyHolder.organization.okpo', 'IN', '', 'policyHolder.organization.okpo', '59', 'STRING'),
('ph_org_shortName', 'Страхователь.краткое наименование юр.лица', 'policyHolder.organization.shortName', 'IN', '', 'policyHolder.organization.shortName', '55', 'STRING'),
('ph_age_end', 'Страхователь.возраст на дату окончания договора', '', 'MAGIC', '', 'policyHolder.person.age_end', '1115', 'NUMBER'),
('ph_age_issue', 'Страхователь.возраст на дату выпуска договора', '', 'MAGIC', '', 'policyHolder.person.age_issue', '1115', 'NUMBER'),
('ph_birthDate', 'Страхователь.дата рождения', 'policyHolder.person.birthDate', 'IN', '', 'policyHolder.person.birthDate', '4', 'STRING'),
('ph_birthPlace', 'Страхователь.место рождения', 'policyHolder.person.birthPlace', 'IN', '', 'policyHolder.person.birthPlace', '7', 'STRING'),
('ph_citizenship', 'Страхователь.гражданство', 'policyHolder.person.citizenship', 'IN', 'RU', 'policyHolder.person.citizenship', '8', 'STRING'),
('ph_ext_id', 'Страхователь.внешний ID', 'policyHolder.person.ext_id', 'IN', '', 'policyHolder.person.ext_id', '14', 'STRING'),
('ph_familyState', 'Страхователь.семейное положение', 'policyHolder.person.familyState', 'IN', 'SINGLE', 'policyHolder.person.familyState', '10', 'STRING'),
('ph_firstName', 'Страхователь.имя', 'policyHolder.person.firstName', 'IN', '', 'policyHolder.person.firstName', '1', 'STRING'),
('ph_fullName', 'Страхователь.полное ФИО', 'policyHolder.person.fullName', 'IN', '', 'policyHolder.person.fullName', '5', 'STRING'),
('ph_fullNameEn', 'Страхователь.полное ФИО англ', 'policyHolder.person.fullNameEn', 'IN', '', 'policyHolder.person.fullNameEn', '6', 'STRING'),
('ph_gender', 'Страхователь.пол', 'policyHolder.person.gender', 'IN', '', 'policyHolder.person.gender', '9', 'STRING'),
('ph_isFemale', 'Страхователь.пол.Ж', '', 'MAGIC', '', 'policyHolder.person.isFemale', '1114', 'STRING'),
('ph_isMale', 'Страхователь.пол.М', '', 'MAGIC', '', 'policyHolder.person.isMale', '1113', 'STRING'),
('ph_isPublicOfficial', 'Страхователь.признак ПДЛ', 'policyHolder.person.isPublicOfficial', 'IN', '', 'policyHolder.person.isPublicOfficial', '11', 'STRING'),
('ph_isResident', 'Страхователь.резидент РФ', 'policyHolder.person.isResident', 'IN', 'true', 'policyHolder.person.isResident', '12', 'STRING'),
('ph_lastName', 'Страхователь.фамилия', 'policyHolder.person.lastName', 'IN', '', 'policyHolder.person.lastName', '2', 'STRING'),
('ph_middleName', 'Страхователь.отчество', 'policyHolder.person.middleName', 'IN', '', 'policyHolder.person.middleName', '3', 'STRING'),
('io_propertyTypeCode', 'Имущество.тип имущества код', 'insuredObjects[0].property.propertyType.code', 'IN', '', 'insuredObject.property.propertyType.code', 1001, 'STRING'),
('io_cadastrNr', 'Имущество.кадастровый номер', 'insuredObjects[0].property.cadastrNr', 'IN', '77:07:0018002:2590', 'insuredObject.property.cadastrNr', 1018, 'STRING'),
('io_wallsMaterial', 'Имущество.материал стен', 'insuredObjects[0].property.wallsMaterial', 'IN', 'Каменные, кирпичные', 'insuredObject.property.wallsMaterial', 1019, 'STRING'),
('io_wallsMaterialOther', 'Имущество.материал стен другой', 'insuredObjects[0].property.wallsMaterialOther', 'IN', 'Каменные, кирпичные', 'insuredObject.property.wallsMaterialOther', 1020, 'STRING'),
('io_ceilingMaterial', 'Имущество.материал перекрытий', 'insuredObjects[0].property.ceilingMaterial', 'IN', 'Смешанные', 'insuredObject.property.ceilingMaterial', 1021, 'STRING'),
('io_ceilingMaterialOther', 'Имущество.материал перекрытий другой', 'insuredObjects[0].property.ceilingMaterialOther', 'IN', 'Смешанные', 'insuredObject.property.ceilingMaterialOther', 1022, 'STRING'),
('io_constructionYear', 'Имущество.год постройки', 'insuredObjects[0].property.constructionYear', 'IN', '', 'insuredObject.property.constructionYear', 1023, 'STRING'),
('io_repairYear', 'Имущество.год ремонта', 'insuredObjects[0].property.repairYear', 'IN', '', 'insuredObject.property.repairYear', 1024, 'STRING'),
('io_buildingArea', 'Имущество.площадь здания', 'insuredObjects[0].property.buildingArea', 'IN', '0', 'insuredObject.property.buildingArea', 1025, 'NUMBER'),
('io_landArea', 'Имущество.площадь участка', 'insuredObjects[0].property.landArea', 'IN', '0', 'insuredObject.property.landArea', 1026, 'NUMBER'),
('io_buildingValue', 'Имущество.стоимость здания', 'insuredObjects[0].property.buildingValue', 'IN', '0', 'insuredObject.property.buildingValue', 1027, 'NUMBER'),
('io_wearCoefficient', 'Имущество.коэффициент износа', 'insuredObjects[0].property.wearCoefficient', 'IN', '0', 'insuredObject.property.wearCoefficient', 1028, 'NUMBER'),
('io_numberOfFloors', 'Имущество.количество этажей', 'insuredObjects[0].property.numberOfFloors', 'IN', '0', 'insuredObject.property.numberOfFloors', 1029, 'NUMBER'),
('io_propertyLocation', 'Имущество.расположение имущества', 'insuredObjects[0].property.propertyLocation', 'IN', 'В многоквартирном доме', 'insuredObject.property.propertyLocation', 1030, 'STRING'),
('io_isNewBuilding', 'Имущество.новостройка', 'insuredObjects[0].property.isNewBuilding', 'IN', '', 'insuredObject.property.isNewBuilding', 1031, 'STRING'),
('io_propertyValue', 'Имущество.стоимость имущества', 'insuredObjects[0].property.propertyValue', 'IN', '0', 'insuredObject.property.propertyValue', 1032, 'NUMBER'),
('io_commissioningDate', 'Имущество.дата ввода в эксплуатацию', 'insuredObjects[0].property.commissioningDate', 'IN', '', 'insuredObject.property.commissioningDate', 1033, 'STRING'),

('gross_up_factor', 'gross-up_factor 1/(1-kV)', '', 'MAGIC', '', 'policy.magic.grossUpFactor', 1050, 'NUMBER'),
('pl_commRate', 'Процент кВ по договору', 'commission.appliedCommissionRate', 'IN', '', 'policy.commission.appliedCommissionRate', 1050, 'NUMBER'),

('io_floor', 'Имущество.этаж', 'insuredObjects[0].property.floor', 'IN', '0', 'insuredObject.property.floor', 1034, 'NUMBER');





insert into pt_refdata values
('fns-dul','1','Паспорт гражданина СССР'),
('fns-dul','2','Загранпаспорт гражданина СССР'),
('fns-dul','3','Свидетельство о рождении'),
('fns-dul','4','Удостоверение личности офицера'),
('fns-dul','5','Справка об освобождении из места лишения свободы'),
('fns-dul','6','Паспорт Минморфлота'),
('fns-dul','7','Военный билет'),
('fns-dul','8','Временное удостоверение, выданное взамен военного билета'),
('fns-dul','9','Дипломатический паспорт'),
('fns-dul','10','Паспорт иностранного гражданина'),
('fns-dul','11','Свидетельство о рассмотрении ходатайства о признании лица беженцем на территории РФ по существу'),
('fns-dul','12','Вид на жительство в Российской Федерации'),
('fns-dul','13','Удостоверение беженца'),
('fns-dul','14','Временное удостоверение личности гражданина Российской Федерации'),
('fns-dul','15','Разрешение на временное проживание в Российской Федерации'),
('fns-dul','16','Временное удостоверение личности лица без гражданства в РФ'),
('fns-dul','18','Свидетельство о предоставлении временного убежища на территории Российской Федерации (до 01.01.2013)'),
('fns-dul','19','Свидетельство о предоставлении временного убежища на территории Российской Федерации'),
('fns-dul','21','Паспорт гражданина Российской Федерации'),
('fns-dul','22','Паспорт гражданина РФ, удостоверяющий личность гражданина РФ за пределами территории РФ'),
('fns-dul','23','Свидетельство о рождении, выданное уполномоченным органом иностранного государства'),
('fns-dul','24','Удостоверение личности военнослужащего Российской Федерации'),
('fns-dul','26','Паспорт моряка'),
('fns-dul','27','Военный билет офицера запаса'),
('fns-dul','28','Служебный паспорт гражданина Российской Федерации'),
('fns-dul','60','Документы, подтверждающие факт регистрации по месту жительства (пребывания)'),
('fns-dul','61','Свидетельство о регистрации по месту жительства'),
('fns-dul','62','Вид на жительство иностранного гражданина'),
('fns-dul','63','Свидетельство о регистрации по месту пребывания'),
('fns-dul','81','Свидетельство о смерти'),
('fns-dul','91','Иные документы');

insert into pt_refdata values
('oksm2','AF','АФГАНИСТАН'),
('oksm2','AL','АЛБАНИЯ'),
('oksm2','AQ','АНТАРКТИДА'),
('oksm2','DZ','АЛЖИР'),
('oksm2','AS','АМЕРИКАНСКОЕ САМОА'),
('oksm2','AD','АНДОРРА'),
('oksm2','AO','АНГОЛА'),
('oksm2','AG','АНТИГУА И БАРБУДА'),
('oksm2','AZ','АЗЕРБАЙДЖАН'),
('oksm2','AR','АРГЕНТИНА'),
('oksm2','AU','АВСТРАЛИЯ'),
('oksm2','AT','АВСТРИЯ'),
('oksm2','BS','БАГАМЫ'),
('oksm2','BH','БАХРЕЙН'),
('oksm2','BD','БАНГЛАДЕШ'),
('oksm2','AM','АРМЕНИЯ'),
('oksm2','BB','БАРБАДОС'),
('oksm2','BE','БЕЛЬГИЯ'),
('oksm2','BM','БЕРМУДЫ'),
('oksm2','BT','БУТАН'),
('oksm2','BO','БОЛИВИЯ, МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО'),
('oksm2','BA','БОСНИЯ И ГЕРЦЕГОВИНА'),
('oksm2','BW','БОТСВАНА'),
('oksm2','BV','ОСТРОВ БУВЕ'),
('oksm2','BR','БРАЗИЛИЯ'),
('oksm2','BZ','БЕЛИЗ'),
('oksm2','IO','БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ'),
('oksm2','SB','СОЛОМОНОВЫ ОСТРОВА'),
('oksm2','VG','ВИРГИНСКИЕ ОСТРОВА (БРИТАНСКИЕ)'),
('oksm2','BN','БРУНЕЙ-ДАРУССАЛАМ'),
('oksm2','BG','БОЛГАРИЯ'),
('oksm2','MM','МЬЯНМА'),
('oksm2','BI','БУРУНДИ'),
('oksm2','BY','БЕЛАРУСЬ'),
('oksm2','KH','КАМБОДЖА'),
('oksm2','CM','КАМЕРУН'),
('oksm2','CA','КАНАДА'),
('oksm2','CV','КАБО-ВЕРДЕ'),
('oksm2','KY','ОСТРОВА КАЙМАН'),
('oksm2','CF','ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА'),
('oksm2','LK','ШРИ-ЛАНКА'),
('oksm2','TD','ЧАД'),
('oksm2','CL','ЧИЛИ'),
('oksm2','CN','КИТАЙ'),
('oksm2','TW','ТАЙВАНЬ (КИТАЙ)'),
('oksm2','CX','ОСТРОВ РОЖДЕСТВА'),
('oksm2','CC','КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА'),
('oksm2','CO','КОЛУМБИЯ'),
('oksm2','KM','КОМОРЫ'),
('oksm2','YT','МАЙОТТА'),
('oksm2','CG','КОНГО'),
('oksm2','CD','КОНГО, ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА'),
('oksm2','CK','ОСТРОВА КУКА'),
('oksm2','CR','КОСТА-РИКА'),
('oksm2','HR','ХОРВАТИЯ'),
('oksm2','CU','КУБА'),
('oksm2','CY','КИПР'),
('oksm2','CZ','ЧЕХИЯ'),
('oksm2','BJ','БЕНИН'),
('oksm2','DK','ДАНИЯ'),
('oksm2','DM','ДОМИНИКА'),
('oksm2','DO','ДОМИНИКАНСКАЯ РЕСПУБЛИКА'),
('oksm2','EC','ЭКВАДОР'),
('oksm2','SV','ЭЛЬ-САЛЬВАДОР'),
('oksm2','GQ','ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ'),
('oksm2','ET','ЭФИОПИЯ'),
('oksm2','ER','ЭРИТРЕЯ'),
('oksm2','EE','ЭСТОНИЯ'),
('oksm2','FO','ФАРЕРСКИЕ ОСТРОВА'),
('oksm2','FK','ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)'),
('oksm2','GS','ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА'),
('oksm2','FJ','ФИДЖИ'),
('oksm2','FI','ФИНЛЯНДИЯ'),
('oksm2','AX','АЛАНДСКИЕ ОСТРОВА'),
('oksm2','FR','ФРАНЦИЯ'),
('oksm2','GF','ФРАНЦУЗСКАЯ ГВИАНА'),
('oksm2','PF','ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ'),
('oksm2','TF','ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ'),
('oksm2','DJ','ДЖИБУТИ'),
('oksm2','GA','ГАБОН'),
('oksm2','GE','ГРУЗИЯ'),
('oksm2','GM','ГАМБИЯ'),
('oksm2','PS','ПАЛЕСТИНА, ГОСУДАРСТВО'),
('oksm2','DE','ГЕРМАНИЯ'),
('oksm2','GH','ГАНА'),
('oksm2','GI','ГИБРАЛТАР'),
('oksm2','KI','КИРИБАТИ'),
('oksm2','GR','ГРЕЦИЯ'),
('oksm2','GL','ГРЕНЛАНДИЯ'),
('oksm2','GD','ГРЕНАДА'),
('oksm2','GP','ГВАДЕЛУПА'),
('oksm2','GU','ГУАМ'),
('oksm2','GT','ГВАТЕМАЛА'),
('oksm2','GN','ГВИНЕЯ'),
('oksm2','GY','ГАЙАНА'),
('oksm2','HT','ГАИТИ'),
('oksm2','HM','ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД'),
('oksm2','VA','ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО - ГОРОД ВАТИКАН)'),
('oksm2','HN','ГОНДУРАС'),
('oksm2','HK','ГОНКОНГ'),
('oksm2','HU','ВЕНГРИЯ'),
('oksm2','IS','ИСЛАНДИЯ'),
('oksm2','IN','ИНДИЯ'),
('oksm2','ID','ИНДОНЕЗИЯ'),
('oksm2','IR','ИРАН (ИСЛАМСКАЯ РЕСПУБЛИКА)'),
('oksm2','IQ','ИРАК'),
('oksm2','IE','ИРЛАНДИЯ'),
('oksm2','IL','ИЗРАИЛЬ'),
('oksm2','IT','ИТАЛИЯ'),
('oksm2','CI','КОТ ДИВУАР'),
('oksm2','JM','ЯМАЙКА'),
('oksm2','JP','ЯПОНИЯ'),
('oksm2','KZ','КАЗАХСТАН'),
('oksm2','JO','ИОРДАНИЯ'),
('oksm2','KE','КЕНИЯ'),
('oksm2','KP','КОРЕЯ, НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА'),
('oksm2','KR','КОРЕЯ, РЕСПУБЛИКА'),
('oksm2','KW','КУВЕЙТ'),
('oksm2','KG','КИРГИЗИЯ'),
('oksm2','LA','ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА'),
('oksm2','LB','ЛИВАН'),
('oksm2','LS','ЛЕСОТО'),
('oksm2','LV','ЛАТВИЯ'),
('oksm2','LR','ЛИБЕРИЯ'),
('oksm2','LY','ЛИВИЯ'),
('oksm2','LI','ЛИХТЕНШТЕЙН'),
('oksm2','LT','ЛИТВА'),
('oksm2','LU','ЛЮКСЕМБУРГ'),
('oksm2','MO','МАКАО'),
('oksm2','MG','МАДАГАСКАР'),
('oksm2','MW','МАЛАВИ'),
('oksm2','MY','МАЛАЙЗИЯ'),
('oksm2','MV','МАЛЬДИВЫ'),
('oksm2','ML','МАЛИ'),
('oksm2','MT','МАЛЬТА'),
('oksm2','MQ','МАРТИНИКА'),
('oksm2','MR','МАВРИТАНИЯ'),
('oksm2','MU','МАВРИКИЙ'),
('oksm2','MX','МЕКСИКА'),
('oksm2','MC','МОНАКО'),
('oksm2','MN','МОНГОЛИЯ'),
('oksm2','MD','МОЛДОВА, РЕСПУБЛИКА'),
('oksm2','ME','ЧЕРНОГОРИЯ'),
('oksm2','MS','МОНТСЕРРАТ'),
('oksm2','MA','МАРОККО'),
('oksm2','MZ','МОЗАМБИК'),
('oksm2','OM','ОМАН'),
('oksm2','NA','НАМИБИЯ'),
('oksm2','NR','НАУРУ'),
('oksm2','NP','НЕПАЛ'),
('oksm2','NL','НИДЕРЛАНДЫ, КОРОЛЕВСТВО'),
('oksm2','CW','КЮРАСАО'),
('oksm2','AW','АРУБА'),
('oksm2','SX','СЕН-МАРТЕН (нидерландская часть)'),
('oksm2','BQ','БОНЭЙР, СИНТ-ЭСТАТИУС И САБА'),
('oksm2','NC','НОВАЯ КАЛЕДОНИЯ'),
('oksm2','VU','ВАНУАТУ'),
('oksm2','NZ','НОВАЯ ЗЕЛАНДИЯ'),
('oksm2','NI','НИКАРАГУА'),
('oksm2','NE','НИГЕР'),
('oksm2','NG','НИГЕРИЯ'),
('oksm2','NU','НИУЭ'),
('oksm2','NF','ОСТРОВ НОРФОЛК'),
('oksm2','NO','НОРВЕГИЯ'),
('oksm2','MP','СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА'),
('oksm2','UM','МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ'),
('oksm2','FM','МИКРОНЕЗИЯ, ФЕДЕРАТИВНЫЕ ШТАТЫ'),
('oksm2','MH','МАРШАЛЛОВЫ ОСТРОВА'),
('oksm2','PW','ПАЛАУ'),
('oksm2','PK','ПАКИСТАН'),
('oksm2','PA','ПАНАМА'),
('oksm2','PG','ПАПУА-НОВАЯ ГВИНЕЯ'),
('oksm2','PY','ПАРАГВАЙ'),
('oksm2','PE','ПЕРУ'),
('oksm2','PH','ФИЛИППИНЫ'),
('oksm2','PN','ПИТКЕРН'),
('oksm2','PL','ПОЛЬША'),
('oksm2','PT','ПОРТУГАЛИЯ'),
('oksm2','GW','ГВИНЕЯ-БИСАУ'),
('oksm2','TL','ТИМОР-ЛЕСТЕ'),
('oksm2','PR','ПУЭРТО-РИКО'),
('oksm2','QA','КАТАР'),
('oksm2','RE','РЕЮНЬОН'),
('oksm2','RO','РУМЫНИЯ'),
('oksm2','RU','РОССИЯ'),
('oksm2','RW','РУАНДА'),
('oksm2','BL','СЕН-БАРТЕЛЕМИ'),
('oksm2','SH','СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ'),
('oksm2','KN','СЕНТ-КИТС И НЕВИС'),
('oksm2','AI','АНГИЛЬЯ'),
('oksm2','LC','СЕНТ-ЛЮСИЯ'),
('oksm2','MF','СЕН-МАРТЕН (французская часть)'),
('oksm2','PM','СЕН-ПЬЕР И МИКЕЛОН'),
('oksm2','VC','СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ'),
('oksm2','SM','САН-МАРИНО'),
('oksm2','ST','САН-ТОМЕ И ПРИНСИПИ'),
('oksm2','SA','САУДОВСКАЯ АРАВИЯ'),
('oksm2','SN','СЕНЕГАЛ'),
('oksm2','RS','СЕРБИЯ'),
('oksm2','SC','СЕЙШЕЛЫ'),
('oksm2','SL','СЬЕРРА-ЛЕОНЕ'),
('oksm2','SG','СИНГАПУР'),
('oksm2','SK','СЛОВАКИЯ'),
('oksm2','VN','ВЬЕТНАМ'),
('oksm2','SI','СЛОВЕНИЯ'),
('oksm2','SO','СОМАЛИ'),
('oksm2','ZA','ЮЖНАЯ АФРИКА'),
('oksm2','ZW','ЗИМБАБВЕ'),
('oksm2','ES','ИСПАНИЯ'),
('oksm2','SS','ЮЖНЫЙ СУДАН'),
('oksm2','SD','СУДАН'),
('oksm2','EH','ЗАПАДНАЯ САХАРА'),
('oksm2','SR','СУРИНАМ'),
('oksm2','SJ','ШПИЦБЕРГЕН И ЯН МАЙЕН'),
('oksm2','SZ','ЭСВАТИНИ'),
('oksm2','SE','ШВЕЦИЯ'),
('oksm2','CH','ШВЕЙЦАРИЯ'),
('oksm2','SY','СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА'),
('oksm2','TJ','ТАДЖИКИСТАН'),
('oksm2','TH','ТАИЛАНД'),
('oksm2','TG','ТОГО'),
('oksm2','TK','ТОКЕЛАУ'),
('oksm2','TO','ТОНГА'),
('oksm2','TT','ТРИНИДАД И ТОБАГО'),
('oksm2','AE','ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ'),
('oksm2','TN','ТУНИС'),
('oksm2','TR','ТУРЦИЯ'),
('oksm2','TM','ТУРКМЕНИСТАН'),
('oksm2','TC','ОСТРОВА ТЕРКС И КАЙКОС'),
('oksm2','TV','ТУВАЛУ'),
('oksm2','UG','УГАНДА'),
('oksm2','UA','УКРАИНА'),
('oksm2','MK','СЕВЕРНАЯ МАКЕДОНИЯ'),
('oksm2','EG','ЕГИПЕТ'),
('oksm2','GB','СОЕДИНЕННОЕ КОРОЛЕВСТВО ВЕЛИКОБРИТАНИИ И СЕВЕРНОЙ ИРЛАНДИИ'),
('oksm2','GG','ГЕРНСИ'),
('oksm2','JE','ДЖЕРСИ'),
('oksm2','IM','ОСТРОВ МЭН'),
('oksm2','TZ','ТАНЗАНИЯ, ОБЪЕДИНЕННАЯ РЕСПУБЛИКА'),
('oksm2','US','СОЕДИНЕННЫЕ ШТАТЫ'),
('oksm2','VI','ВИРГИНСКИЕ ОСТРОВА (США)'),
('oksm2','BF','БУРКИНА-ФАСО'),
('oksm2','UY','УРУГВАЙ'),
('oksm2','UZ','УЗБЕКИСТАН'),
('oksm2','VE','ВЕНЕСУЭЛА, БОЛИВАРИАНСКАЯ РЕСПУБЛИКА'),
('oksm2','WF','УОЛЛИС И ФУТУНА'),
('oksm2','WS','САМОА'),
('oksm2','YE','ЙЕМЕН'),
('oksm2','ZM','ЗАМБИЯ'),
('oksm2','AB','АБХАЗИЯ'),
('oksm2','OS','ЮЖНАЯ ОСЕТИЯ'),
('oksm2','DN','ДНР'),
('oksm2','LN','ЛНР');
