SET session_replication_role = 'replica';

INSERT INTO mt_attribute_def VALUES (1216, NULL, 1, 'INSURANCE_CONTRACT', 'policy', 'Договор страхования', '*', 1, 'OBJECT', 'SINGLE', 'OBJECT', '', '*', NULL, 'policy', 'Договор страхования', false);
INSERT INTO mt_attribute_def VALUES (1435, 1216, 1, 'INSURANCE_CONTRACT', 'pl_currencyCode', 'Валюта договора', 'currencyCode', 0, 'IN', 'SINGLE', 'STRING', '', 'currencyCode', NULL, 'pl_currencyCode', 'Валюта договора', false);
INSERT INTO mt_attribute_def VALUES (1519, 1241, 1, 'INSURANCE_CONTRACT', 'io_departureAirportICAO', 'Аэропорт вылета ICAO"', 'insuredObjects[0].travelSegments[*].departureAirportICAO', 203, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].departureAirportICAO', NULL, 'departureAirportICAO', 'Аэропорт вылета ICAO"', false);
INSERT INTO mt_attribute_def VALUES (1520, 1241, 1, 'INSURANCE_CONTRACT', 'io_arrivalAirportIATA', 'Аэропорт прилета IATA', 'insuredObjects[0].travelSegments[*].arrivalAirportIATA', 204, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].arrivalAirportIATA', NULL, 'arrivalAirportIATA', 'Аэропорт прилета IATA', false);
INSERT INTO mt_attribute_def VALUES (1521, 1241, 1, 'INSURANCE_CONTRACT', 'io_arrivalAirportICAO', 'Аэропорт прилета ICAO', 'insuredObjects[0].travelSegments[*].arrivalAirportICAO', 205, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].arrivalAirportICAO', NULL, 'arrivalAirportICAO', 'Аэропорт прилета ICAO', false);
INSERT INTO mt_attribute_def VALUES (1523, 1241, 1, 'INSURANCE_CONTRACT', 'io_travelRoutes', 'таблица вылет-прилет', '*', 206, 'MAGIC', 'SINGLE', 'STRING', NULL, NULL, NULL, 'travelRoutes', 'таблица вылет-прилет', false);
INSERT INTO mt_attribute_def VALUES (1524, 1241, 1, 'INSURANCE_CONTRACT', 'io_travelTimetable', 'таблица - время вылета - прилета', '*', 207, 'MAGIC', 'SINGLE', 'STRING', NULL, NULL, NULL, 'travelTimetable', 'таблица - время вылета - прилета', false);
INSERT INTO mt_attribute_def VALUES (1517, 1241, 1, 'INSURANCE_CONTRACT', 'io_flightNr', 'Номер рейса', 'insuredObjects[0].travelSegments[*].flightNr', 201, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].flightNr', NULL, 'flightNr', 'Номер рейса', false);
INSERT INTO mt_attribute_def VALUES (1217, 1216, 1, 'INSURANCE_CONTRACT', 'gross_up_factor', 'Gross_up_factor 1/(1-kv)', 'null', 138, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'gross_up_factor', 'Gross_up_factor 1/(1-kv)', false);
INSERT INTO mt_attribute_def VALUES (1220, 1216, 1, 'INSURANCE_CONTRACT', 'pl_endDate', 'Дата окончания договора', 'endDate', 29, 'IN', 'SINGLE', 'STRING', NULL, 'endDate', NULL, 'endDate', 'Дата окончания договора', false);
INSERT INTO mt_attribute_def VALUES (1221, 1216, 1, 'INSURANCE_CONTRACT', 'pl_issueDate', 'Дата выпуска договора', 'issueDate', 10, 'IN', 'SINGLE', 'STRING', NULL, 'issueDate', NULL, 'issueDate', 'Дата выпуска договора', false);
INSERT INTO mt_attribute_def VALUES (1224, 1216, 1, 'INSURANCE_CONTRACT', 'pl_productCode', 'Код продукта', 'productCode', 1, 'IN', 'SINGLE', 'STRING', NULL, 'productCode', NULL, 'productCode', 'Код продукта', false);
INSERT INTO mt_attribute_def VALUES (1225, 1216, 1, 'INSURANCE_CONTRACT', 'pl_productName', 'Название продукта', 'productName', 2, 'VAR', 'SINGLE', 'STRING', '', 'productName', NULL, 'pl_productName', 'Название продукта', false);
INSERT INTO mt_attribute_def VALUES (1226, 1216, 1, 'INSURANCE_CONTRACT', 'pl_startDate', 'Дата начала действия договора', 'startDate', 23, 'IN', 'SINGLE', 'STRING', NULL, 'startDate', NULL, 'startDate', 'Дата начала действия договора', false);
INSERT INTO mt_attribute_def VALUES (1227, 1216, 1, 'INSURANCE_CONTRACT', 'pl_TermDays', 'Срок полиса в днях', 'null', 144, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'TermDays', 'Срок полиса в днях', false);
INSERT INTO mt_attribute_def VALUES (1228, 1216, 1, 'INSURANCE_CONTRACT', 'pl_TermMonths', 'Срок полиса в месяцах', 'null', 143, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'TermMonths', 'Срок полиса в месяцах', false);
INSERT INTO mt_attribute_def VALUES (1229, 1216, 1, 'INSURANCE_CONTRACT', 'policyHolder', 'Страхователь', 'policyHolder', 300, 'OBJECT', 'SINGLE', 'OBJECT', '', 'policyHolder', NULL, 'policyHolder', 'Страхователь', false);
INSERT INTO mt_attribute_def VALUES (1230, 1216, 1, 'INSURANCE_CONTRACT', 'сommission', 'Агентская комиссия', 'сommission', 10, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'сommission', NULL, 'сommission', 'Агентская комиссия', false);
INSERT INTO mt_attribute_def VALUES (1231, 1218, 1, 'INSURANCE_CONTRACT', 'io_addresses', 'Адрес', 'insuredObjects[0].addresses[?(@.isPrimary)]', 24, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObjects.addresses', NULL, 'addresses', 'Адрес', false);
INSERT INTO mt_attribute_def VALUES (1232, 1218, 1, 'INSURANCE_CONTRACT', 'io_contacts', 'Контакты', 'insuredObjects[0].contacts', 21, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObjects.contacts', NULL, 'contacts', 'Контакты', false);
INSERT INTO mt_attribute_def VALUES (1233, 1218, 1, 'INSURANCE_CONTRACT', 'io_device', 'Электронное устройство', 'insuredObjects[0].device', 25, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObjects.device', NULL, 'device', 'Электронное устройство', false);
INSERT INTO mt_attribute_def VALUES (1234, 1218, 1, 'INSURANCE_CONTRACT', 'io_identifiers', 'Документ', 'insuredObjects[0].identifiers[?(@.isPrimary)]', 23, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObjects.identifiers', NULL, 'identifiers', 'Документ', false);
INSERT INTO mt_attribute_def VALUES (1235, 1218, 1, 'INSURANCE_CONTRACT', 'io_organization', 'Юр.лицо', 'insuredObjects[0].organization', 22, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObjects.organization', NULL, 'organization', 'Юр.лицо', false);
INSERT INTO mt_attribute_def VALUES (1236, 1218, 1, 'INSURANCE_CONTRACT', 'io_packageCode', 'Код пакета', 'insuredObjects[0].packageCode', 24, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.packageCode', NULL, 'packageCode', 'Код пакета', false);
INSERT INTO mt_attribute_def VALUES (1237, 1218, 1, 'INSURANCE_CONTRACT', 'io_person', 'Физ.лицо', 'insuredObjects[0].person', 20, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObjects.person', NULL, 'person', 'Физ.лицо', false);
INSERT INTO mt_attribute_def VALUES (1238, 1218, 1, 'INSURANCE_CONTRACT', 'io_property', 'Недвижимость', 'insuredObjects[0].property', 26, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObjects.property', NULL, 'property', 'Недвижимость', false);
INSERT INTO mt_attribute_def VALUES (1239, 1218, 1, 'INSURANCE_CONTRACT', 'io_riskFactors', 'Доп. риски', 'insuredObjects[0].riskFactors', 28, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObjects.riskFactors', NULL, 'riskFactors', 'Доп. риски', false);
INSERT INTO mt_attribute_def VALUES (1241, 1218, 1, 'INSURANCE_CONTRACT', 'io_travelSegments', 'Сегмент авиаперевозки', 'insuredObjects[0].travelSegments', 27, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insuredObjects.travelSegments', NULL, 'travelSegments', 'Сегмент авиаперевозки', false);

INSERT INTO mt_attribute_def VALUES (1246, 1229, 1, 'INSURANCE_CONTRACT', 'ph_addresses', 'Адрес', 'policyHolder.addresses[?(@.isPrimary)]', 14, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'policyHolder.addresses', NULL, 'addresses', 'Адрес', false);
INSERT INTO mt_attribute_def VALUES (1247, 1229, 1, 'INSURANCE_CONTRACT', 'ph_contacts', 'Контакты', 'policyHolder.contacts', 11, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'policyHolder.contacts', NULL, 'contacts', 'Контакты', false);
INSERT INTO mt_attribute_def VALUES (1248, 1229, 1, 'INSURANCE_CONTRACT', 'ph_identifiers', 'Документ', 'policyHolder.identifiers[?(@.isPrimary)]', 13, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'policyHolder.identifiers', NULL, 'identifiers', 'Документ', false);
INSERT INTO mt_attribute_def VALUES (1249, 1229, 1, 'INSURANCE_CONTRACT', 'ph_organization', 'Юр.лицо', 'policyHolder.organization', 12, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'policyHolder.organization', NULL, 'organization', 'Юр.лицо', false);
INSERT INTO mt_attribute_def VALUES (1250, 1229, 1, 'INSURANCE_CONTRACT', 'ph_person', 'Физ.лицо', 'policyHolder.person', 10, 'OBJECT', 'SINGLE', 'OBJECT', '', 'policyHolder.person', NULL, 'ph_person', 'Физ.лицо', false);
INSERT INTO mt_attribute_def VALUES (1223, 1216, 1, 'INSURANCE_CONTRACT', 'pl_premium', 'Премия по договору', 'premium', 32, 'VAR', 'SINGLE', 'STRING', '', 'premium', NULL, 'pl_premium', 'Премия по договору', false);
INSERT INTO mt_attribute_def VALUES (1222, 1216, 1, 'INSURANCE_CONTRACT', 'pl_policyNumber', 'Номер договора', 'policyNumber', 5, 'VAR', 'SINGLE', 'STRING', '', 'policyNumber', NULL, 'pl_policyNumber', 'Номер договора', false);
INSERT INTO mt_attribute_def VALUES (1251, 1230, 1, 'INSURANCE_CONTRACT', 'pl_commission', 'Комиссия по договору', 'commission.commission', 2, 'VAR', 'SINGLE', 'NUMBER', NULL, 'commission.commission', NULL, 'commission', 'Комиссия по договору', true);
INSERT INTO mt_attribute_def VALUES (1253, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_addressStr', 'Io.адрес.адресная строка', 'insuredObjects[0].addresses[?(@.isPrimary)].addressStr', 97, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.addressStr', NULL, 'addressStr', 'Адресная строка', false);
INSERT INTO mt_attribute_def VALUES (1254, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_addressStrEn', 'Io.адрес.адресная строка англ', 'insuredObjects[0].addresses[?(@.isPrimary)].addressStrEn', 100, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.addressStrEn', NULL, 'addressStrEn', 'Адресная строка англ', false);
INSERT INTO mt_attribute_def VALUES (1255, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_building', 'Io.адрес.строение', 'insuredObjects[0].addresses[?(@.isPrimary)].building', 85, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.building', NULL, 'building', 'Строение', false);
INSERT INTO mt_attribute_def VALUES (1256, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_city', 'Io.адрес.город', 'insuredObjects[0].addresses[?(@.isPrimary)].city', 80, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.city', NULL, 'city', 'Город', false);
INSERT INTO mt_attribute_def VALUES (1257, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_countryCode', 'Io.адрес.код страны', 'insuredObjects[0].addresses[?(@.isPrimary)].countryCode', 75, 'IN', 'SINGLE', 'STRING', 'RU', 'insuredObjects.addresses.countryCode', 'country2', 'countryCode', 'Код страны', false);
INSERT INTO mt_attribute_def VALUES (1258, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_ext_id', 'Io.адрес.внешний id', 'insuredObjects[0].addresses[?(@.isPrimary)].ext_id', 102, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.ext_id', NULL, 'ext_id', 'Внешний id', false);
INSERT INTO mt_attribute_def VALUES (1259, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_fiasId', 'Io.адрес.код фиас', 'insuredObjects[0].addresses[?(@.isPrimary)].fiasId', 96, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.fiasId', NULL, 'fiasId', 'Код фиас', false);
INSERT INTO mt_attribute_def VALUES (1260, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_flat', 'Io.адрес.квартира', 'insuredObjects[0].addresses[?(@.isPrimary)].flat', 88, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.flat', NULL, 'flat', 'Квартира', false);
INSERT INTO mt_attribute_def VALUES (1261, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_house', 'Io.адрес.дом', 'insuredObjects[0].addresses[?(@.isPrimary)].house', 84, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.house', NULL, 'house', 'Дом', false);
INSERT INTO mt_attribute_def VALUES (1262, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_kladrId', 'Io.адрес.код кладр', 'insuredObjects[0].addresses[?(@.isPrimary)].kladrId', 94, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.kladrId', NULL, 'kladrId', 'Код кладр', false);
INSERT INTO mt_attribute_def VALUES (1263, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_region', 'Io.адрес.регион', 'insuredObjects[0].addresses[?(@.isPrimary)].region', 78, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.region', NULL, 'region', 'Регион', false);
INSERT INTO mt_attribute_def VALUES (1264, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_room', 'Io.адрес.комната', 'insuredObjects[0].addresses[?(@.isPrimary)].room', 90, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.room', NULL, 'room', 'Комната', false);
INSERT INTO mt_attribute_def VALUES (1265, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_street', 'Io.адрес.улица', 'insuredObjects[0].addresses[?(@.isPrimary)].street', 82, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.street', NULL, 'street', 'Улица', false);
INSERT INTO mt_attribute_def VALUES (1266, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_typeCode', 'Io.адрес.тип адреса', 'insuredObjects[0].addresses[?(@.isPrimary)].typeCode', 73, 'IN', 'SINGLE', 'STRING', 'REGISTRATION', 'insuredObjects.addresses.typeCode', 'addressType', 'typeCode', 'Тип адреса', false);
INSERT INTO mt_attribute_def VALUES (1267, 1231, 1, 'INSURANCE_CONTRACT', 'io_addr_zipCode', 'Io.адрес.индекс', 'insuredObjects[0].addresses[?(@.isPrimary)].zipCode', 91, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.addresses.zipCode', NULL, 'zipCode', 'Индекс', false);
INSERT INTO mt_attribute_def VALUES (1268, 1232, 1, 'INSURANCE_CONTRACT', 'io_email', 'Застрахованный.email', 'insuredObjects[0].contacts.email', 51, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.contacts.email', NULL, 'email', 'Email', false);
INSERT INTO mt_attribute_def VALUES (1269, 1232, 1, 'INSURANCE_CONTRACT', 'io_phone', 'Застрахованный.телефон', 'insuredObjects[0].contacts.phone', 50, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.contacts.phone', NULL, 'phone', 'Телефон', false);
INSERT INTO mt_attribute_def VALUES (1270, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_countryCode', 'Застрахованное ус-во. код страны', 'insuredObjects[0].device.countryCode', 118, 'IN', 'SINGLE', 'STRING', 'RU', 'insuredObjects.device.countryCode', 'country2', 'device_countryCode', 'Код страны', false);
INSERT INTO mt_attribute_def VALUES (1271, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_devicePrice', 'Застрахованное ус-во. цена', 'insuredObjects[0].device.devicePrice', 119, 'IN', 'SINGLE', 'NUMBER', '10000', 'insuredObjects.device.devicePrice', NULL, 'device_devicePrice', 'Цена', false);
INSERT INTO mt_attribute_def VALUES (1272, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_imei', 'Застрахованное ус-во. imei', 'insuredObjects[0].device.imei', 115, 'IN', 'SINGLE', 'STRING', '1234567890', 'insuredObjects.device.imei', NULL, 'device_imei', 'Imei', false);
INSERT INTO mt_attribute_def VALUES (1273, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_licenseKey', 'Застрахованное ус-во. ключ лицензии', 'insuredObjects[0].device.licenseKey', 114, 'IN', 'SINGLE', 'STRING', '1234567890', 'insuredObjects.device.licenseKey', NULL, 'device_licenseKey', 'Ключ лицензии', false);
INSERT INTO mt_attribute_def VALUES (1274, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_model', 'Застрахованное ус-во. модель', 'insuredObjects[0].device.model', 110, 'IN', 'SINGLE', 'STRING', 'Galaxy S21', 'insuredObjects.device.model', NULL, 'device_model', 'Модель', false);
INSERT INTO mt_attribute_def VALUES (1275, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_name', 'Застрахованное ус-во. название', 'insuredObjects[0].device.deviceName', 103, 'IN', 'SINGLE', 'STRING', 'Телефон', 'insuredObjects.device.deviceName', NULL, 'device_name', 'Название', false);
INSERT INTO mt_attribute_def VALUES (1276, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_osName', 'Застрахованное ус-во. название ос', 'insuredObjects[0].device.osName', 117, 'IN', 'SINGLE', 'STRING', 'Android', 'insuredObjects.device.osName', NULL, 'device_osName', 'Название ос', false);
INSERT INTO mt_attribute_def VALUES (1277, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_osVersion', 'Застрахованное ус-во. версия ос', 'insuredObjects[0].device.osVersion', 116, 'IN', 'SINGLE', 'STRING', '10', 'insuredObjects.device.osVersion', NULL, 'device_osVersion', 'Версия ос', false);
INSERT INTO mt_attribute_def VALUES (1278, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_serialNr', 'Застрахованное ус-во. серийный номер', 'insuredObjects[0].device.serialNr', 112, 'IN', 'SINGLE', 'STRING', '1234567890', 'insuredObjects.device.serialNr', NULL, 'device_serialNr', 'Серийный номер', false);
INSERT INTO mt_attribute_def VALUES (1279, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_tradeMark', 'Застрахованное ус-во. торговая марка', 'insuredObjects[0].device.tradeMark', 108, 'IN', 'SINGLE', 'STRING', 'Samsung', 'insuredObjects.device.tradeMark', NULL, 'device_tradeMark', 'Торговая марка', false);
INSERT INTO mt_attribute_def VALUES (1280, 1233, 1, 'INSURANCE_CONTRACT', 'io_device_typeCode', 'Застрахованное ус-во. код типа', 'insuredObjects[0].device.deviceTypeCode', 106, 'IN', 'SINGLE', 'STRING', 'PHONE', 'insuredObjects.device.deviceTypeCode', 'deviceType', 'device_typeCode', 'Код типа', false);
INSERT INTO mt_attribute_def VALUES (1281, 1234, 1, 'INSURANCE_CONTRACT', 'io_doc_countryCode', 'io.документ.страна выдачи документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].countryCode', 72, 'IN', 'SINGLE', 'STRING', 'RU', 'insuredObjects.identifiers.countryCode', 'country2', 'countryCode', 'Страна выдачи документа', false);
INSERT INTO mt_attribute_def VALUES (1282, 1234, 1, 'INSURANCE_CONTRACT', 'io_doc_dateIssue', 'io.документ.дата выдачи', 'insuredObjects[0].identifiers[?(@.isPrimary)].dateIssue', 61, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.dateIssue', NULL, 'dateIssue', 'Дата выдачи', false);
INSERT INTO mt_attribute_def VALUES (1283, 1234, 1, 'INSURANCE_CONTRACT', 'io_doc_divisionCode', 'io.документ.код подразделения', 'insuredObjects[0].identifiers[?(@.isPrimary)].divisionCode', 67, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.divisionCode', NULL, 'divisionCode', 'Код подразделения', false);
INSERT INTO mt_attribute_def VALUES (1284, 1234, 1, 'INSURANCE_CONTRACT', 'io_doc_ext_id', 'io.документ.внешний id', 'insuredObjects[0].identifiers[?(@.isPrimary)].ext_id', 70, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.ext_id', NULL, 'ext_id', 'Внешний id', false);
INSERT INTO mt_attribute_def VALUES (1285, 1234, 1, 'INSURANCE_CONTRACT', 'io_doc_number', 'io.документ.номер документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].number', 60, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.number', NULL, 'number', 'Номер документа', false);
INSERT INTO mt_attribute_def VALUES (1286, 1234, 1, 'INSURANCE_CONTRACT', 'io_doc_serial', 'io.документ.серия документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].serial', 57, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.serial', NULL, 'serial', 'Серия документа', false);
INSERT INTO mt_attribute_def VALUES (1287, 1234, 1, 'INSURANCE_CONTRACT', 'io_doc_typeCode', 'io.документ.код типа документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].typeCode', 55, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.typeCode', 'identifierType', 'typeCode', 'Код типа документа', false);
INSERT INTO mt_attribute_def VALUES (1288, 1234, 1, 'INSURANCE_CONTRACT', 'io_doc_validUntil', 'io.документ.действительно до', 'insuredObjects[0].identifiers[?(@.isPrimary)].validUntil', 64, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.validUntil', NULL, 'validUntil', 'Действительно до', false);
INSERT INTO mt_attribute_def VALUES (1289, 1234, 1, 'INSURANCE_CONTRACT', 'io_doc_whom', 'io.документ.кем выдан', 'insuredObjects[0].identifiers[?(@.isPrimary)].whom', 65, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.identifiers.whom', NULL, 'whom', 'Кем выдан', false);
INSERT INTO mt_attribute_def VALUES (1290, 1237, 1, 'INSURANCE_CONTRACT', 'io_age_end', 'Возраст застрахованного на дату окончания полиса', 'null', 140, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_end', 'Возраст застрахованного на дату окончания полиса', false);
INSERT INTO mt_attribute_def VALUES (1291, 1237, 1, 'INSURANCE_CONTRACT', 'io_age_issue', 'Возраст застрахованного на дату выпуска полиса', 'null', 139, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_issue', 'Возраст застрахованного на дату выпуска полиса', false);
INSERT INTO mt_attribute_def VALUES (1292, 1237, 1, 'INSURANCE_CONTRACT', 'io_birthDate', 'Застрахованный.дата рождения', 'insuredObjects[0].person.birthDate', 8, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.birthDate', NULL, 'birthDate', 'Дата рождения', false);
INSERT INTO mt_attribute_def VALUES (1293, 1237, 1, 'INSURANCE_CONTRACT', 'io_birthPlace', 'Застрахованный.место рождения', 'insuredObjects[0].person.birthPlace', 14, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.birthPlace', NULL, 'birthPlace', 'Место рождения', false);
INSERT INTO mt_attribute_def VALUES (1294, 1237, 1, 'INSURANCE_CONTRACT', 'io_citizenship', 'Застрахованный.гражданство', 'insuredObjects[0].person.citizenship', 15, 'IN', 'SINGLE', 'STRING', 'RU', 'insuredObjects.person.citizenship', 'country2', 'citizenship', 'Гражданство', false);
INSERT INTO mt_attribute_def VALUES (1295, 1237, 1, 'INSURANCE_CONTRACT', 'io_ext_id', 'Застрахованный.внешний id', 'insuredObjects[0].person.ext_id', 33, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.ext_id', NULL, 'ext_id', 'Внешний id', false);
INSERT INTO mt_attribute_def VALUES (1296, 1237, 1, 'INSURANCE_CONTRACT', 'io_familyState', 'Застрахованный.семейное положение', 'insuredObjects[0].person.familyState', 21, 'IN', 'SINGLE', 'STRING', 'SINGLE', 'insuredObjects.person.familyState', 'familyState', 'familyState', 'Семейное положение', false);
INSERT INTO mt_attribute_def VALUES (1297, 1237, 1, 'INSURANCE_CONTRACT', 'io_firstName', 'Застрахованный.имя', 'insuredObjects[0].person.firstName', 1, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.firstName', NULL, 'firstName', 'Имя', false);
INSERT INTO mt_attribute_def VALUES (1298, 1237, 1, 'INSURANCE_CONTRACT', 'io_fullName', 'Застрахованный.полное фио', 'insuredObjects[0].person.fullName', 10, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.fullName', NULL, 'fullName', 'Полное фио', false);
INSERT INTO mt_attribute_def VALUES (1299, 1237, 1, 'INSURANCE_CONTRACT', 'io_fullNameEn', 'Застрахованный.полное фио англ', 'insuredObjects[0].person.fullNameEn', 11, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.fullNameEn', NULL, 'fullNameEn', 'Полное фио англ', false);
INSERT INTO mt_attribute_def VALUES (1300, 1237, 1, 'INSURANCE_CONTRACT', 'io_gender', 'Застрахованный.пол', 'insuredObjects[0].person.gender', 17, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.gender', 'gender', 'gender', 'Пол', false);
INSERT INTO mt_attribute_def VALUES (1301, 1237, 1, 'INSURANCE_CONTRACT', 'io_isPublicOfficial', 'Застрахованный.признак пдл', 'insuredObjects[0].person.isPublicOfficial', 25, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.isPublicOfficial', 'yesNo', 'isPublicOfficial', 'Признак пдл', false);
INSERT INTO mt_attribute_def VALUES (1302, 1237, 1, 'INSURANCE_CONTRACT', 'io_isResident', 'Застрахованный.резидент рф', 'insuredObjects[0].person.isResident', 27, 'IN', 'SINGLE', 'STRING', 'true', 'insuredObjects.person.isResident', 'yesNo', 'isResident', 'Резидент рф', false);
INSERT INTO mt_attribute_def VALUES (1303, 1237, 1, 'INSURANCE_CONTRACT', 'io_lastName', 'Застрахованный.фамилия', 'insuredObjects[0].person.lastName', 4, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.lastName', NULL, 'lastName', 'Фамилия', false);
INSERT INTO mt_attribute_def VALUES (1304, 1237, 1, 'INSURANCE_CONTRACT', 'io_middleName', 'Застрахованный.отчество', 'insuredObjects[0].person.middleName', 6, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.person.middleName', NULL, 'middleName', 'Отчество', false);
INSERT INTO mt_attribute_def VALUES (1305, 1238, 1, 'INSURANCE_CONTRACT', 'io_buildingArea', 'Имущество.площадь здания', 'insuredObjects[0].property.buildingArea', 127, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.buildingArea', NULL, 'buildingArea', 'Площадь здания', false);
INSERT INTO mt_attribute_def VALUES (1306, 1238, 1, 'INSURANCE_CONTRACT', 'io_buildingValue', 'Имущество.стоимость здания', 'insuredObjects[0].property.buildingValue', 129, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.buildingValue', NULL, 'buildingValue', 'Стоимость здания', false);
INSERT INTO mt_attribute_def VALUES (1307, 1238, 1, 'INSURANCE_CONTRACT', 'io_cadastrNr', 'Имущество.кадастровый номер', 'insuredObjects[0].property.cadastrNr', 120, 'IN', 'SINGLE', 'STRING', '77:07:0018002:2590', 'insuredObjects.property.cadastrNr', NULL, 'cadastrNr', 'Кадастровый номер', false);
INSERT INTO mt_attribute_def VALUES (1308, 1238, 1, 'INSURANCE_CONTRACT', 'io_ceilingMaterial', 'Имущество.материал перекрытий', 'insuredObjects[0].property.ceilingMaterial', 123, 'IN', 'SINGLE', 'STRING', 'Смешанные', 'insuredObjects.property.ceilingMaterial', NULL, 'ceilingMaterial', 'Материал перекрытий', false);
INSERT INTO mt_attribute_def VALUES (1309, 1238, 1, 'INSURANCE_CONTRACT', 'io_ceilingMaterialOther', 'Имущество.материал перекрытий другой', 'insuredObjects[0].property.ceilingMaterialOther', 124, 'IN', 'SINGLE', 'STRING', 'Смешанные', 'insuredObjects.property.ceilingMaterialOther', NULL, 'ceilingMaterialOther', 'Материал перекрытий другой', false);
INSERT INTO mt_attribute_def VALUES (1310, 1238, 1, 'INSURANCE_CONTRACT', 'io_commissioningDate', 'Имущество.дата ввода в эксплуатацию', 'insuredObjects[0].property.commissioningDate', 135, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.commissioningDate', NULL, 'commissioningDate', 'Дата ввода в эксплуатацию', false);
INSERT INTO mt_attribute_def VALUES (1311, 1238, 1, 'INSURANCE_CONTRACT', 'io_constructionYear', 'Имущество.год постройки', 'insuredObjects[0].property.constructionYear', 125, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.constructionYear', NULL, 'constructionYear', 'Год постройки', false);
INSERT INTO mt_attribute_def VALUES (1312, 1238, 1, 'INSURANCE_CONTRACT', 'io_floor', 'Имущество.этаж', 'insuredObjects[0].property.floor', 136, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.floor', NULL, 'floor', 'Этаж', false);
INSERT INTO mt_attribute_def VALUES (1313, 1238, 1, 'INSURANCE_CONTRACT', 'io_isNewBuilding', 'Имущество.новостройка', 'insuredObjects[0].property.isNewBuilding', 133, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.isNewBuilding', NULL, 'isNewBuilding', 'Новостройка', false);
INSERT INTO mt_attribute_def VALUES (1314, 1238, 1, 'INSURANCE_CONTRACT', 'io_landArea', 'Имущество.площадь участка', 'insuredObjects[0].property.landArea', 128, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.landArea', NULL, 'landArea', 'Площадь участка', false);
INSERT INTO mt_attribute_def VALUES (1315, 1238, 1, 'INSURANCE_CONTRACT', 'io_numberOfFloors', 'Имущество.количество этажей', 'insuredObjects[0].property.numberOfFloors', 131, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.numberOfFloors', NULL, 'numberOfFloors', 'Количество этажей', false);
INSERT INTO mt_attribute_def VALUES (1316, 1238, 1, 'INSURANCE_CONTRACT', 'io_propertyLocation', 'Имущество.расположение имущества', 'insuredObjects[0].property.propertyLocation', 132, 'IN', 'SINGLE', 'STRING', 'В многоквартирном доме', 'insuredObjects.property.propertyLocation', NULL, 'propertyLocation', 'Расположение имущества', false);
INSERT INTO mt_attribute_def VALUES (1317, 1238, 1, 'INSURANCE_CONTRACT', 'io_propertyTypeCode', 'Имущество.тип имущества код', 'insuredObjects[0].property.propertyType.code', 104, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.propertyType.code', NULL, 'propertyTypeCode', 'Тип имущества код', false);
INSERT INTO mt_attribute_def VALUES (1318, 1238, 1, 'INSURANCE_CONTRACT', 'io_propertyValue', 'Имущество.стоимость имущества', 'insuredObjects[0].property.propertyValue', 134, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.propertyValue', NULL, 'propertyValue', 'Стоимость имущества', false);
INSERT INTO mt_attribute_def VALUES (1319, 1238, 1, 'INSURANCE_CONTRACT', 'io_repairYear', 'Имущество.год ремонта', 'insuredObjects[0].property.repairYear', 126, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.property.repairYear', NULL, 'repairYear', 'Год ремонта', false);
INSERT INTO mt_attribute_def VALUES (1320, 1238, 1, 'INSURANCE_CONTRACT', 'io_wallsMaterial', 'Имущество.материал стен', 'insuredObjects[0].property.wallsMaterial', 121, 'IN', 'SINGLE', 'STRING', 'Каменные, кирпичные', 'insuredObjects.property.wallsMaterial', NULL, 'wallsMaterial', 'Материал стен', false);
INSERT INTO mt_attribute_def VALUES (1321, 1238, 1, 'INSURANCE_CONTRACT', 'io_wallsMaterialOther', 'Имущество.материал стен другой', 'insuredObjects[0].property.wallsMaterialOther', 122, 'IN', 'SINGLE', 'STRING', 'Каменные, кирпичные', 'insuredObjects.property.wallsMaterialOther', NULL, 'wallsMaterialOther', 'Материал стен другой', false);
INSERT INTO mt_attribute_def VALUES (1322, 1238, 1, 'INSURANCE_CONTRACT', 'io_wearCoefficient', 'Имущество.коэффициент износа', 'insuredObjects[0].property.wearCoefficient', 130, 'IN', 'SINGLE', 'NUMBER', '0', 'insuredObjects.property.wearCoefficient', NULL, 'wearCoefficient', 'Коэффициент износа', false);
INSERT INTO mt_attribute_def VALUES (1323, 1239, 1, 'INSURANCE_CONTRACT', 'rf_profSport', 'Профессиональный спорт', 'insuredObjects[0].riskFactors.profSport', 150, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.profSport', NULL, 'profSport', 'Профессиональный спорт', false);
INSERT INTO mt_attribute_def VALUES (1324, 1239, 1, 'INSURANCE_CONTRACT', 'rf_sport1', 'Доп.риск спорт #1', 'insuredObjects[0].riskFactors.sport1', 145, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport1', NULL, 'sport1', 'Доп.риск спорт #1', false);
INSERT INTO mt_attribute_def VALUES (1325, 1239, 1, 'INSURANCE_CONTRACT', 'rf_sport2', 'Доп.риск спорт #2', 'insuredObjects[0].riskFactors.sport2', 146, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport2', NULL, 'sport2', 'Доп.риск спорт #2', false);
INSERT INTO mt_attribute_def VALUES (1326, 1239, 1, 'INSURANCE_CONTRACT', 'rf_sport3', 'Доп.риск спорт #3', 'insuredObjects[0].riskFactors.sport3', 147, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport3', NULL, 'sport3', 'Доп.риск спорт #3', false);
INSERT INTO mt_attribute_def VALUES (1327, 1239, 1, 'INSURANCE_CONTRACT', 'rf_sport4', 'Доп.риск спорт #4', 'insuredObjects[0].riskFactors.sport4', 148, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport4', NULL, 'sport4', 'Доп.риск спорт #4', false);
INSERT INTO mt_attribute_def VALUES (1328, 1239, 1, 'INSURANCE_CONTRACT', 'rf_sport5', 'Доп.риск спорт #5', 'insuredObjects[0].riskFactors.sport5', 149, 'IN', 'SINGLE', 'STRING', '0', 'insuredObjects.riskFactors.sport5', NULL, 'sport5', 'Доп.риск спорт #5', false);
INSERT INTO mt_attribute_def VALUES (1329, 1241, 1, 'INSURANCE_CONTRACT', 'io_arrivalCity', 'Город прилета', 'insuredObjects[0].travelSegments[*].arrivalCity', 113, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].arrivalCity', NULL, 'arrivalCity', 'Город прилета', false);
INSERT INTO mt_attribute_def VALUES (1330, 1241, 1, 'INSURANCE_CONTRACT', 'io_departureCity', 'Город вылета', 'insuredObjects[0].travelSegments[*].departureCity', 111, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].departureCity', NULL, 'departureCity', 'Город вылета', false);
INSERT INTO mt_attribute_def VALUES (1331, 1241, 1, 'INSURANCE_CONTRACT', 'io_departureDate', 'Дата вылета', 'insuredObjects[0].travelSegments[*].departureDate', 107, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].departureDate', NULL, 'departureDate', 'Дата вылета', false);
INSERT INTO mt_attribute_def VALUES (1332, 1241, 1, 'INSURANCE_CONTRACT', 'io_departureTime', 'Время вылета', 'insuredObjects[0].travelSegments[*].departureTime', 109, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].departureTime', NULL, 'departureTime', 'Время вылета', false);
INSERT INTO mt_attribute_def VALUES (1333, 1241, 1, 'INSURANCE_CONTRACT', 'io_legs', 'Количество перелетов', 'insuredObjects[0].travelSegments[*].count()', 56, 'IN', 'SINGLE', 'NUMBER', NULL, 'insuredObjects.travelSegments[*].count()', NULL, 'legs', 'Количество перелетов', false);
INSERT INTO mt_attribute_def VALUES (1334, 1241, 1, 'INSURANCE_CONTRACT', 'io_ticketNr', 'Номер билета', 'insuredObjects[0].travelSegments[*].ticketNr', 105, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].ticketNr', NULL, 'ticketNr', 'Номер билета', false);
INSERT INTO mt_attribute_def VALUES (1335, 1241, 1, 'INSURANCE_CONTRACT', 'io_ticketPrice', 'Стоимость билета', 'insuredObjects[0].travelSegments[*].ticketPrice.sum()', 53, 'IN', 'SINGLE', 'NUMBER', NULL, 'insuredObjects.travelSegments[*].ticketPrice.sum()', NULL, 'ticketPrice', 'Стоимость билета', false);

INSERT INTO mt_attribute_def VALUES (1529, 1219, 1, 'INSURANCE_CONTRACT', 'ic_code', 'код СК', 'insurer.code', 1, 'VAR', 'SINGLE', 'STRING', '', 'insurer.code', NULL, 'code', 'код СК', true);
INSERT INTO mt_attribute_def VALUES (1528, 1219, 1, 'INSURANCE_CONTRACT', 'ic_name', 'название СК', 'insurer.name', 2, 'VAR', 'SINGLE', 'STRING', '', 'insurer.name', NULL, 'name', 'название СК', true);
INSERT INTO mt_attribute_def VALUES (1527, 1219, 1, 'INSURANCE_CONTRACT', 'ic_representative', 'Представитель, кто подписывает', 'insurer.contractRepresentative', 10, 'VAR', 'SINGLE', 'STRING', '', 'insurer.contractRepresentative', NULL, 'contractRepresentative', 'Представитель, кто подписывает', true);
INSERT INTO mt_attribute_def VALUES (1745, 1219, 1, 'INSURANCE_CONTRACT', 'ic_displayName', 'Строка для страхового договора', 'insurer.contractText', 12, 'VAR', 'SINGLE', 'STRING', '', 'insurer.organization.displayName', NULL, 'contractText', 'Строка для страхового договора', true);

INSERT INTO mt_attribute_def VALUES (1377, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_addressStr', 'Ph.адрес.адресная строка', 'policyHolder.addresses[?(@.isPrimary)].addressStr', 98, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.addressStr', NULL, 'addressStr', 'Адресная строка', false);
INSERT INTO mt_attribute_def VALUES (1378, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_addressStrEn', 'Ph.адрес.адресная строка англ', 'policyHolder.addresses[?(@.isPrimary)].addressStrEn', 99, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.addressStrEn', NULL, 'addressStrEn', 'Адресная строка англ', false);
INSERT INTO mt_attribute_def VALUES (1379, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_building', 'Ph.адрес.строение', 'policyHolder.addresses[?(@.isPrimary)].building', 86, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.building', NULL, 'building', 'Строение', false);
INSERT INTO mt_attribute_def VALUES (1380, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_city', 'Ph.адрес.город', 'policyHolder.addresses[?(@.isPrimary)].city', 79, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.city', NULL, 'city', 'Город', false);
INSERT INTO mt_attribute_def VALUES (1381, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_countryCode', 'Ph.адрес.код страны', 'policyHolder.addresses[?(@.isPrimary)].countryCode', 76, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.addresses.countryCode', 'country2', 'countryCode', 'Код страны', false);
INSERT INTO mt_attribute_def VALUES (1382, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_ext_id', 'Ph.адрес.внешний id', 'policyHolder.addresses[?(@.isPrimary)].ext_id', 101, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.ext_id', NULL, 'ext_id', 'Внешний id', false);
INSERT INTO mt_attribute_def VALUES (1383, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_fiasId', 'Ph.адрес.код фиас', 'policyHolder.addresses[?(@.isPrimary)].fiasId', 95, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.fiasId', NULL, 'fiasId', 'Код фиас', false);
INSERT INTO mt_attribute_def VALUES (1384, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_flat', 'Ph.адрес.квартира', 'policyHolder.addresses[?(@.isPrimary)].flat', 87, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.flat', NULL, 'flat', 'Квартира', false);
INSERT INTO mt_attribute_def VALUES (1385, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_house', 'Ph.адрес.дом', 'policyHolder.addresses[?(@.isPrimary)].house', 83, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.house', NULL, 'house', 'Дом', false);
INSERT INTO mt_attribute_def VALUES (1386, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_kladrId', 'Ph.адрес.код кладр', 'policyHolder.addresses[?(@.isPrimary)].kladrId', 93, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.kladrId', NULL, 'kladrId', 'Код кладр', false);
INSERT INTO mt_attribute_def VALUES (1387, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_region', 'Ph.адрес.регион', 'policyHolder.addresses[?(@.isPrimary)].region', 77, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.region', NULL, 'region', 'Регион', false);
INSERT INTO mt_attribute_def VALUES (1388, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_room', 'Ph.адрес.комната', 'policyHolder.addresses[?(@.isPrimary)].room', 89, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.room', NULL, 'room', 'Комната', false);
INSERT INTO mt_attribute_def VALUES (1389, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_street', 'Ph.адрес.улица', 'policyHolder.addresses[?(@.isPrimary)].street', 81, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.street', NULL, 'street', 'Улица', false);
INSERT INTO mt_attribute_def VALUES (1390, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_typeCode', 'Ph.адрес.тип адреса', 'policyHolder.addresses[?(@.isPrimary)].typeCode', 74, 'IN', 'SINGLE', 'STRING', 'REGISTRATION', 'policyHolder.addresses.typeCode', 'addressType', 'typeCode', 'Тип адреса', false);
INSERT INTO mt_attribute_def VALUES (1391, 1246, 1, 'INSURANCE_CONTRACT', 'ph_addr_zipCode', 'Ph.адрес.индекс', 'policyHolder.addresses[?(@.isPrimary)].zipCode', 92, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.addresses.zipCode', NULL, 'zipCode', 'Индекс', false);
INSERT INTO mt_attribute_def VALUES (1392, 1247, 1, 'INSURANCE_CONTRACT', 'ph_email', 'Страхователь.email', 'policyHolder.contacts.email', 52, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.contacts.email', NULL, 'email', 'Email', false);
INSERT INTO mt_attribute_def VALUES (1393, 1247, 1, 'INSURANCE_CONTRACT', 'ph_phone', 'Страхователь.телефон', 'policyHolder.contacts.phone', 49, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.contacts.phone', NULL, 'phone', 'Телефон', false);
INSERT INTO mt_attribute_def VALUES (1394, 1248, 1, 'INSURANCE_CONTRACT', 'ph_doc_countryCode', 'Ph.документ.страна выдачи документа', 'policyHolder.identifiers[?(@.isPrimary)].countryCode', 72, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.identifiers.countryCode', 'country2', 'countryCode', 'Страна выдачи документа', false);
INSERT INTO mt_attribute_def VALUES (1395, 1248, 1, 'INSURANCE_CONTRACT', 'ph_doc_dateIssue', 'Ph.документ.дата выдачи', 'policyHolder.identifiers[?(@.isPrimary)].dateIssue', 61, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.dateIssue', NULL, 'dateIssue', 'Дата выдачи', false);
INSERT INTO mt_attribute_def VALUES (1396, 1248, 1, 'INSURANCE_CONTRACT', 'ph_doc_divisionCode', 'Ph.документ.код подразделения', 'policyHolder.identifiers[?(@.isPrimary)].divisionCode', 67, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.divisionCode', NULL, 'divisionCode', 'Код подразделения', false);
INSERT INTO mt_attribute_def VALUES (1397, 1248, 1, 'INSURANCE_CONTRACT', 'ph_doc_ext_id', 'Ph.документ.внешний id', 'policyHolder.identifiers[?(@.isPrimary)].ext_id', 70, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.ext_id', NULL, 'ext_id', 'Внешний id', false);
INSERT INTO mt_attribute_def VALUES (1398, 1248, 1, 'INSURANCE_CONTRACT', 'ph_doc_number', 'Ph.документ.номер документа', 'policyHolder.identifiers[?(@.isPrimary)].number', 60, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.number', NULL, 'number', 'Номер документа', false);
INSERT INTO mt_attribute_def VALUES (1399, 1248, 1, 'INSURANCE_CONTRACT', 'ph_doc_serial', 'Ph.документ.серия документа', 'policyHolder.identifiers[?(@.isPrimary)].serial', 57, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.serial', NULL, 'serial', 'Серия документа', false);
INSERT INTO mt_attribute_def VALUES (1400, 1248, 1, 'INSURANCE_CONTRACT', 'ph_doc_typeCode', 'Ph.документ.код типа документа', 'policyHolder.identifiers[?(@.isPrimary)].typeCode', 55, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.typeCode', 'identifierType', 'typeCode', 'Код типа документа', false);
INSERT INTO mt_attribute_def VALUES (1401, 1248, 1, 'INSURANCE_CONTRACT', 'ph_doc_validUntil', 'Ph.документ.действительно до', 'policyHolder.identifiers[?(@.isPrimary)].validUntil', 64, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.validUntil', NULL, 'validUntil', 'Действительно до', false);
INSERT INTO mt_attribute_def VALUES (1402, 1248, 1, 'INSURANCE_CONTRACT', 'ph_doc_whom', 'Ph.документ.кем выдан', 'policyHolder.identifiers[?(@.isPrimary)].whom', 65, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.identifiers.whom', NULL, 'whom', 'Кем выдан', false);
INSERT INTO mt_attribute_def VALUES (1404, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_country', 'Страхователь.код страны регистрации', 'policyHolder.organization.country', 35, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.country', 'country2', 'country', 'Код страны регистрации', false);
INSERT INTO mt_attribute_def VALUES (1405, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_ext_id', 'Страхователь.внешний id (юрик)', 'policyHolder.organization.ext_id', 47, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.ext_id', NULL, 'ext_id', 'Внешний id (юрик)', false);
INSERT INTO mt_attribute_def VALUES (1406, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_fullName', 'Страхователь.полное наименование юр.лица', 'policyHolder.organization.fullName', 37, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.fullName', NULL, 'fullName', 'Полное наименование юр.лица', false);
INSERT INTO mt_attribute_def VALUES (1407, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_fullNameEn', 'Страхователь.полное наименование  юр.лица англ', 'policyHolder.organization.fullNameEn', 38, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.fullNameEn', NULL, 'fullNameEn', 'Полное наименование  юр.лица англ', false);
INSERT INTO mt_attribute_def VALUES (1408, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_group', 'Страхователь.gруппа страхователя юл', 'policyHolder.organization.group', 46, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.group', NULL, 'group', 'Gруппа страхователя юл', false);
INSERT INTO mt_attribute_def VALUES (1409, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_inn', 'Страхователь.инн юр.лица', 'policyHolder.organization.inn', 36, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.inn', NULL, 'inn', 'Инн юр.лица', false);
INSERT INTO mt_attribute_def VALUES (1410, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_isResident', 'Страхователь.резидент рф юр.лица', 'policyHolder.organization.isResident', 45, 'IN', 'SINGLE', 'STRING', 'true', 'policyHolder.organization.isResident', 'yesNo', 'isResident', 'Резидент рф юр.лица', false);
INSERT INTO mt_attribute_def VALUES (1411, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_kpp', 'Страхователь.кпп', 'policyHolder.organization.kpp', 41, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.kpp', NULL, 'kpp', 'Кпп', false);
INSERT INTO mt_attribute_def VALUES (1412, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_legalForm', 'Страхователь.организационно-правовая форма', 'policyHolder.organization.legalForm', 40, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.legalForm', NULL, 'legalForm', 'Организационно-правовая форма', false);
INSERT INTO mt_attribute_def VALUES (1413, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_nciCode', 'Страхователь.нси код', 'policyHolder.organization.nciCode', 48, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.nciCode', NULL, 'nciCode', 'Нси код', false);
INSERT INTO mt_attribute_def VALUES (1414, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_ogrn', 'Страхователь.огрн', 'policyHolder.organization.ogrn', 42, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.ogrn', NULL, 'ogrn', 'Огрн', false);
INSERT INTO mt_attribute_def VALUES (1415, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_okpo', 'Страхователь.окпо', 'policyHolder.organization.okpo', 43, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.okpo', NULL, 'okpo', 'Окпо', false);
INSERT INTO mt_attribute_def VALUES (1416, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_shortName', 'Страхователь.краткое наименование юр.лица', 'policyHolder.organization.shortName', 39, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.shortName', NULL, 'shortName', 'Краткое наименование юр.лица', false);
INSERT INTO mt_attribute_def VALUES (1417, 1250, 1, 'INSURANCE_CONTRACT', 'ph_age_end', 'Страхователь.возраст на дату окончания договора', 'null', 141, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_end', 'Возраст на дату окончания договора', false);
INSERT INTO mt_attribute_def VALUES (1418, 1250, 1, 'INSURANCE_CONTRACT', 'ph_age_issue', 'Страхователь.возраст на дату выпуска договора', 'null', 142, 'MAGIC', 'SINGLE', 'NUMBER', NULL, 'null', NULL, 'age_issue', 'Возраст на дату выпуска договора', false);
INSERT INTO mt_attribute_def VALUES (1419, 1250, 1, 'INSURANCE_CONTRACT', 'ph_birthDate', 'Страхователь.дата рождения', 'policyHolder.person.birthDate', 7, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.birthDate', NULL, 'birthDate', 'Дата рождения', false);
INSERT INTO mt_attribute_def VALUES (1420, 1250, 1, 'INSURANCE_CONTRACT', 'ph_birthPlace', 'Страхователь.место рождения', 'policyHolder.person.birthPlace', 13, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.birthPlace', NULL, 'birthPlace', 'Место рождения', false);
INSERT INTO mt_attribute_def VALUES (1218, 1216, 1, 'INSURANCE_CONTRACT', 'insuredObject', 'Объект страхования', 'insuredObject[0]', 400, 'OBJECT', 'SINGLE', 'OBJECT', '', 'insuredObject', NULL, 'insuredObject', 'Объект страхования', false);
INSERT INTO mt_attribute_def VALUES (1240, 1218, 1, 'INSURANCE_CONTRACT', 'io_sumInsured', 'Страховая сумма объекта страхования', 'insuredObjects[0].sumInsured', 19, 'IN', 'SINGLE', 'NUMBER', '100000', 'insuredObjects.sumInsured', NULL, 'io_sumInsured', 'Страховая сумма объекта страхования', false);
INSERT INTO mt_attribute_def VALUES (1433, 1216, 1, 'INSURANCE_CONTRACT', 'pl_installmentType', 'Периодичность оплаты', 'installmentType', 10, 'IN', 'SINGLE', 'STRING', '', 'installmentType', 'installmentType', 'pl_installmentType', 'Периодичность оплаты', false);
INSERT INTO mt_attribute_def VALUES (1434, 1216, 1, 'INSURANCE_CONTRACT', 'pl_premiumCur', 'Премия в валюте договора (не рубли )', 'premiumCur', 20, 'VAR', 'SINGLE', 'NUMBER', '', 'premiumCur', NULL, 'pl_premiumCur', 'Премия в валюте договора (не рубли )', false);
INSERT INTO mt_attribute_def VALUES (1436, 1216, 1, 'INSURANCE_CONTRACT', 'pl_currencyRate', 'Курс на дату расчета премии', 'currencyRate', 25, 'VAR', 'SINGLE', 'NUMBER', '', 'currencyRate', NULL, 'pl_currencyRate', 'Курс на дату расчета премии', false);
INSERT INTO mt_attribute_def VALUES (1219, 1216, 1, 'INSURANCE_CONTRACT', 'insurer', 'Страховщик', 'insurer', 200, 'OBJECT', 'SINGLE', 'OBJECT', NULL, 'insurer', NULL, 'insurer', 'Страховщик', false);

INSERT INTO mt_attribute_def VALUES (1490, NULL, 1, 'INSURANCE_CONTRACT', 'txt_insurer', 'Страховщик', '', 1116, 'TEXT', 'SINGLE', 'STRING', 'САО ВСК', 'strings.txt_insurer', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1491, NULL, 1, 'INSURANCE_CONTRACT', 'txt_header', 'Шапка номер от дата', '', 1119, 'TEXT', 'SINGLE', 'STRING', 'Договор страхования № {{pl_policyNumber}} от {{pl_issueDate|dd MMMM yyyy}}г.', 'strings.txt_header', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1492, NULL, 1, 'INSURANCE_CONTRACT', 'txt_policy_number', 'Номер договора', '', 1101, 'TEXT', 'SINGLE', 'STRING', 'Договор страхования № {{pl_policyNumber}} от {{pl_issueDate|dd.MM.yyyy}}', 'strings.txt_policy_number', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1493, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_citizenship', 'Страхователь гражданство', '', 1122, 'TEXT', 'SINGLE', 'STRING', '{{ph_citizenship|country2}}', 'strings.txt_ph_citizenship', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1494, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_dob', 'Страхователь дата рождения', '', 1104, 'TEXT', 'SINGLE', 'STRING', '{{ph_birthDate|dd.MM.yyyy}}', 'strings.txt_ph_dob', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1495, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_address', 'Страхователь адрес регистрации', '', 1105, 'TEXT', 'SINGLE', 'STRING', 'Адрес регистрации: {{ph_addr_addressStr}}', 'strings.txt_ph_address', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1496, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_phone', 'Страхователь телефон', '', 1106, 'TEXT', 'SINGLE', 'STRING', 'Телефон: {{ph_phone}}', 'strings.txt_ph_phone', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1497, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_email', 'Страхователь адрес электронной почты', '', 1107, 'TEXT', 'SINGLE', 'STRING', '{{ph_email}}', 'strings.txt_ph_email', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1498, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_id', 'Страхователь документ, удостоверяющий личность наименование', '', 1108, 'TEXT', 'SINGLE', 'STRING', '{{#if ph_doc_serial}}серия: {{ph_doc_serial}}{{/if}}{{#if ph_doc_number}}  номер: {{ph_doc_number}}{{/if}}{{#if ph_doc_whom}}  кем выдан: {{ph_doc_whom}}{{/if}}{{#if ph_doc_dateIssue}}  дата выдачи:{{ph_doc_dateIssue|dd.MM.yyyy}}{{/if}}\n', 'strings.txt_ph_id', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1499, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_id_serial', 'Страхователь документ серия', '', 1109, 'TEXT', 'SINGLE', 'STRING', 'Серия: {{ph_doc_serial}}', 'strings.txt_ph_id_serial', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1500, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_id_number', 'Страхователь документ номер', '', 1110, 'TEXT', 'SINGLE', 'STRING', 'Номер: {{ph_doc_number}}', 'strings.txt_ph_id_number', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1501, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_id_date', 'Страхователь документ дата выдачи', '', 1111, 'TEXT', 'SINGLE', 'STRING', 'Дата выдачи: {{ph_doc_dateIssue|dd.MM.yyyy}}', 'strings.txt_ph_id_date', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1502, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph_id_whom', 'Страхователь документ кем выдан', '', 1112, 'TEXT', 'SINGLE', 'STRING', '{{ph_doc_whom}}', 'strings.txt_ph_id_whom', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1503, NULL, 1, 'INSURANCE_CONTRACT', 'txt_sumInsured', 'Страховая сумма', '', 1121, 'TEXT', 'SINGLE', 'STRING', '{{io_sumInsured|money}}', 'strings.txt_sumInsured', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1504, NULL, 1, 'INSURANCE_CONTRACT', 'txt_premium', 'Страховая премия', '', 1123, 'TEXT', 'SINGLE', 'STRING', '{{pl_premium|money}} рублей.', 'strings.txt_premium', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1505, NULL, 1, 'INSURANCE_CONTRACT', 'txt_paymentDate', 'Страховая премия уплачена', '', 1124, 'TEXT', 'SINGLE', 'STRING', '{{payment_date|dd MMMM yyyy}}', 'strings.txt_paymentDate', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1506, NULL, 1, 'INSURANCE_CONTRACT', 'txt_period_text', 'Период ответственности Страховщика', '', 1125, 'TEXT', 'SINGLE', 'STRING', 'с {{pl_startDate|date}} по {{pl_endDate|date}}', 'strings.txt_period_text', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1507, NULL, 1, 'INSURANCE_CONTRACT', 'txt_issueDate', 'Дата заключения договора', '', 1128, 'TEXT', 'SINGLE', 'STRING', '{{pl_issueDate|dd.MM.yyyy}}', 'strings.txt_issueDate', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1508, NULL, 1, 'INSURANCE_CONTRACT', 'txt_start_period', 'Срок действия договора с', '', 1145, 'TEXT', 'SINGLE', 'STRING', 'с 00 часов {{pl_startDate|dd MMMM yyyy}}г. но не ранее времени фактической оплаты страховой премии в полном объеме.', 'strings.txt_start_period', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1509, NULL, 1, 'INSURANCE_CONTRACT', 'txt_end_period', 'Срок действия договора по', '', 1146, 'TEXT', 'SINGLE', 'STRING', 'до 24 часов {{pl_endDate|dd MMMM yyyy}}г.', 'strings.txt_end_period', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1510, NULL, 1, 'INSURANCE_CONTRACT', 'txt_sports', 'Все виды спорта', '', 1148, 'TEXT', 'SINGLE', 'STRING', '{{#if rf_sport1}}{{rf_sport1}}{{/if}}{{#if rf_sport2}},{{rf_sport2}}{{/if}}{{#if rf_sport3}},{{rf_sport3}}{{/if}}{{#if rf_sport4}},{{rf_sport4}}{{/if}}{{#if rf_sport5}},{{rf_sport5}}{{/if}}', 'strings.txt_sports', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1511, NULL, 1, 'INSURANCE_CONTRACT', 'io_digest', 'Объект страхования', '', 1147, 'TEXT', 'SINGLE', 'STRING', '{{io_device_model}} {{io_device_name}}', 'strings.io_digest', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1512, NULL, 1, 'INSURANCE_CONTRACT', 'ph_digest', 'Страхователь ( для ЛК)', '', 1148, 'TEXT', 'SINGLE', 'STRING', '{{ph_lastName}} {{ph_firstName}} {{ph_middleName}}', 'strings.ph_digest', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1513, NULL, 1, 'INSURANCE_CONTRACT', 'txt_pl_territory', 'Территория страхования', '', 1240, 'TEXT', 'SINGLE', 'STRING', 'Весь мир', 'strings.txt_pl_territory', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1514, NULL, 1, 'INSURANCE_CONTRACT', 'txt_pl_payment_frequency', 'Порядок уплаты премии', '', 1241, 'TEXT', 'SINGLE', 'STRING', 'единовременно', 'strings.txt_pl_payment_frequency', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1515, NULL, 1, 'INSURANCE_CONTRACT', 'txt_ph', 'Страхователь', '', 1243, 'TEXT', 'SINGLE', 'STRING', '{{ph_lastName}} {{ph_firstName}} {{ph_middleName}}', 'strings.txt_ph', NULL, NULL, NULL, false);
INSERT INTO mt_attribute_def VALUES (1516, NULL, 1, 'INSURANCE_CONTRACT', 'txt', 'txt', '', 1243, 'TEXT', 'SINGLE', 'STRING', '', 'strings.txt', NULL, NULL, NULL, false);

INSERT INTO mt_attribute_def VALUES (1518, 1241, 1, 'INSURANCE_CONTRACT', 'io_departureAirportIATA', 'Аэропорт вылета IATA', 'insuredObjects[0].travelSegments[*].departureAirportIATA', 202, 'IN', 'SINGLE', 'STRING', NULL, 'insuredObjects.travelSegments[*].departureAirportIATA', NULL, 'departureAirportIATA', 'Аэропорт вылета IATA', false);
INSERT INTO mt_attribute_def VALUES (1252, 1230, 1, 'INSURANCE_CONTRACT', 'pl_commRate', 'Процент кв по договору', 'commission.appliedCommissionRate', 1, 'VAR', 'SINGLE', 'NUMBER', NULL, 'commission.appliedCommissionRate', NULL, 'commRate', 'Процент кв по договору', true);
INSERT INTO mt_attribute_def VALUES (1525, 1230, 1, 'INSURANCE_CONTRACT', 'pl_reqCommDiscount', 'Запрошенная скидка за счет комиссии', 'commission.requestedCommissionDiscount', 3, 'IN', 'SINGLE', 'NUMBER', NULL, 'commission.requestedCommissionDiscount', NULL, 'requestedCommissionDiscount', 'Запрошенная скидка за счет комиссии', false);
INSERT INTO mt_attribute_def VALUES (1526, 1230, 1, 'INSURANCE_CONTRACT', 'pl_reqCommRate', 'Запрошенный размер комиссии', 'commission.requestedCommissionRate', 4, 'IN', 'SINGLE', 'NUMBER', NULL, 'commission.requestedCommissionRate', NULL, 'requestedCommissionRate', 'Запрошенный размер комиссии', false);
INSERT INTO mt_attribute_def VALUES (1403, 1249, 1, 'INSURANCE_CONTRACT', 'ph_org_bic', 'Страхователь.бик', 'policyHolder.organization.bic', 44, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.organization.bic', NULL, 'bic', 'Бик', false);
INSERT INTO mt_attribute_def VALUES (1421, 1250, 1, 'INSURANCE_CONTRACT', 'ph_citizenship', 'Страхователь.гражданство', 'policyHolder.person.citizenship', 16, 'IN', 'SINGLE', 'STRING', 'RU', 'policyHolder.person.citizenship', 'country2', 'citizenship', 'Гражданство', false);
INSERT INTO mt_attribute_def VALUES (1422, 1250, 1, 'INSURANCE_CONTRACT', 'ph_ext_id', 'Страхователь.внешний id', 'policyHolder.person.ext_id', 31, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.ext_id', NULL, 'ext_id', 'Внешний id', false);
INSERT INTO mt_attribute_def VALUES (1423, 1250, 1, 'INSURANCE_CONTRACT', 'ph_familyState', 'Страхователь.семейное положение', 'policyHolder.person.familyState', 20, 'IN', 'SINGLE', 'STRING', 'SINGLE', 'policyHolder.person.familyState', 'familyState', 'familyState', 'Семейное положение', false);
INSERT INTO mt_attribute_def VALUES (1424, 1250, 1, 'INSURANCE_CONTRACT', 'ph_firstName', 'Страхователь.имя', 'policyHolder.person.firstName', 2, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.firstName', NULL, 'firstName', 'Имя', false);
INSERT INTO mt_attribute_def VALUES (1425, 1250, 1, 'INSURANCE_CONTRACT', 'ph_fullName', 'Страхователь.полное фио', 'policyHolder.person.fullName', 9, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.fullName', NULL, 'fullName', 'Полное фио', false);
INSERT INTO mt_attribute_def VALUES (1426, 1250, 1, 'INSURANCE_CONTRACT', 'ph_fullNameEn', 'Страхователь.полное фио англ', 'policyHolder.person.fullNameEn', 12, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.fullNameEn', NULL, 'fullNameEn', 'Полное фио англ', false);
INSERT INTO mt_attribute_def VALUES (1427, 1250, 1, 'INSURANCE_CONTRACT', 'ph_gender', 'Пол', 'policyHolder.person.gender', 18, 'IN', 'SINGLE', 'STRING', '', 'policyHolder.person.gender', 'gender', 'ph_gender', 'Пол', false);
INSERT INTO mt_attribute_def VALUES (1428, 1250, 1, 'INSURANCE_CONTRACT', 'ph_isPublicOfficial', 'Страхователь.признак пдл', 'policyHolder.person.isPublicOfficial', 26, 'IN', 'SINGLE', 'STRING', '', 'policyHolder.person.isPublicOfficial', 'yesNo', 'ph_isPublicOfficial', 'Страхователь.признак пдл', false);
INSERT INTO mt_attribute_def VALUES (1429, 1250, 1, 'INSURANCE_CONTRACT', 'ph_isResident', 'Страхователь.резидент рф', 'policyHolder.person.isResident', 28, 'IN', 'SINGLE', 'STRING', 'true', 'policyHolder.person.isResident', 'yesNo', 'ph_isResident', 'Страхователь.резидент рф', false);
INSERT INTO mt_attribute_def VALUES (1430, 1250, 1, 'INSURANCE_CONTRACT', 'ph_lastName', 'Страхователь.фамилия', 'policyHolder.person.lastName', 3, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.lastName', NULL, 'lastName', 'Фамилия', false);
INSERT INTO mt_attribute_def VALUES (1431, 1250, 1, 'INSURANCE_CONTRACT', 'ph_middleName', 'Страхователь.отчество', 'policyHolder.person.middleName', 5, 'IN', 'SINGLE', 'STRING', NULL, 'policyHolder.person.middleName', NULL, 'middleName', 'Отчество', false);


SET session_replication_role = 'origin';

INSERT INTO pt_insurance_company VALUES (112, 1, 'vsk', 'VSK', 'active', '{}', 'ACTIVE', '2026-04-06 14:59:36.107812', '2026-04-06 14:59:36.107812');

INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '1', 'Паспорт гражданина СССР');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '2', 'Загранпаспорт гражданина СССР');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '3', 'Свидетельство о рождении');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '4', 'Удостоверение личности офицера');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '5', 'Справка об освобождении из места лишения свободы');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '6', 'Паспорт Минморфлота');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '7', 'Военный билет');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '8', 'Временное удостоверение, выданное взамен военного билета');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '9', 'Дипломатический паспорт');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '10', 'Паспорт иностранного гражданина');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '11', 'Свидетельство о рассмотрении ходатайства о признании лица беженцем на территории РФ по существу');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '12', 'Вид на жительство в Российской Федерации');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '13', 'Удостоверение беженца');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '14', 'Временное удостоверение личности гражданина Российской Федерации');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '15', 'Разрешение на временное проживание в Российской Федерации');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '16', 'Временное удостоверение личности лица без гражданства в РФ');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '18', 'Свидетельство о предоставлении временного убежища на территории Российской Федерации (до 01.01.2013)');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '19', 'Свидетельство о предоставлении временного убежища на территории Российской Федерации');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '21', 'Паспорт гражданина Российской Федерации');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '22', 'Паспорт гражданина РФ, удостоверяющий личность гражданина РФ за пределами территории РФ');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '23', 'Свидетельство о рождении, выданное уполномоченным органом иностранного государства');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '24', 'Удостоверение личности военнослужащего Российской Федерации');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '26', 'Паспорт моряка');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '27', 'Военный билет офицера запаса');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '28', 'Служебный паспорт гражданина Российской Федерации');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '60', 'Документы, подтверждающие факт регистрации по месту жительства (пребывания)');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '61', 'Свидетельство о регистрации по месту жительства');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '62', 'Вид на жительство иностранного гражданина');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '63', 'Свидетельство о регистрации по месту пребывания');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '81', 'Свидетельство о смерти');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('fns-dul', '91', 'Иные документы');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AF', 'Афганистан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AX', 'Аландские острова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AL', 'Албания');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'DZ', 'Алжир');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AS', 'Американское Самоа');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AD', 'Андорра');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AO', 'Ангола');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AI', 'Ангилья');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AQ', 'Антарктида');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AG', 'Антигуа и Барбуда');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AR', 'Аргентина');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AM', 'Армения');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AW', 'Аруба');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AU', 'Австралия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AT', 'Австрия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AZ', 'Азербайджан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BS', 'Багамы');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BH', 'Бахрейн');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BD', 'Бангладеш');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BB', 'Барбадос');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BY', 'Беларусь');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BE', 'Бельгия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BZ', 'Белиз');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BJ', 'Бенин');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BM', 'Бермуды');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BT', 'Бутан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BO', 'Боливия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BQ', 'Бонайре, Синт-Эстатиус и Саба');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BA', 'Босния и Герцеговина');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BW', 'Ботсвана');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BV', 'Остров Буве');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BR', 'Бразилия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'IO', 'Британская территория в Индийском океане');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BN', 'Бруней');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BG', 'Болгария');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BF', 'Буркина-Фасо');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BI', 'Бурунди');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CV', 'Кабо-Верде');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KH', 'Камбоджа');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CM', 'Камерун');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CA', 'Канада');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KY', 'Каймановы острова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CF', 'Центральноафриканская Республика');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TD', 'Чад');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CL', 'Чили');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CN', 'Китай');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CX', 'Остров Рождества');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CC', 'Кокосовые острова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CO', 'Колумбия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KM', 'Коморы');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CG', 'Конго');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CD', 'Конго, Демократическая Республика');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CK', 'Острова Кука');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CR', 'Коста-Рика');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CI', 'Кот-д''Ивуар');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'HR', 'Хорватия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CU', 'Куба');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CW', 'Кюрасао');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CY', 'Кипр');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CZ', 'Чехия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'DK', 'Дания');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'DJ', 'Джибути');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'DM', 'Доминика');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'DO', 'Доминиканская Республика');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'EC', 'Эквадор');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'EG', 'Египет');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SV', 'Сальвадор');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GQ', 'Экваториальная Гвинея');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ER', 'Эритрея');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'EE', 'Эстония');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SZ', 'Эсватини');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ET', 'Эфиопия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'FK', 'Фолклендские острова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'FO', 'Фарерские острова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'FJ', 'Фиджи');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'FI', 'Финляндия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'FR', 'Франция');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GF', 'Французская Гвиана');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PF', 'Французская Полинезия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TF', 'Французские Южные территории');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GA', 'Габон');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GM', 'Гамбия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GE', 'Грузия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'DE', 'Германия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GH', 'Гана');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GI', 'Гибралтар');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GR', 'Греция');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GL', 'Гренландия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GD', 'Гренада');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GP', 'Гваделупа');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GU', 'Гуам');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GT', 'Гватемала');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GG', 'Гернси');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GN', 'Гвинея');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GW', 'Гвинея-Бисау');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GY', 'Гайана');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'HT', 'Гаити');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'HM', 'Остров Херд и острова Макдональд');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'VA', 'Ватикан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'HN', 'Гондурас');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'HK', 'Гонконг');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'HU', 'Венгрия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'IS', 'Исландия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'IN', 'Индия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ID', 'Индонезия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'IR', 'Иран');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'IQ', 'Ирак');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'IE', 'Ирландия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'IM', 'Остров Мэн');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'IL', 'Израиль');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'IT', 'Италия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'JM', 'Ямайка');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'JP', 'Япония');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'JE', 'Джерси');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'JO', 'Иордания');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KZ', 'Казахстан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KE', 'Кения');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KI', 'Кирибати');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KP', 'Корейская Народно-Демократическая Республика');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KR', 'Корея, Республика');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KW', 'Кувейт');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KG', 'Кыргызстан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LA', 'Лаос');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LV', 'Латвия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LB', 'Ливан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LS', 'Лесото');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LR', 'Либерия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LY', 'Ливия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LI', 'Лихтенштейн');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LT', 'Литва');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LU', 'Люксембург');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MO', 'Макао');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MG', 'Мадагаскар');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MW', 'Малави');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MY', 'Малайзия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MV', 'Мальдивы');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ML', 'Мали');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MT', 'Мальта');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MH', 'Маршалловы острова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MQ', 'Мартиника');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MR', 'Мавритания');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MU', 'Маврикий');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'YT', 'Майотта');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MX', 'Мексика');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'FM', 'Микронезия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MD', 'Молдова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MC', 'Монако');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MN', 'Монголия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ME', 'Черногория');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MS', 'Монтсеррат');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MA', 'Марокко');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MZ', 'Мозамбик');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MM', 'Мьянма');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NA', 'Намибия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NR', 'Науру');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NP', 'Непал');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NL', 'Нидерланды');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NC', 'Новая Каледония');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NZ', 'Новая Зеландия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NI', 'Никарагуа');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NE', 'Нигер');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NG', 'Нигерия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NU', 'Ниуэ');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NF', 'Остров Норфолк');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MK', 'Северная Македония');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MP', 'Северные Марианские острова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'NO', 'Норвегия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'OM', 'Оман');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PK', 'Пакистан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PW', 'Палау');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PS', 'Палестина');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PA', 'Панама');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PG', 'Папуа — Новая Гвинея');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PY', 'Парагвай');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PE', 'Перу');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PH', 'Филиппины');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PN', 'Питкэрн');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PL', 'Польша');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PT', 'Португалия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PR', 'Пуэрто-Рико');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'QA', 'Катар');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'RE', 'Реюньон');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'RO', 'Румыния');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'RU', 'Россия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'RW', 'Руанда');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'BL', 'Сен-Бартелеми');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SH', 'Святая Елена, Вознесения и Тристан-да-Кунья');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'KN', 'Сент-Китс и Невис');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LC', 'Сент-Люсия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'MF', 'Сен-Мартен');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'PM', 'Сен-Пьер и Микелон');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'VC', 'Сент-Винсент и Гренадины');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'WS', 'Самоа');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SM', 'Сан-Марино');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ST', 'Сан-Томе и Принсипи');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SA', 'Саудовская Аравия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SN', 'Сенегал');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'RS', 'Сербия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SC', 'Сейшелы');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SL', 'Сьерра-Леоне');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SG', 'Сингапур');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SX', 'Синт-Мартен');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SK', 'Словакия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SI', 'Словения');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SB', 'Соломоновы острова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SO', 'Сомали');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ZA', 'Южная Африка');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GS', 'Южная Георгия и Южные Сандвичевы острова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SS', 'Южный Судан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ES', 'Испания');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'LK', 'Шри-Ланка');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SD', 'Судан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SR', 'Суринам');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SJ', 'Шпицберген и Ян-Майен');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SE', 'Швеция');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'CH', 'Швейцария');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'SY', 'Сирия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TW', 'Тайвань');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TJ', 'Таджикистан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TZ', 'Танзания');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TH', 'Таиланд');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TL', 'Тимор-Лесте');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TG', 'Того');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TK', 'Токелау');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TO', 'Тонга');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TT', 'Тринидад и Тобаго');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TN', 'Тунис');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TR', 'Турция');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TM', 'Туркменистан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TC', 'Теркс и Кайкос');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'TV', 'Тувалу');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'UG', 'Уганда');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'UA', 'Украина');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'AE', 'Объединенные Арабские Эмираты');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'GB', 'Великобритания');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'US', 'Соединенные Штаты');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'UM', 'Внешние малые острова США');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'UY', 'Уругвай');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'UZ', 'Узбекистан');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'VU', 'Вануату');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'VE', 'Венесуэла');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'VN', 'Вьетнам');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'VG', 'Виргинские острова, Британские');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'VI', 'Виргинские острова, США');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'WF', 'Уоллис и Футуна');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'EH', 'Западная Сахара');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'YE', 'Йемен');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ZM', 'Замбия');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('country2', 'ZW', 'Зимбабве');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('gender', 'F', 'Женский');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('gender', 'M', 'Мужской');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierTypeCode', 'PASSPORT', 'Паспорт');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierTypeCode', 'DRIVER LICENCE', 'Вод.уд.');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierTypeCode', 'OTHER', 'Другой документ');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('yesNo', 'N', 'Нет');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('yesNo', 'Y', 'Да');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'HOME-DEVICE', 'крупная и мелкая бытовая техника');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'DIGITAL-DEVICE', 'цифровая техника');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'TABLET', 'TABLET');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'NETBOOK', 'NETBOOK');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'LAPTOP', 'LAPTOP');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'MOBILE-PHONE', 'MOBILE-PHONE');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'SMARTPHONE', 'SMARTPHONE');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'PORT-AUDIO-VIDEO', 'PORT-AUDIO-VIDEO');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'E-BOOK', 'E-BOOK');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'CAR-NAVIGATOR', 'CAR-NAVIGATOR');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'CAR-DVR', 'CAR-DVR');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'GAME-CONSOLE', 'GAME-CONSOLE');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('deviceType', 'SMART-WATCH', 'SMART-WATCH');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('familyState', 'SINGLE', 'Холост / Не замужем');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('familyState', 'MARRIED', 'Состоит в браке');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('familyState', 'DIVORCED', 'Разведен(а)');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('familyState', 'WIDOWED', 'Вдовец / Вдова');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('familyState', 'CIVIL_MARRIAGE', 'Гражданский брак');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('familyState', 'SEPARATED', 'Раздельное проживание');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'PASSPORT_RF', 'Паспорт гражданина РФ');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'BIRTH_CERTIFICATE', 'Свидетельство о рождении');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'FOREIGN_PASSPORT', 'Загранпаспорт гражданина РФ');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'DRIVER_LICENSE', 'Водительское удостоверение');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'MILITARY_ID', 'Военный билет');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'SERVICE_PASSPORT', 'Служебный паспорт');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'DIPLOMATIC_PASSPORT', 'Дипломатический паспорт');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'SEAMAN_PASSPORT', 'Паспорт моряка');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'FOREIGN_PASSPORT_FOREIGN', 'Паспорт иностранного гражданина');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'RESIDENCE_PERMIT', 'Вид на жительство');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'TEMPORARY_RESIDENCE', 'Разрешение на временное проживание');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'REFUGEE_CERTIFICATE', 'Удостоверение беженца');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'STATELESS_PASSPORT', 'Паспорт лица без гражданства');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'BIRTH_CERTIFICATE_FOREIGN', 'Свидетельство о рождении (иностранное)');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('identifierType', 'OTHER', 'Иной документ');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('installmentType', 'SINGLE', 'Полная оплата премии одним платежом');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('installmentType', 'SEMI_ANNUAL', '2 платежа в год (раз в 6 месяцев)');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('installmentType', 'QUARTERLY', '4 платежа в год (раз в 3 месяца)');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('installmentType', 'MONTHLY', '12 платежей в год');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('installmentType', 'BI_MONTHLY', '6 платежей в год (раз в 2 месяца)');
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES ('installmentType', 'ANNUAL', '1 платеж в год');
