-- SQL скрипт для вставки данных в таблицу pt_metadata
-- Поля: var_code, var_name, var_path, var_type, var_value, var_cdm, nr, var_data_type
DELETE FROM pt_metadata;

INSERT INTO pt_metadata (var_code, var_name, var_path, var_type, var_value, var_cdm, nr, var_data_type) VALUES
('io_addr_addressStr', 'io.Адрес.адресная строка', 'insuredObjects[0].addresses[?(@.isPrimary)].addressStr', 'IN', NULL, 'insuredObject.addresses.addressStr', '133', 'STRING'),
('io_addr_addressStrEn', 'io.Адрес.адресная строка англ', 'insuredObjects[0].addresses[?(@.isPrimary)].addressStrEn', 'IN', NULL, 'insuredObject.addresses.addressStrEn', '134', 'STRING'),
('io_addr_building', 'io.Адрес.строение', 'insuredObjects[0].addresses[?(@.isPrimary)].building', 'IN', NULL, 'insuredObject.addresses.building', '127', 'STRING'),
('io_addr_city', 'io.Адрес.город', 'insuredObjects[0].addresses[?(@.isPrimary)].city', 'IN', NULL, 'insuredObject.addresses.city', '124', 'STRING'),
('io_addr_countryCode', 'io.Адрес.код страны', 'insuredObjects[0].addresses[?(@.isPrimary)].countryCode', 'IN', 'RU', 'insuredObject.addresses.countryCode', '122', 'STRING'),
('io_addr_ext_id', 'io.Адрес.внешний ID', 'insuredObjects[0].addresses[?(@.isPrimary)].ext_id', 'IN', NULL, 'insuredObject.addresses.ext_id', '136', 'STRING'),
('io_addr_fiasId', 'io.Адрес.код ФИАС', 'insuredObjects[0].addresses[?(@.isPrimary)].fiasId', 'IN', NULL, 'insuredObject.addresses.fiasId', '132', 'STRING'),
('io_addr_flat', 'io.Адрес.квартира', 'insuredObjects[0].addresses[?(@.isPrimary)].flat', 'IN', NULL, 'insuredObject.addresses.flat', '128', 'STRING'),
('io_addr_house', 'io.Адрес.дом', 'insuredObjects[0].addresses[?(@.isPrimary)].house', 'IN', NULL, 'insuredObject.addresses.house', '126', 'STRING'),
('io_addr_kladrId', 'io.Адрес.код КЛАДР', 'insuredObjects[0].addresses[?(@.isPrimary)].kladrId', 'IN', NULL, 'insuredObject.addresses.kladrId', '131', 'STRING'),
('io_addr_region', 'io.Адрес.регион', 'insuredObjects[0].addresses[?(@.isPrimary)].region', 'IN', NULL, 'insuredObject.addresses.region', '123', 'STRING'),
('io_addr_room', 'io.Адрес.комната', 'insuredObjects[0].addresses[?(@.isPrimary)].room', 'IN', NULL, 'insuredObject.addresses.room', '129', 'STRING'),
('io_addr_street', 'io.Адрес.улица', 'insuredObjects[0].addresses[?(@.isPrimary)].street', 'IN', NULL, 'insuredObject.addresses.street', '125', 'STRING'),
('io_addr_typeCode', 'io.Адрес.тип адреса', 'insuredObjects[0].addresses[?(@.isPrimary)].typeCode', 'IN', 'REGISTRATION', 'insuredObject.addresses.typeCode', '121', 'STRING'),
('io_addr_zipCode', 'io.Адрес.индекс', 'insuredObjects[0].addresses[?(@.isPrimary)].zipCode', 'IN', NULL, 'insuredObject.addresses.zipCode', '130', 'STRING'),
('io_email', 'Застрахованный.email', 'insuredObjects[0].contacts.email', 'IN', NULL, 'insuredObject.contacts.email', '91', 'STRING'),
('io_phone', 'Застрахованный.телефон', 'insuredObjects[0].contacts.phone', 'IN', NULL, 'insuredObject.contacts.phone', '81', 'STRING'),
('io_device_countryCode', 'Застрахованное ус-во. код страны', 'insuredObjects[0].device.countryCode', 'IN', 'RU', 'insuredObject.device.countryCode', '1009', 'STRING'),
('io_device_name', 'Застрахованное ус-во. название', 'insuredObjects[0].device.deviceName', 'IN', 'Телефон', 'insuredObject.device.deviceName', '1001', 'STRING'),
('io_device_devicePrice', 'Застрахованное ус-во. цена', 'insuredObjects[0].device.devicePrice', 'IN', '10000', 'insuredObject.device.devicePrice', '1010', 'STRING'),
('io_device_typeCode', 'Застрахованное ус-во. код типа', 'insuredObjects[0].device.deviceTypeCode', 'IN', 'PHONE', 'insuredObject.device.deviceTypeCode', '1002', 'STRING'),
('io_device_imei', 'Застрахованное ус-во. IMEI', 'insuredObjects[0].device.imei', 'IN', '1234567890', 'insuredObject.device.imei', '1007', 'STRING'),
('io_device_licenseKey', 'Застрахованное ус-во. ключ лицензии', 'insuredObjects[0].device.licenseKey', 'IN', '1234567890', 'insuredObject.device.licenseKey', '1006', 'STRING'),
('io_device_model', 'Застрахованное ус-во. модель', 'insuredObjects[0].device.model', 'IN', 'Galaxy S21', 'insuredObject.device.model', '1004', 'STRING'),
('io_device_osName', 'Застрахованное ус-во. название ОС', 'insuredObjects[0].device.osName', 'IN', 'Android', 'insuredObject.device.osName', '1008', 'STRING'),
('io_device_osVersion', 'Застрахованное ус-во. версия ОС', 'insuredObjects[0].device.osVersion', 'IN', '10', 'insuredObject.device.osVersion', '1008', 'STRING'),
('io_device_serialNr', 'Застрахованное ус-во. серийный номер', 'insuredObjects[0].device.serialNr', 'IN', '1234567890', 'insuredObject.device.serialNr', '1005', 'STRING'),
('io_device_tradeMark', 'Застрахованное ус-во. торговая марка', 'insuredObjects[0].device.tradeMark', 'IN', 'Samsung', 'insuredObject.device.tradeMark', '1003', 'STRING'),
('io_doc_countryCode', 'io.Документ.страна выдачи документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].countryCode', 'IN', 'RU', 'insuredObject.identifiers.countryCode', '110', 'STRING'),
('io_doc_dateIssue', 'io.Документ.дата выдачи', 'insuredObjects[0].identifiers[?(@.isPrimary)].dateIssue', 'IN', NULL, 'insuredObject.identifiers.dateIssue', '104', 'STRING'),
('io_doc_divisionCode', 'io.Документ.код подразделения', 'insuredObjects[0].identifiers[?(@.isPrimary)].divisionCode', 'IN', NULL, 'insuredObject.identifiers.divisionCode', '107', 'STRING'),
('io_doc_ext_id', 'io.Документ.внешний ID', 'insuredObjects[0].identifiers[?(@.isPrimary)].ext_id', 'IN', NULL, 'insuredObject.identifiers.ext_id', '109', 'STRING'),
('io_doc_number', 'io.Документ.номер документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].number', 'IN', NULL, 'insuredObject.identifiers.number', '103', 'STRING'),
('io_doc_serial', 'io.Документ.серия документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].serial', 'IN', NULL, 'insuredObject.identifiers.serial', '102', 'STRING'),
('io_doc_typeCode', 'io.Документ.код типа документа', 'insuredObjects[0].identifiers[?(@.isPrimary)].typeCode', 'IN', NULL, 'insuredObject.identifiers.typeCode', '101', 'STRING'),
('io_doc_validUntil', 'io.Документ.действительно до', 'insuredObjects[0].identifiers[?(@.isPrimary)].validUntil', 'IN', NULL, 'insuredObject.identifiers.validUntil', '105', 'STRING'),
('io_doc_whom', 'io.Документ.кем выдан', 'insuredObjects[0].identifiers[?(@.isPrimary)].whom', 'IN', NULL, 'insuredObject.identifiers.whom', '106', 'STRING'),
('io_packageCode', 'Код пакета', 'insuredObjects[0].packageCode', 'IN', '0', 'insuredObject.packageCode', '11', 'STRING'),
('io_age_end', 'Возраст застрахованного на дату окончания полиса', NULL, 'MAGIC', NULL, 'insuredObject.person.age_end', '1102', 'NUMBER'),
('io_age_issue', 'Возраст застрахованного на дату выпуска полиса', NULL, 'MAGIC', NULL, 'insuredObject.person.age_issue', '1101', 'NUMBER'),
('io_birthDate', 'Застрахованный.дата рождения', 'insuredObjects[0].person.birthDate', 'IN', NULL, 'insuredObject.person.birthDate', '4', 'STRING'),
('io_birthPlace', 'Застрахованный.место рождения', 'insuredObjects[0].person.birthPlace', 'IN', NULL, 'insuredObject.person.birthPlace', '7', 'STRING'),
('io_citizenship', 'Застрахованный.гражданство', 'insuredObjects[0].person.citizenship', 'IN', 'RU', 'insuredObject.person.citizenship', '8', 'STRING'),
('io_ext_id', 'Застрахованный.внешний ID', 'insuredObjects[0].person.ext_id', 'IN', NULL, 'insuredObject.person.ext_id', '14', 'STRING'),
('io_familyState', 'Застрахованный.семейное положение', 'insuredObjects[0].person.familyState', 'IN', 'SINGLE', 'insuredObject.person.familyState', '10', 'STRING'),
('io_firstName', 'Застрахованный.имя', 'insuredObjects[0].person.firstName', 'IN', NULL, 'insuredObject.person.firstName', '1', 'STRING'),
('io_fullName', 'Застрахованный.полное ФИО', 'insuredObjects[0].person.fullName', 'IN', NULL, 'insuredObject.person.fullName', '5', 'STRING'),
('io_fullNameEn', 'Застрахованный.полное ФИО англ', 'insuredObjects[0].person.fullNameEn', 'IN', NULL, 'insuredObject.person.fullNameEn', '6', 'STRING'),
('io_gender', 'Застрахованный.пол', 'insuredObjects[0].person.gender', 'IN', NULL, 'insuredObject.person.gender', '9', 'STRING'),
('io_isPublicOfficial', 'Застрахованный.признак ПДЛ', 'insuredObjects[0].person.isPublicOfficial', 'IN', NULL, 'insuredObject.person.isPublicOfficial', '11', 'STRING'),
('io_lastName', 'Застрахованный.фамилия', 'insuredObjects[0].person.lastName', 'IN', NULL, 'insuredObject.person.lastName', '2', 'STRING'),
('io_middleName', 'Застрахованный.отчество', 'insuredObjects[0].person.middleName', 'IN', NULL, 'insuredObject.person.middleName', '3', 'STRING'),
('io_buildingArea', 'Имущество.площадь здания', 'insuredObjects[0].property.buildingArea', 'IN', '0', 'insuredObject.property.buildingArea', '1025', 'NUMBER'),
('io_buildingValue', 'Имущество.стоимость здания', 'insuredObjects[0].property.buildingValue', 'IN', '0', 'insuredObject.property.buildingValue', '1027', 'NUMBER'),
('io_cadastrNr', 'Имущество.кадастровый номер', 'insuredObjects[0].property.cadastrNr', 'IN', '77:07:0018002:2590', 'insuredObject.property.cadastrNr', '1018', 'STRING'),
('io_ceilingMaterial', 'Имущество.материал перекрытий', 'insuredObjects[0].property.ceilingMaterial', 'IN', 'Смешанные', 'insuredObject.property.ceilingMaterial', '1021', 'STRING'),
('io_ceilingMaterialOther', 'Имущество.материал перекрытий другой', 'insuredObjects[0].property.ceilingMaterialOther', 'IN', 'Смешанные', 'insuredObject.property.ceilingMaterialOther', '1022', 'STRING'),
('io_commissioningDate', 'Имущество.дата ввода в эксплуатацию', 'insuredObjects[0].property.commissioningDate', 'IN', NULL, 'insuredObject.property.commissioningDate', '1033', 'STRING'),
('io_constructionYear', 'Имущество.год постройки', 'insuredObjects[0].property.constructionYear', 'IN', NULL, 'insuredObject.property.constructionYear', '1023', 'STRING'),
('io_floor', 'Имущество.этаж', 'insuredObjects[0].property.floor', 'IN', '0', 'insuredObject.property.floor', '1034', 'NUMBER'),
('io_isNewBuilding', 'Имущество.новостройка', 'insuredObjects[0].property.isNewBuilding', 'IN', NULL, 'insuredObject.property.isNewBuilding', '1031', 'STRING'),
('io_landArea', 'Имущество.площадь участка', 'insuredObjects[0].property.landArea', 'IN', '0', 'insuredObject.property.landArea', '1026', 'NUMBER'),
('io_numberOfFloors', 'Имущество.количество этажей', 'insuredObjects[0].property.numberOfFloors', 'IN', '0', 'insuredObject.property.numberOfFloors', '1029', 'NUMBER'),
('io_propertyLocation', 'Имущество.расположение имущества', 'insuredObjects[0].property.propertyLocation', 'IN', 'В многоквартирном доме', 'insuredObject.property.propertyLocation', '1030', 'STRING'),
('io_propertyTypeCode', 'Имущество.тип имущества код', 'insuredObjects[0].property.propertyType.code', 'IN', NULL, 'insuredObject.property.propertyType.code', '1001', 'STRING'),
('io_propertyValue', 'Имущество.стоимость имущества', 'insuredObjects[0].property.propertyValue', 'IN', '0', 'insuredObject.property.propertyValue', '1032', 'NUMBER'),
('io_repairYear', 'Имущество.год ремонта', 'insuredObjects[0].property.repairYear', 'IN', NULL, 'insuredObject.property.repairYear', '1024', 'STRING'),
('io_wallsMaterial', 'Имущество.материал стен', 'insuredObjects[0].property.wallsMaterial', 'IN', 'Каменные, кирпичные', 'insuredObject.property.wallsMaterial', '1019', 'STRING'),
('io_wallsMaterialOther', 'Имущество.материал стен другой', 'insuredObjects[0].property.wallsMaterialOther', 'IN', 'Каменные, кирпичные', 'insuredObject.property.wallsMaterialOther', '1020', 'STRING'),
('io_wearCoefficient', 'Имущество.коэффициент износа', 'insuredObjects[0].property.wearCoefficient', 'IN', '0', 'insuredObject.property.wearCoefficient', '1028', 'NUMBER'),
('rf_profSport', 'Профессиональный спорт', 'insuredObjects[0].riskFactors.profSport', 'IN', '0', 'insuredObject.riskFactors.profSport', '2040', 'STRING'),
('rf_sport1', 'Доп.риск спорт #1', 'insuredObjects[0].riskFactors.sport1', 'IN', '0', 'insuredObject.riskFactors.sport1', '2034', 'STRING'),
('rf_sport2', 'Доп.риск спорт #2', 'insuredObjects[0].riskFactors.sport2', 'IN', '0', 'insuredObject.riskFactors.sport2', '2035', 'STRING'),
('rf_sport3', 'Доп.риск спорт #3', 'insuredObjects[0].riskFactors.sport3', 'IN', '0', 'insuredObject.riskFactors.sport3', '2036', 'STRING'),
('rf_sport4', 'Доп.риск спорт #4', 'insuredObjects[0].riskFactors.sport4', 'IN', '0', 'insuredObject.riskFactors.sport4', '2037', 'STRING'),
('rf_sport5', 'Доп.риск спорт #5', 'insuredObjects[0].riskFactors.sport5', 'IN', '0', 'insuredObject.riskFactors.sport5', '2038', 'STRING'),
('io_sumInsured', 'Страховая сумма объекта страхования', 'insuredObjects[0].sumInsured', 'IN', '100000', 'insuredObject.sumInsured', '10', 'NUMBER'),
('io_arrivalCity', 'город прилета', 'insuredObjects[0].travelSegments[*].arrivalCity', 'IN', NULL, 'insuredObject.travelSegments.arrivalCity', '1005', 'STRING'),
('io_departureCity', 'город вылета', 'insuredObjects[0].travelSegments[*].departureCity', 'IN', NULL, 'insuredObject.travelSegments.departureCity', '1004', 'STRING'),
('io_departureDate', 'дата вылета', 'insuredObjects[0].travelSegments[*].departureDate', 'IN', NULL, 'insuredObject.travelSegments.departureDate', '1002', 'STRING'),
('io_departureTime', 'время вылета', 'insuredObjects[0].travelSegments[*].departureTime', 'IN', NULL, 'insuredObject.travelSegments.departureTime', '1003', 'STRING'),
('io_legs', 'количество перелетов', 'insuredObjects[0].travelSegments[*].count()', 'IN', NULL, 'insuredObject.travelSegments.legs', '101', 'NUMBER'),
('io_ticketNr', 'номер билета', 'insuredObjects[0].travelSegments[*].ticketNr', 'IN', NULL, 'insuredObject.travelSegments.ticketNr', '1001', 'STRING'),
('io_ticketPrice', 'стоимость билета', 'insuredObjects[0].travelSegments[*].ticketPrice.sum()', 'IN', NULL, 'insuredObject.travelSegments.ticketPrice', '101', 'NUMBER'),
('io_isResident', 'Застрахованный.резидент РФ', 'insuredObjects[0].person.isResident', 'IN', 'true', 'insuredObjects[0].person.isResident', '12', 'STRING'),
('pl_commRate', 'Процент кВ по договору', 'commission.appliedCommissionRate', 'IN', NULL, 'policy.commission.appliedCommissionRate', '1050', 'NUMBER'),
('gross_up_factor', 'gross_up_factor 1/(1-kV)', NULL, 'MAGIC', NULL, 'policy.magic.grossUpFactor', '1050', 'NUMBER'),
('pl_TermDays', 'Срок полиса в днях', NULL, 'MAGIC', NULL, 'policy.magic.termDays', '1202', 'NUMBER'),
('pl_TermMonths', 'Срок полиса в месяцах', NULL, 'MAGIC', NULL, 'policy.magic.termMonths', '1201', 'NUMBER'),
('pl_endDate', 'дата окончания договора', 'endDate', 'IN', NULL, 'policy.policy.endDate', '12', 'STRING'),
('pl_issueDate', 'дата выпуска договора', 'issueDate', 'IN', NULL, 'policy.policy.issueDate', '15', 'STRING'),
('pl_policyNumber', 'номер договора', 'policyNumber', 'IN', NULL, 'policy.policy.policyNumber', '13', 'STRING'),
('pl_premium', 'премия по договору', 'premium', 'IN', NULL, 'policy.policy.premium', '14', 'STRING'),
('pl_productCode', 'Код продукта', 'productCode', 'IN', NULL, 'policy.policy.productCode', '10', 'STRING'),
('pl_startDate', 'дата начала действия договора', 'startDate', 'IN', NULL, 'policy.policy.startDate', '11', 'STRING'),

('ph_addr_addressStr', 'ph.Адрес.адресная строка', 'policyHolder.addresses[?(@.isPrimary)].addressStr', 'IN', NULL, 'policyHolder.addresses.addressStr', '133', 'STRING'),
('ph_addr_addressStrEn', 'ph.Адрес.адресная строка англ', 'policyHolder.addresses[?(@.isPrimary)].addressStrEn', 'IN', NULL, 'policyHolder.addresses.addressStrEn', '134', 'STRING'),
('ph_addr_building', 'ph.Адрес.строение', 'policyHolder.addresses[?(@.isPrimary)].building', 'IN', NULL, 'policyHolder.addresses.building', '127', 'STRING'),
('ph_addr_city', 'ph.Адрес.город', 'policyHolder.addresses[?(@.isPrimary)].city', 'IN', NULL, 'policyHolder.addresses.city', '124', 'STRING'),
('ph_addr_countryCode', 'ph.Адрес.код страны', 'policyHolder.addresses[?(@.isPrimary)].countryCode', 'IN', 'RU', 'policyHolder.addresses.countryCode', '122', 'STRING'),
('ph_addr_ext_id', 'ph.Адрес.внешний ID', 'policyHolder.addresses[?(@.isPrimary)].ext_id', 'IN', NULL, 'policyHolder.addresses.ext_id', '136', 'STRING'),
('ph_addr_fiasId', 'ph.Адрес.код ФИАС', 'policyHolder.addresses[?(@.isPrimary)].fiasId', 'IN', NULL, 'policyHolder.addresses.fiasId', '132', 'STRING'),
('ph_addr_flat', 'ph.Адрес.квартира', 'policyHolder.addresses[?(@.isPrimary)].flat', 'IN', NULL, 'policyHolder.addresses.flat', '128', 'STRING'),
('ph_addr_house', 'ph.Адрес.дом', 'policyHolder.addresses[?(@.isPrimary)].house', 'IN', NULL, 'policyHolder.addresses.house', '126', 'STRING'),
('ph_addr_kladrId', 'ph.Адрес.код КЛАДР', 'policyHolder.addresses[?(@.isPrimary)].kladrId', 'IN', NULL, 'policyHolder.addresses.kladrId', '131', 'STRING'),
('ph_addr_region', 'ph.Адрес.регион', 'policyHolder.addresses[?(@.isPrimary)].region', 'IN', NULL, 'policyHolder.addresses.region', '123', 'STRING'),
('ph_addr_room', 'ph.Адрес.комната', 'policyHolder.addresses[?(@.isPrimary)].room', 'IN', NULL, 'policyHolder.addresses.room', '129', 'STRING'),
('ph_addr_street', 'ph.Адрес.улица', 'policyHolder.addresses[?(@.isPrimary)].street', 'IN', NULL, 'policyHolder.addresses.street', '125', 'STRING'),
('ph_addr_typeCode', 'ph.Адрес.тип адреса', 'policyHolder.addresses[?(@.isPrimary)].typeCode', 'IN', 'REGISTRATION', 'policyHolder.addresses.typeCode', '121', 'STRING'),
('ph_addr_zipCode', 'ph.Адрес.индекс', 'policyHolder.addresses[?(@.isPrimary)].zipCode', 'IN', NULL, 'policyHolder.addresses.zipCode', '130', 'STRING'),

('ph_email', 'Страхователь.email', 'policyHolder.contacts.email', 'IN', NULL, 'policyHolder.contacts.email', '91', 'STRING'),
('ph_phone', 'Страхователь.телефон', 'policyHolder.contacts.phone', 'IN', NULL, 'policyHolder.contacts.phone', '81', 'STRING'),

('ph_doc_countryCode', 'ph.Документ.страна выдачи документа', 'policyHolder.identifiers[?(@.isPrimary)].countryCode', 'IN', 'RU', 'policyHolder.identifiers.countryCode', '110', 'STRING'),
('ph_doc_dateIssue', 'ph.Документ.дата выдачи', 'policyHolder.identifiers[?(@.isPrimary)].dateIssue', 'IN', NULL, 'policyHolder.identifiers.dateIssue', '104', 'STRING'),
('ph_doc_divisionCode', 'ph.Документ.код подразделения', 'policyHolder.identifiers[?(@.isPrimary)].divisionCode', 'IN', NULL, 'policyHolder.identifiers.divisionCode', '107', 'STRING'),
('ph_doc_ext_id', 'ph.Документ.внешний ID', 'policyHolder.identifiers[?(@.isPrimary)].ext_id', 'IN', NULL, 'policyHolder.identifiers.ext_id', '109', 'STRING'),
('ph_doc_number', 'ph.Документ.номер документа', 'policyHolder.identifiers[?(@.isPrimary)].number', 'IN', NULL, 'policyHolder.identifiers.number', '103', 'STRING'),
('ph_doc_serial', 'ph.Документ.серия документа', 'policyHolder.identifiers[?(@.isPrimary)].serial', 'IN', NULL, 'policyHolder.identifiers.serial', '102', 'STRING'),
('ph_doc_typeCode', 'ph.Документ.код типа документа', 'policyHolder.identifiers[?(@.isPrimary)].typeCode', 'IN', NULL, 'policyHolder.identifiers.typeCode', '101', 'STRING'),
('ph_doc_validUntil', 'ph.Документ.действительно до', 'policyHolder.identifiers[?(@.isPrimary)].validUntil', 'IN', NULL, 'policyHolder.identifiers.validUntil', '105', 'STRING'),
('ph_doc_whom', 'ph.Документ.кем выдан', 'policyHolder.identifiers[?(@.isPrimary)].whom', 'IN', NULL, 'policyHolder.identifiers.whom', '106', 'STRING'),

('ph_org_bic', 'Страхователь.БИК', 'policyHolder.organization.bic', 'IN', NULL, 'policyHolder.organization.bic', '60', 'STRING'),
('ph_country', 'Страхователь.код страны регистрации', 'policyHolder.organization.country', 'IN', NULL, 'policyHolder.organization.country', '51', 'STRING'),
('ph_org_ext_id', 'Страхователь.внешний ID', 'policyHolder.organization.ext_id', 'IN', NULL, 'policyHolder.organization.ext_id', '64', 'STRING'),
('ph_org_fullName', 'Страхователь.полное наименование юр.лица', 'policyHolder.organization.fullName', 'IN', NULL, 'policyHolder.organization.fullName', '53', 'STRING'),
('ph_org_fullNameEn', 'Страхователь.полное наименование  юр.лица англ', 'policyHolder.organization.fullNameEn', 'IN', NULL, 'policyHolder.organization.fullNameEn', '54', 'STRING'),
('ph_org_group', 'Страхователь.Gруппа страхователя ЮЛ', 'policyHolder.organization.group', 'IN', NULL, 'policyHolder.organization.group', '62', 'STRING'),
('ph_org_inn', 'Страхователь.ИНН юр.лица', 'policyHolder.organization.inn', 'IN', NULL, 'policyHolder.organization.inn', '52', 'STRING'),
('ph_org_isResident', 'Страхователь.резидент РФ юр.лица', 'policyHolder.organization.isResident', 'IN', 'true', 'policyHolder.organization.isResident', '61', 'STRING'),
('ph_org_kpp', 'Страхователь.КПП', 'policyHolder.organization.kpp', 'IN', NULL, 'policyHolder.organization.kpp', '57', 'STRING'),
('ph_org_legalForm', 'Страхователь.организационно-правовая форма', 'policyHolder.organization.legalForm', 'IN', NULL, 'policyHolder.organization.legalForm', '56', 'STRING'),
('ph_org_nciCode', 'Страхователь.НСИ код', 'policyHolder.organization.nciCode', 'IN', NULL, 'policyHolder.organization.nciCode', '65', 'STRING'),
('ph_org_ogrn', 'Страхователь.ОГРН', 'policyHolder.organization.ogrn', 'IN', NULL, 'policyHolder.organization.ogrn', '58', 'STRING'),
('ph_org_okpo', 'Страхователь.ОКПО', 'policyHolder.organization.okpo', 'IN', NULL, 'policyHolder.organization.okpo', '59', 'STRING'),
('ph_org_shortName', 'Страхователь.краткое наименование юр.лица', 'policyHolder.organization.shortName', 'IN', NULL, 'policyHolder.organization.shortName', '55', 'STRING'),

('ph_age_end', 'Страхователь.возраст на дату окончания договора', NULL, 'MAGIC', NULL, 'policyHolder.person.age_end', '1115', 'NUMBER'),
('ph_age_issue', 'Страхователь.возраст на дату выпуска договора', NULL, 'MAGIC', NULL, 'policyHolder.person.age_issue', '1115', 'NUMBER'),
('ph_birthDate', 'Страхователь.дата рождения', 'policyHolder.person.birthDate', 'IN', NULL, 'policyHolder.person.birthDate', '4', 'STRING'),
('ph_birthPlace', 'Страхователь.место рождения', 'policyHolder.person.birthPlace', 'IN', NULL, 'policyHolder.person.birthPlace', '7', 'STRING'),
('ph_citizenship', 'Страхователь.гражданство', 'policyHolder.person.citizenship', 'IN', 'RU', 'policyHolder.person.citizenship', '8', 'STRING'),
('ph_ext_id', 'Страхователь.внешний ID', 'policyHolder.person.ext_id', 'IN', NULL, 'policyHolder.person.ext_id', '14', 'STRING'),
('ph_familyState', 'Страхователь.семейное положение', 'policyHolder.person.familyState', 'IN', 'SINGLE', 'policyHolder.person.familyState', '10', 'STRING'),
('ph_firstName', 'Страхователь.имя', 'policyHolder.person.firstName', 'IN', NULL, 'policyHolder.person.firstName', '1', 'STRING'),
('ph_fullName', 'Страхователь.полное ФИО', 'policyHolder.person.fullName', 'IN', NULL, 'policyHolder.person.fullName', '5', 'STRING'),
('ph_fullNameEn', 'Страхователь.полное ФИО англ', 'policyHolder.person.fullNameEn', 'IN', NULL, 'policyHolder.person.fullNameEn', '6', 'STRING'),
('ph_gender', 'Страхователь.пол', 'policyHolder.person.gender', 'IN', NULL, 'policyHolder.person.gender', '9', 'STRING'),
('ph_isPublicOfficial', 'Страхователь.признак ПДЛ', 'policyHolder.person.isPublicOfficial', 'IN', NULL, 'policyHolder.person.isPublicOfficial', '11', 'STRING'),
('ph_isResident', 'Страхователь.резидент РФ', 'policyHolder.person.isResident', 'IN', 'true', 'policyHolder.person.isResident', '12', 'STRING'),
('ph_lastName', 'Страхователь.фамилия', 'policyHolder.person.lastName', 'IN', NULL, 'policyHolder.person.lastName', '2', 'STRING'),
('ph_middleName', 'Страхователь.отчество', 'policyHolder.person.middleName', 'IN', NULL, 'policyHolder.person.middleName', '3', 'STRING');


-- Вставка стран с кодами ISO Alpha2
INSERT INTO pt_refdata (ref_code, md_code, md_name) VALUES
('country2', 'AF', 'Афганистан'),
('country2', 'AX', 'Аландские острова'),
('country2', 'AL', 'Албания'),
('country2', 'DZ', 'Алжир'),
('country2', 'AS', 'Американское Самоа'),
('country2', 'AD', 'Андорра'),
('country2', 'AO', 'Ангола'),
('country2', 'AI', 'Ангилья'),
('country2', 'AQ', 'Антарктида'),
('country2', 'AG', 'Антигуа и Барбуда'),
('country2', 'AR', 'Аргентина'),
('country2', 'AM', 'Армения'),
('country2', 'AW', 'Аруба'),
('country2', 'AU', 'Австралия'),
('country2', 'AT', 'Австрия'),
('country2', 'AZ', 'Азербайджан'),
('country2', 'BS', 'Багамы'),
('country2', 'BH', 'Бахрейн'),
('country2', 'BD', 'Бангладеш'),
('country2', 'BB', 'Барбадос'),
('country2', 'BY', 'Беларусь'),
('country2', 'BE', 'Бельгия'),
('country2', 'BZ', 'Белиз'),
('country2', 'BJ', 'Бенин'),
('country2', 'BM', 'Бермуды'),
('country2', 'BT', 'Бутан'),
('country2', 'BO', 'Боливия'),
('country2', 'BQ', 'Бонайре, Синт-Эстатиус и Саба'),
('country2', 'BA', 'Босния и Герцеговина'),
('country2', 'BW', 'Ботсвана'),
('country2', 'BV', 'Остров Буве'),
('country2', 'BR', 'Бразилия'),
('country2', 'IO', 'Британская территория в Индийском океане'),
('country2', 'BN', 'Бруней'),
('country2', 'BG', 'Болгария'),
('country2', 'BF', 'Буркина-Фасо'),
('country2', 'BI', 'Бурунди'),
('country2', 'CV', 'Кабо-Верде'),
('country2', 'KH', 'Камбоджа'),
('country2', 'CM', 'Камерун'),
('country2', 'CA', 'Канада'),
('country2', 'KY', 'Каймановы острова'),
('country2', 'CF', 'Центральноафриканская Республика'),
('country2', 'TD', 'Чад'),
('country2', 'CL', 'Чили'),
('country2', 'CN', 'Китай'),
('country2', 'CX', 'Остров Рождества'),
('country2', 'CC', 'Кокосовые острова'),
('country2', 'CO', 'Колумбия'),
('country2', 'KM', 'Коморы'),
('country2', 'CG', 'Конго'),
('country2', 'CD', 'Конго, Демократическая Республика'),
('country2', 'CK', 'Острова Кука'),
('country2', 'CR', 'Коста-Рика'),
('country2', 'CI', 'Кот-д''Ивуар'),
('country2', 'HR', 'Хорватия'),
('country2', 'CU', 'Куба'),
('country2', 'CW', 'Кюрасао'),
('country2', 'CY', 'Кипр'),
('country2', 'CZ', 'Чехия'),
('country2', 'DK', 'Дания'),
('country2', 'DJ', 'Джибути'),
('country2', 'DM', 'Доминика'),
('country2', 'DO', 'Доминиканская Республика'),
('country2', 'EC', 'Эквадор'),
('country2', 'EG', 'Египет'),
('country2', 'SV', 'Сальвадор'),
('country2', 'GQ', 'Экваториальная Гвинея'),
('country2', 'ER', 'Эритрея'),
('country2', 'EE', 'Эстония'),
('country2', 'SZ', 'Эсватини'),
('country2', 'ET', 'Эфиопия'),
('country2', 'FK', 'Фолклендские острова'),
('country2', 'FO', 'Фарерские острова'),
('country2', 'FJ', 'Фиджи'),
('country2', 'FI', 'Финляндия'),
('country2', 'FR', 'Франция'),
('country2', 'GF', 'Французская Гвиана'),
('country2', 'PF', 'Французская Полинезия'),
('country2', 'TF', 'Французские Южные территории'),
('country2', 'GA', 'Габон'),
('country2', 'GM', 'Гамбия'),
('country2', 'GE', 'Грузия'),
('country2', 'DE', 'Германия'),
('country2', 'GH', 'Гана'),
('country2', 'GI', 'Гибралтар'),
('country2', 'GR', 'Греция'),
('country2', 'GL', 'Гренландия'),
('country2', 'GD', 'Гренада'),
('country2', 'GP', 'Гваделупа'),
('country2', 'GU', 'Гуам'),
('country2', 'GT', 'Гватемала'),
('country2', 'GG', 'Гернси'),
('country2', 'GN', 'Гвинея'),
('country2', 'GW', 'Гвинея-Бисау'),
('country2', 'GY', 'Гайана'),
('country2', 'HT', 'Гаити'),
('country2', 'HM', 'Остров Херд и острова Макдональд'),
('country2', 'VA', 'Ватикан'),
('country2', 'HN', 'Гондурас'),
('country2', 'HK', 'Гонконг'),
('country2', 'HU', 'Венгрия'),
('country2', 'IS', 'Исландия'),
('country2', 'IN', 'Индия'),
('country2', 'ID', 'Индонезия'),
('country2', 'IR', 'Иран'),
('country2', 'IQ', 'Ирак'),
('country2', 'IE', 'Ирландия'),
('country2', 'IM', 'Остров Мэн'),
('country2', 'IL', 'Израиль'),
('country2', 'IT', 'Италия'),
('country2', 'JM', 'Ямайка'),
('country2', 'JP', 'Япония'),
('country2', 'JE', 'Джерси'),
('country2', 'JO', 'Иордания'),
('country2', 'KZ', 'Казахстан'),
('country2', 'KE', 'Кения'),
('country2', 'KI', 'Кирибати'),
('country2', 'KP', 'Корейская Народно-Демократическая Республика'),
('country2', 'KR', 'Корея, Республика'),
('country2', 'KW', 'Кувейт'),
('country2', 'KG', 'Кыргызстан'),
('country2', 'LA', 'Лаос'),
('country2', 'LV', 'Латвия'),
('country2', 'LB', 'Ливан'),
('country2', 'LS', 'Лесото'),
('country2', 'LR', 'Либерия'),
('country2', 'LY', 'Ливия'),
('country2', 'LI', 'Лихтенштейн'),
('country2', 'LT', 'Литва'),
('country2', 'LU', 'Люксембург'),
('country2', 'MO', 'Макао'),
('country2', 'MG', 'Мадагаскар'),
('country2', 'MW', 'Малави'),
('country2', 'MY', 'Малайзия'),
('country2', 'MV', 'Мальдивы'),
('country2', 'ML', 'Мали'),
('country2', 'MT', 'Мальта'),
('country2', 'MH', 'Маршалловы острова'),
('country2', 'MQ', 'Мартиника'),
('country2', 'MR', 'Мавритания'),
('country2', 'MU', 'Маврикий'),
('country2', 'YT', 'Майотта'),
('country2', 'MX', 'Мексика'),
('country2', 'FM', 'Микронезия'),
('country2', 'MD', 'Молдова'),
('country2', 'MC', 'Монако'),
('country2', 'MN', 'Монголия'),
('country2', 'ME', 'Черногория'),
('country2', 'MS', 'Монтсеррат'),
('country2', 'MA', 'Марокко'),
('country2', 'MZ', 'Мозамбик'),
('country2', 'MM', 'Мьянма'),
('country2', 'NA', 'Намибия'),
('country2', 'NR', 'Науру'),
('country2', 'NP', 'Непал'),
('country2', 'NL', 'Нидерланды'),
('country2', 'NC', 'Новая Каледония'),
('country2', 'NZ', 'Новая Зеландия'),
('country2', 'NI', 'Никарагуа'),
('country2', 'NE', 'Нигер'),
('country2', 'NG', 'Нигерия'),
('country2', 'NU', 'Ниуэ'),
('country2', 'NF', 'Остров Норфолк'),
('country2', 'MK', 'Северная Македония'),
('country2', 'MP', 'Северные Марианские острова'),
('country2', 'NO', 'Норвегия'),
('country2', 'OM', 'Оман'),
('country2', 'PK', 'Пакистан'),
('country2', 'PW', 'Палау'),
('country2', 'PS', 'Палестина'),
('country2', 'PA', 'Панама'),
('country2', 'PG', 'Папуа — Новая Гвинея'),
('country2', 'PY', 'Парагвай'),
('country2', 'PE', 'Перу'),
('country2', 'PH', 'Филиппины'),
('country2', 'PN', 'Питкэрн'),
('country2', 'PL', 'Польша'),
('country2', 'PT', 'Португалия'),
('country2', 'PR', 'Пуэрто-Рико'),
('country2', 'QA', 'Катар'),
('country2', 'RE', 'Реюньон'),
('country2', 'RO', 'Румыния'),
('country2', 'RU', 'Россия'),
('country2', 'RW', 'Руанда'),
('country2', 'BL', 'Сен-Бартелеми'),
('country2', 'SH', 'Святая Елена, Вознесения и Тристан-да-Кунья'),
('country2', 'KN', 'Сент-Китс и Невис'),
('country2', 'LC', 'Сент-Люсия'),
('country2', 'MF', 'Сен-Мартен'),
('country2', 'PM', 'Сен-Пьер и Микелон'),
('country2', 'VC', 'Сент-Винсент и Гренадины'),
('country2', 'WS', 'Самоа'),
('country2', 'SM', 'Сан-Марино'),
('country2', 'ST', 'Сан-Томе и Принсипи'),
('country2', 'SA', 'Саудовская Аравия'),
('country2', 'SN', 'Сенегал'),
('country2', 'RS', 'Сербия'),
('country2', 'SC', 'Сейшелы'),
('country2', 'SL', 'Сьерра-Леоне'),
('country2', 'SG', 'Сингапур'),
('country2', 'SX', 'Синт-Мартен'),
('country2', 'SK', 'Словакия'),
('country2', 'SI', 'Словения'),
('country2', 'SB', 'Соломоновы острова'),
('country2', 'SO', 'Сомали'),
('country2', 'ZA', 'Южная Африка'),
('country2', 'GS', 'Южная Георгия и Южные Сандвичевы острова'),
('country2', 'SS', 'Южный Судан'),
('country2', 'ES', 'Испания'),
('country2', 'LK', 'Шри-Ланка'),
('country2', 'SD', 'Судан'),
('country2', 'SR', 'Суринам'),
('country2', 'SJ', 'Шпицберген и Ян-Майен'),
('country2', 'SE', 'Швеция'),
('country2', 'CH', 'Швейцария'),
('country2', 'SY', 'Сирия'),
('country2', 'TW', 'Тайвань'),
('country2', 'TJ', 'Таджикистан'),
('country2', 'TZ', 'Танзания'),
('country2', 'TH', 'Таиланд'),
('country2', 'TL', 'Тимор-Лесте'),
('country2', 'TG', 'Того'),
('country2', 'TK', 'Токелау'),
('country2', 'TO', 'Тонга'),
('country2', 'TT', 'Тринидад и Тобаго'),
('country2', 'TN', 'Тунис'),
('country2', 'TR', 'Турция'),
('country2', 'TM', 'Туркменистан'),
('country2', 'TC', 'Теркс и Кайкос'),
('country2', 'TV', 'Тувалу'),
('country2', 'UG', 'Уганда'),
('country2', 'UA', 'Украина'),
('country2', 'AE', 'Объединенные Арабские Эмираты'),
('country2', 'GB', 'Великобритания'),
('country2', 'US', 'Соединенные Штаты'),
('country2', 'UM', 'Внешние малые острова США'),
('country2', 'UY', 'Уругвай'),
('country2', 'UZ', 'Узбекистан'),
('country2', 'VU', 'Вануату'),
('country2', 'VE', 'Венесуэла'),
('country2', 'VN', 'Вьетнам'),
('country2', 'VG', 'Виргинские острова, Британские'),
('country2', 'VI', 'Виргинские острова, США'),
('country2', 'WF', 'Уоллис и Футуна'),
('country2', 'EH', 'Западная Сахара'),
('country2', 'YE', 'Йемен'),
('country2', 'ZM', 'Замбия'),
('country2', 'ZW', 'Зимбабве');

ALTER TABLE coefficient_data ALTER COLUMN id DROP DEFAULT;

-- Устанавливаем новый DEFAULT с другой sequence
ALTER TABLE coefficient_data ALTER COLUMN id 
    SET DEFAULT nextval('coefficient_data_seq'::regclass);

    CREATE UNIQUE INDEX IF NOT EXISTS idx_acc_commission_rates_uk
    ON acc_commission_rates(account_id, product_id, action)
    WHERE is_deleted = FALSE;

ALTER TABLE pt_number_generators ADD UNIQUE (tid, product_code);
