CREATE SEQUENCE IF NOT EXISTS pt_lobs_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS pt_products_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS pt_product_versions_seq START WITH 1 INCREMENT BY 1;